Cargo.lock, Cargo.toml, deny.toml, lib/saluki-components/src/sources/dogstatsd/mod.rs, lib/saluki-io/Cargo.toml, lib/saluki-io/src/deser/macros.rs, lib/saluki-io/src/deser/mod.rs, lib/saluki-io/src/net/addr.rs, lib/saluki-io/src/net/listener.rs, lib/saluki-io/src/net/mod.rs, lib/saluki-io/src/net/stream.rs, lib/saluki-io/src/net/unix/ancillary.rs, lib/saluki-io/src/net/unix/linux.rs, lib/saluki-io/src/net/unix/mod.rs, lib/saluki-io/src/net/unix/non_linux.rs, lib/saluki-io/src/net/unix/recvmsg.rs
As part of metric enrichment, we need to know where a metric originates from. In some cases, this can be [signaled directly](https://docs.datadoghq.com/developers/dogstatsd/datagram_shell/?tab=metrics#dogstatsd-protocol-v12) in the metric payload, and in other cases, we can figure it out based on the socket peer.
In particular, when using Unix domain sockets, we can set the `SO_PASSCRED` socket option on Linux, which allows receive calls (`recvmsg`, in particular) to be able to collect "ancillary data" in an out-of-band control buffer. This data is then coerceable into specific data structures, such as [`ucred`](https://elixir.bootlin.com/linux/2.1.123/source/include/linux/socket.h#L125), which can be used to get the process ID of the socket peer.
However, both the Rust standard library …
=> io: add support for origin detection via `SO_PEERCRED`

lib/saluki-env/src/host/hostname/kubernetes.rs
This commit removes a minor build issue that pops up on OS X. Most of the build issues are around the use of `libc::ucred` in ancillary.rs which is not exposed by OS X's libc. This commit does nothing for that, instead resolving a simple-to-address problem with a function being await that doesn't need to be, hidden on Linux owing to feature flags.
=> Fix a minor build issue on OS X

lib/saluki-io/src/deser/codec/dogstatsd.rs
When a dogstatsd msg fails to parse, the default print formatter for `[u8]` just prints the codepoint values, which is not helpful.
Dogstatsd messages are supposed to be utf8-encoded, so this prints out the lossy version of a utf8-str.
Before:
```
2024-04-30T18:23:33.608060Z ERROR saluki_components::sources::dogstatsd: Failed to decode events. error=failed to decode events: decoder error: structural error: encountered error 'Tag': [124, 112, 72, 105, 105, 100, 114, 108
, 120, 87, 124, 49, 124, 104, 58, 84, 121, 87, 107, 55, 124, 109, 58, 102, 121, 65, 50, 113, 101, 90, 55, 55, 84, 51, 108, 100, 50, 110, 83, 50, 121, 83, 73, 86, 79, 55, 74, 116, 90, 99, 112, 65, 103, 111, 76, 97, 66, 103, 89
, 70, 111, 102, 66, 50, 119, 99, 113, 79, 70, 70, 48, 101, 112, 86, 52, 49, 50, 121, 108, 90, 50, …
```
=> Prints out utf8 interp of failed msg parse

.gitlab/single-machine-performance/regression_detector-dogstatsd.yml, .gitlab/single-machine-performance/regression_detector.yml
This commit updates the pr-commenter command so that we include a header showing the different targets. We also attempt to emit the markdown and not HTML versions of the analysis report.
=> Update Regression Detector pr-commenter command

.gitlab/single-machine-performance/regression_detector-dogstatsd.yml, .gitlab/single-machine-performance/regression_detector.yml, test/smp/regression/dogstatsd/cases/uds_dogstatsd_to_api/lading/lading.yaml, test/smp/regression/saluki/cases/uds_dogstatsd_to_api/lading/lading.yaml
This commit removes the emission of events and service-checks in the Regression Detector experiments. They're not appropriate for the targets.
=> Don't send events or service checks

Cargo.lock, Cargo.toml, LICENSE-3rdparty.csv, bin/agent-data-plane/src/main.rs, deny.toml, lib/saluki-components/Cargo.toml, lib/saluki-components/src/destinations/datadog_metrics/mod.rs, lib/saluki-components/src/sources/dogstatsd/mod.rs, lib/saluki-components/src/transforms/origin_enrichment/mod.rs, lib/saluki-config/src/lib.rs, lib/saluki-core/src/lib.rs, lib/saluki-core/src/topology/shutdown.rs, lib/saluki-env/src/workload/collectors/containerd.rs, lib/saluki-env/src/workload/collectors/mod.rs, lib/saluki-env/src/workload/metadata.rs, lib/saluki-io/Cargo.toml, lib/saluki-io/src/deser/mod.rs, lib/saluki-io/src/net/addr.rs, lib/saluki-io/src/net/listener.rs, lib/saluki-io/src/net/unix/linux.rs, lib/saluki-io/src/net/unix/mod.rs, lib/saluki-io/src/net/unix/non_linux.rs, license-tool.toml, test/k8s/datadog-agent-values.yaml
This PR is a simple refactoring of the existing components to pull their configuration directly where possible.
Currently, most settings are specified manually, either directly during struct initialization or via builder methods. For many of these settings, they're analogues to existing settings in the Datadog Agent configuration (`datadog.yaml`).
In this PR, we've adjusted components to pull these values directly from `GenericConfiguration`, using the equivalent setting names in `datadog.yaml`. Not all components have equivalent settings, so they've been left as-is with their builder methods, etc.
=> components: migrate all components to pull necessary configuration directly

Cargo.lock, bin/agent-data-plane/src/env_provider.rs, bin/agent-data-plane/src/main.rs, docker/Dockerfile.agent-data-plane, lib/saluki-components/src/sources/dogstatsd/mod.rs, lib/saluki-config/Cargo.toml, lib/saluki-config/src/lib.rs, lib/saluki-config/src/provider.rs, lib/saluki-env/src/host/providers/agent.rs, lib/saluki-env/src/workload/collectors/containerd.rs, lib/saluki-env/src/workload/collectors/remote_agent.rs, lib/saluki-env/src/workload/mod.rs, lib/saluki-env/src/workload/providers/remote_agent.rs, lib/saluki-io/src/deser/codec/dogstatsd.rs, lib/saluki-io/src/deser/framing/newline.rs, test/smp/regression/saluki/cases/uds_dogstatsd_to_api/experiment.yaml
Currently, SMP regression detector runs are failing because the ADP binary expects to be run alongside the Datadog Agent, necessary for providing the remote tagger API used to power `RemoteAgenteWorkloadProvider`.
In these runs, we have no need for the actual workload provider because there's no origin detection going on, or any origin detection we could do even if we wanted to.
We've adjusted `ADPEnvironmentProvider` to allow it to be configured to use a no-op workload provider, which is possible through a blanket implementation of `WorkloadProvider` for `T where T: WorkloadProvider`. We've added a new configuration setting -- `adp.use_noop_workload_provider` -- that when set to `true` simply uses `None` for the workload provider, which, well... makes it a no-op.
This is sufficient for …
=> adp: adjust environment provider to make SMP runs function

.gitignore, Makefile, docker/Dockerfile.proxy-dumper, lib/saluki-components/src/transforms/aggregate/mod.rs, lib/saluki-event/src/metric/context.rs, lib/saluki-event/src/metric/metadata.rs, lib/saluki-event/src/metric/mod.rs, lib/saluki-event/src/metric/value.rs, lib/saluki-io/src/deser/codec/dogstatsd.rs, test/k8s/datadog-agent-values.yaml, test/k8s/proxy-dumper.yaml, test/k8s/statsd-generator.yaml, tooling/dogstatsd_client/go.mod
In #26, we observed that we could often find ourselves emitting the same bucket twice -- between two flushes -- in what _appeared_ to be values being split: for N samples meant to be aggregated in a single bucket, the first flush might container 80% of them and the second flush the remaining 20%.
This is a bug because when sending to Datadog, it would result in a last-write-wins scenario where the aggregated series from the second bucket overwrites the aggregated series from the first bucket, since they have an identical timestamp and context (metric name + tags).
We've changed the flushing logic to adjust our check for detecting if a bucket is still open or not, and we've aligned the flush interval so that it occurs at the midpoint between the end of the current bucket and the next one. …
=> aggregate: avoid flushing directly at bucket end

lib/ddsketch-agent/src/lib.rs
Extracted from https://github.com/DataDog/saluki/pull/53. The [relevant light-usage allocation test](https://github.com/DataDog/saluki/pull/53/commits/edf630998544514190f530ccae1633e0690b5dfd#diff-6c4980dfe6c6ae88035251c46b710e5f3d53961c93b0360b3ac62b72584bd441) from that PR shows a nearly 16KB reduction in both peak and total allocations. The [heavy usage allocation test](https://github.com/DataDog/saluki/pull/53/commits/edf630998544514190f530ccae1633e0690b5dfd#diff-17c9e4c3cbdc030fa039f49d91cfeef44716bbae1c66a067b9fa571da6499b75) shows a 10KB reduction in peak allocations and a similar reduction in total allocations.
=> Preallocate the smaller of the initial bin count & the bin limit.

Cargo.lock, LICENSE-3rdparty.csv, lib/saluki-env/src/host/hostname/kubernetes.rs
In #56, we described an issue that occurs where the current method of instantiating a Kubernetes API client tries to read cluster endpoint/credential information from `kubeconfig` before trying to read in-cluster environment variables.
This poses a problem when testing locally, as it's incredibly common to have `kubectl` set up and configured, which means ADP will be trying to query a cluster that it isn't actually in... leading to confusion on why that traffic is happening (which is how this came up after a colleague pointed out the behavior) and also just being incorrect: we only want to query Kubernetes for hostname information if we're running _within_ Kubernetes.
This PR simply changes how we construct the API client to directly attempt loading the client configuration from the …
=> hostname: don't read Kubernetes API configuration from kubeconfig

Cargo.lock, Cargo.toml, lib/saluki-components/Cargo.toml, lib/saluki-components/src/sources/checks/aggregator.rs, lib/saluki-components/src/sources/checks/datadog_agent.rs, lib/saluki-components/src/sources/checks/mod.rs, lib/saluki-components/src/sources/checks/scheduler.rs, lib/saluki-event/src/metric/context.rs
Nearly have something which should do the link Python `submit_metric`  ->  saluki's event buffer
I did a few non-idiomatic/stupid things to move forward, feel free to just get inspiration/copy paste some code from the PR if you don't want to merge it:
* used a global queue (sigh) to transmit metrics resulting from the check execution into the saluki's SourceContext, I don't really know how this link, you or toby might know better
* used an intermediate CheckMetric struct
* most likely better to directly use saluki::Event but I was already to deep into it I didn't look into what existed just yet
* because of this I created an ugly fn event_from_check_metric and didn't even bother to impl TryFrom
* not fitting the serialiser/codec architecture of saluki
For some reasons the queue always …
=> Propagate metrics resulting from a check execution to the Event Buffer.

test/smp/regression/dogstatsd/cases/distribution_metrics/experiment.yaml, test/smp/regression/dogstatsd/cases/distribution_metrics/lading/lading.yaml, test/smp/regression/saluki/cases/distribution_metrics/experiment.yaml, test/smp/regression/saluki/cases/distribution_metrics/lading/lading.yaml
Add regression detector experiments that exclusively exercise dogstatsd distributions. This has historically been a performance pain point for the agent.
Extract from https://github.com/DataDog/saluki/pull/53.
=> Add SMP experiments that exercise distribution metrics

lib/ddsketch-agent/src/lib.rs
The DDSketch port here currently preallocates 128 bins for every sketch. I'd like to make the case that preallocating nothing is a preferable default. My assertion is that preallocating bins hurts memory-sensitive use cases and does not meaningfully benefit high-throughput use cases.
> Commentary: I _think_ this is reasonable, but truthfully this is all more handwavy than I'd like. At the end of the day, the per-distribution impact is minimal, and light users probably don't have enough of them in memory to make a notable difference. I'd be satisfied if we say this is simply not a big enough improvement to be worth considering.
---
First, a look at sketch breadth and capacity:
- The full capacity of 128 bins is 128 * 65535 = 8,388,480 counts.
- 128 bins can store a broad range of values. …
=> DDSketch: Reduce initial bin allocation from 128 to 0

Cargo.lock, Cargo.toml, lib/ddsketch-agent/Cargo.toml, lib/ddsketch-agent/benches/insert.rs, lib/ddsketch-agent/tests/common/mod.rs, lib/ddsketch-agent/tests/one_thousand_single_points_ddsketch.rs, lib/ddsketch-agent/tests/ten_batched_points_ddsketch.rs, lib/ddsketch-agent/tests/ten_single_points_ddsketch.rs
- Uses [dhat-rs](https://github.com/nnethercote/dhat-rs) to assert on the allocations performed during DDSketch operations.
Caveat:
> Warning: This crate is experimental. It relies on implementation techniques that are hard to keep working for 100% of configurations. It may work fine for you, or it may crash, hang, or otherwise do the wrong thing. Its maintenance is not a high priority of the author. Support requests such as issues and pull requests may receive slow responses, or no response at all. Sorry!
- Uses criterion to add microbenchmarks for sketch insert operations.
=> DDSketch: Add allocation tests & microbenchmarks

LICENSE-3rdparty.csv, license-tool.toml
The `crunchy` crate doesn't have a published version with the source repository listed, which we need for the dependency "origin" information in LICENSE-3rdparty.csv. This sets it manually in `license-tool.toml` to make everything happy again.
=> chore: properly set repository for `crunchy` dep to make license tool happy

lib/saluki-components/src/transforms/aggregate/mod.rs
Currently, we calculate the firm bound for the aggregate transform by using knowledge of the limits on tags -- both the number of tags and the tag length -- for metrics coming in over DogStatsD. That leads us to emit a total firm limit for the current ADP topology configuration that is just over 1GB in size.
In reality, we barely use a fraction of that even with antagonistic workloads. Why the discrepancy?
In practice, metrics coming in over DogStatsD are limited in size by the size of the buffer we read the data into. This follows the implementation on the Datadog Agent side, where metrics cannot be sent _across_ multiple packets. In this case, Saluki uses the term "buffer" and the Datadog Agent uses the term "packet", but the behavior is the same.
Since metrics are limited in their …
=> aggregate: improve firm bound by tying context size to DSD buffer size

lib/ddsketch-agent/src/lib.rs, lib/ddsketch-agent/tests/one_thousand_batched_points_ddsketch.rs, lib/ddsketch-agent/tests/one_thousand_single_points_ddsketch.rs, lib/ddsketch-agent/tests/ten_single_points_ddsketch.rs
Further speed up single-value insertion by adding an optimized slow path. Adds a bunch of insertion tests to make sure I got insertion and overflow right.
=> Add insertion tests and a faster single-value slow path

Cargo.lock, Cargo.toml, LICENSE-3rdparty.csv, deny.toml, lib/saluki-components/src/destinations/datadog_metrics/mod.rs, lib/saluki-components/src/destinations/datadog_metrics/request_builder.rs, lib/saluki-components/src/transforms/aggregate/mod.rs, lib/saluki-io/Cargo.toml, lib/saluki-io/src/buf/chunked.rs, lib/saluki-io/src/compression.rs
The Datadog API imposes specific payload size limits when submitting metrics, both in terms of the uncompressed _and_ compressed payload sizes. When building requests, tracking the uncompressed size is easy and can be done with 100% accuracy. Tracking the compressed size is harder, though.
While we are always able to accurate determine if the final compressed payload size is within the limit or not, we need a way to track the compressed size _during_ encoding in order to try and submit as many points per request as possible. This is difficult due to the fact that writing an encoded metric to the compressor doesn't always trigger a corresponding write from the compressor to the underlying buffer. Most compression algorithms with their own internal buffering for efficiency.
For the sake of …
=> datadog metrics/compression: add compression estimator to help avoid oversized compressed payloads

Cargo.lock, lib/saluki-components/src/sources/dogstatsd/mod.rs, lib/saluki-context/Cargo.toml, lib/saluki-context/src/lib.rs, lib/saluki-core/src/observability/metrics.rs, lib/saluki-metrics/src/macros.rs, lib/stringtheory/src/interning/fixed_size.rs
This PR adds some new metrics for `ContextResolver`, and indirectly, `FixedSizeInterner`, using the recently added `static_metrics!` helper macro from `saluki_metrics`3
We're now tracking the following things:
- `context_resolver_resolved_existing_context_total` (counter; resolutions where the context already existed)
- `context_resolver_resolved_new_context_total` (counter; resolutions where the context did not exist)
- `context_resolver_active_contexts` (gauge; number of active contexts)
- `context_resolver_interner_capacity_bytes` (gauge; total capacity, in bytes, of the string interner used for the resolver)i
- `context_resolver_interner_len_bytes` (gauge; current length, in bytes, of the string interner used for the resolver)
- `context_resolver_interner_entries` (gauge; current …
=> metrics: add metrics for context resolver/string interner

Cargo.lock, Cargo.toml, lib/saluki-components/src/transforms/aggregate/mod.rs, lib/saluki-context/Cargo.toml, lib/saluki-context/src/lib.rs, lib/saluki-metrics/Cargo.toml, lib/saluki-metrics/src/lib.rs, lib/saluki-metrics/src/macros.rs
Contexts represent the sum of both the name and tags of a metric, and are used to uniquely identify a metric. As such, contexts are touched often in the hot path of both parsing and aggregation.
Normally, as part of "resolving" a context (similar to string interning) or just looking them up in a map (such as during aggregation), the hash of the context is checked as a fast path, and if there are any collisions with existing items, the equality of those items is checked directly: this looks sort of like check that the name of each context is equal, and that the tags of each context are equal, which compares them _in order_.
This is slower than the hash checking (because comparing two integers is hard to beat) but also means that contexts may not present as equal if their tags are in …
=> context: switch to pure hash-based equality

lib/saluki-components/src/sources/dogstatsd/mod.rs
In some of the SMP benchmarks, I noticed that we're completely filling up the interner. It's not clear what the right default should really be, but this PR is an experiment to see what happens when double the interner size for the DogStatsD source.. mostly in terms of if there's any CPU or memory usage/memory stability improvements.
=> dogstatsd: try increasing interner size from 1MB to 2MB

.gitlab-ci.yml, .gitlab/benchmark.yml, .gitlab/test.yml, Cargo.lock, Cargo.toml, LICENSE-3rdparty.csv, bin/agent-data-plane/src/main.rs, lib/memory-accounting/Cargo.toml, lib/memory-accounting/src/lib.rs, lib/memory-accounting/src/limiter.rs, lib/saluki-app/src/memory.rs, lib/saluki-components/src/sources/dogstatsd/mod.rs, lib/saluki-core/src/components/destinations/context.rs, lib/saluki-core/src/components/sources/context.rs, lib/saluki-core/src/components/transforms/context.rs, lib/saluki-core/src/topology/built.rs, test/smp/regression/saluki/cases/distribution_metrics/experiment.yaml, test/smp/regression/saluki/cases/distribution_metrics/lading/lading.yaml, test/smp/regression/saluki/cases/uds_dogstatsd_to_api_100mb/experiment.yaml, test/smp/regression/saluki/cases/uds_dogstatsd_to_api_100mb/lading/lading.yaml, test/smp/regression/saluki/cases/uds_dogstatsd_to_api_100mb_antagonistic/experiment.yaml, test/smp/regression/saluki/cases/uds_dogstatsd_to_api_100mb_antagonistic/lading/lading.yaml, test/smp/regression/saluki/cases/uds_dogstatsd_to_api_10mb/experiment.yaml, test/smp/regression/saluki/cases/uds_dogstatsd_to_api_10mb/lading/lading.yaml, test/smp/regression/saluki/cases/uds_dogstatsd_to_api_1mb/experiment.yaml, test/smp/regression/saluki/cases/uds_dogstatsd_to_api_1mb/lading/lading.yaml
This PR introduces the concept of a global memory limiter, used to cooperatively slow down components/tasks that are contributing to memory allocations that ultimately lead the process towards, or even past, the configured memory limit.
`MemoryLimiter` is based on a simple design:
- start off with a target RSS limit
- periodically check the RSS of the process
- once actual RSS exceeds the threshold of the target RSS limit, apply backpressure
- backpressure is increased progressively the closer we get to the target RSS limit
After testing with a model that simply blocked until the actual RSS was below the target RSS limit, it was observed that this can be difficult to cope with as it requires memory to be getting freed in near-real-time. In some cases, there might be things expiring and …
=> memory-accounting: global memory limiter

bin/agent-data-plane/src/main.rs, lib/saluki-components/src/transforms/aggregate/mod.rs
In the Datadog Agent, counters are kept alive (in terms of being continuously emitted every time the aggregator flushes) even when no updates to them have come in during the previous aggregation window. This ensures that counters which are sparse (updated infrequently) continue to be emitted, thus providing continuity when graphed.
Counters in this state have a synthetic "zero value" sample injected into the aggregator, and they are tracked in terms of the last seen _true_ update. Every flush, this synthetic sample is injected, and once a counter reaches expiry, it is dropped and no longer have synthetic samples injected.
Saluki currently does _not_ do this, which means not only do counters lack continuity when they are sparse, but we're not properly mimicing the same memory usage (since …
=> aggregate: keep counters alive until expiry

Cargo.lock, lib/saluki-components/src/sources/dogstatsd/mod.rs, lib/saluki-components/src/transforms/aggregate/mod.rs, lib/saluki-context/src/lib.rs, lib/saluki-core/src/observability/metrics.rs, lib/saluki-io/Cargo.toml, lib/saluki-io/src/deser/codec/dogstatsd.rs, lib/saluki-io/src/deser/framing/length_delimited.rs, lib/saluki-io/src/deser/framing/mod.rs, lib/saluki-io/src/deser/framing/newline.rs, test/smp/regression/saluki/cases/uds_dogstatsd_to_api_10mb_no_inlining/experiment.yaml, test/smp/regression/saluki/cases/uds_dogstatsd_to_api_10mb_no_inlining/lading/lading.yaml
Currently, context resolving will handle the interning of strings (metric name and tags) in the following way:
- try and inline them (31 bytes or less)
- try and intern them (interner has to have capacity to do so)
- allocate them on the heap (via `Arc<T>`, so chance for reusability.. but a heap allocation nonetheless)
Naturally, this means contexts are unbounded. We'd like a way to be able to bound them.
This PR adds the ability to configure `ContextResolver` to not fallback to doing a heap allocation, and instead, simply treat resolving as a fallible operation. This is configured through `ContextResolver::allow_heap_allocations` and we've threaded that all the way up through to the DogStatsD source. We've allowed heap allocations by default, for now.
We've added a new experiment that …
=> dogstatsd/context: add ability to stop all heap allocations during context resolving

test/smp/regression/dogstatsd/cases/uds_dogstatsd_to_api_100mb/lading/lading.yaml, test/smp/regression/dogstatsd/cases/uds_dogstatsd_to_api_100mb_antagonistic/lading/lading.yaml, test/smp/regression/dogstatsd/cases/uds_dogstatsd_to_api_10mb/lading/lading.yaml, test/smp/regression/dogstatsd/cases/uds_dogstatsd_to_api_1mb/lading/lading.yaml, test/smp/regression/dogstatsd/cases/uds_dogstatsd_to_api_512kb/experiment.yaml, test/smp/regression/dogstatsd/cases/uds_dogstatsd_to_api_512kb/lading/lading.yaml, test/smp/regression/saluki/cases/uds_dogstatsd_to_api_100mb/lading/lading.yaml, test/smp/regression/saluki/cases/uds_dogstatsd_to_api_100mb_antagonistic/lading/lading.yaml, test/smp/regression/saluki/cases/uds_dogstatsd_to_api_10mb/lading/lading.yaml, test/smp/regression/saluki/cases/uds_dogstatsd_to_api_10mb_no_inlining_allocs_off/lading/lading.yaml, test/smp/regression/saluki/cases/uds_dogstatsd_to_api_512kb/experiment.yaml, test/smp/regression/saluki/cases/uds_dogstatsd_to_api_512kb/lading/lading.yaml
Originally, the Lading generator configurations were added with only counters/gauges while we were still sorting out full DogStatsD codec support. This is outdated since we've had full support for all metric types for a while now.
This PR adjusts the weights so that we should be sending a proper blend of different metric types in all experiments (except for `distribution_metrics`, which is explicitly distributions only). These new values are also based on empirical measurements from internal DD usage.
=> smp: adjust lading metric type blend to reflect internal metric type usage data

.gitignore, Cargo.lock, LICENSE-3rdparty.csv, Makefile, lib/saluki-components/src/transforms/aggregate/mod.rs, lib/saluki-context/src/lib.rs, lib/saluki-io/Cargo.toml, lib/saluki-io/src/deser/codec/dogstatsd.rs, lib/stringtheory/src/interning/fixed_size.rs, test/smp/regression/dogstatsd/cases/uds_dogstatsd_to_api_500mb/experiment.yaml, test/smp/regression/dogstatsd/cases/uds_dogstatsd_to_api_500mb/lading/lading.yaml, test/smp/regression/saluki/cases/uds_dogstatsd_to_api_100mb/experiment.yaml, test/smp/regression/saluki/cases/uds_dogstatsd_to_api_10mb/experiment.yaml, test/smp/regression/saluki/cases/uds_dogstatsd_to_api_10mb_no_inlining/experiment.yaml, test/smp/regression/saluki/cases/uds_dogstatsd_to_api_10mb_no_inlining_allocs_off/experiment.yaml, test/smp/regression/saluki/cases/uds_dogstatsd_to_api_1mb/experiment.yaml, test/smp/regression/saluki/cases/uds_dogstatsd_to_api_500mb/experiment.yaml, test/smp/regression/saluki/cases/uds_dogstatsd_to_api_500mb/lading/lading.yaml, test/smp/regression/saluki/cases/uds_dogstatsd_to_api_512kb/experiment.yaml
This is an attempt to see if we can improve CPU usage by just going with a sharded approach to the interner. The hope is that by reducing the number of entries in each interner, we can drastically cut down on the time spent iterating over existing entries during `try_intern`.
=> context: sharded interner

Cargo.lock, Cargo.toml, lib/saluki-components/Cargo.toml, lib/saluki-components/src/destinations/datadog_metrics/mod.rs, lib/saluki-components/src/destinations/datadog_metrics/request_builder.rs, lib/saluki-components/src/sources/dogstatsd/mod.rs, lib/saluki-components/src/transforms/aggregate/mod.rs, lib/saluki-components/src/transforms/host_enrichment/mod.rs, lib/saluki-context/src/lib.rs, lib/saluki-core/Cargo.toml, lib/saluki-core/src/components/mod.rs, lib/saluki-core/src/observability/metrics.rs, lib/saluki-core/src/topology/built.rs, lib/saluki-core/src/topology/ids.rs, lib/saluki-core/src/topology/interconnect/event_buffer.rs, lib/saluki-core/src/topology/interconnect/event_stream.rs, lib/saluki-core/src/topology/interconnect/forwarder.rs, lib/saluki-event/src/metric/metadata.rs, lib/saluki-io/Cargo.toml, lib/saluki-io/src/deser/codec/dogstatsd.rs, lib/saluki-io/src/deser/codec/mod.rs, lib/stringtheory/src/lib.rs
This PR primarily adds support for "no aggregation" pipelines. This is where metrics specify a timestamp directly (such as using DogStatsD's extension to allow specify the Unix timestamp for the metric) and, in turn, the `aggregate` transform forwards those metrics on without aggregating them.
This required changes to the DSD codec to avoid setting a timestamp if one was not specified, as well as threading through some configuration to allow for the fast-laning of metrics with timestamps, and so on.
That's the bulk of this PR, and I took the liberty of doing some ergonomic improvements like more fleshed out getters/setters for `MetricMetadata`, and so on.
Listed in no particular order:
- tracing spans around each component parent task for better logs
- renamed a builder-style setter in …
=> dogstatsd/aggregate: add support for no aggregation mode + a lot of cleanup/bugfixes

Cargo.lock, lib/ddsketch-agent/Cargo.toml, lib/ddsketch-agent/build.rs, lib/ddsketch-agent/src/lib.rs, lib/ddsketch-agent/tests/one_thousand_batched_points_ddsketch.rs, lib/ddsketch-agent/tests/one_thousand_single_points_ddsketch.rs, lib/ddsketch-agent/tests/ten_batched_points_ddsketch.rs, lib/ddsketch-agent/tests/ten_single_points_ddsketch.rs
Currently, `DDSketch` is a decently large struct owing to the fact that we include a number of configuration parameters in the struct that are effectively static. Additionally, creating a `DDSketch` when handling timer/histogram/distribution metrics in DogStatsD leads to having to allocate a backing vector for the bins, even when there's only a single value present, which is fairly common.
We've taken a two-pronged approach to this:
- switch to `SmallVec<T>` to allow for a small number of inline bins to avoid allocations entirely for single-sample use cases
- move the configuration parameters out of `DDSketch` and reference them from a global static
We've done some work to push generating the configuration parameters into a build-time script, as there's not enough support for doing so …
=> ddsketch-agent: shrink the size of `DDSketch` struct

lib/saluki-components/src/destinations/datadog_metrics/mod.rs, lib/saluki-components/src/destinations/datadog_metrics/request_builder.rs, lib/saluki-core/src/pooling/fixed.rs, lib/saluki-core/src/pooling/helpers.rs, lib/saluki-core/src/pooling/mod.rs, lib/saluki-io/src/buf/chunked.rs, lib/saluki-io/src/buf/mod.rs, lib/saluki-io/src/net/client/http.rs
`ObjectPool` provides a generalized trait for working with object pool implementations. It utilizes `async-trait` to make it possible to define `async fn`s in the trait (and other related pooling traits) in a object safe way, which involves returned a boxed future.
As we call `ObjectPool::acquire` often -- in the case on the DogStatsD source, one per receive loop -- we're very often paying the cost of boxing the future and going through that layer of indirection.
We've removed the use of `async-trait` from `ObjectPool` and the associated traits, and instead taken the more direct approach of returning a `Future` based on an associated type within the trait. We've also refactored `Strategy` to `ReclaimStrategy`, and removed the trait function related to acquiring, as we only need the …
=> core: drop async trait usage for `ObjectPool`

lib/saluki-context/src/lib.rs, lib/saluki-core/src/topology/interconnect/event_buffer.rs, lib/saluki-io/src/deser/codec/dogstatsd.rs
The DogStatsD codec generally avoids allocating as much as reasonably possible, but in the case of tags and multi-value payloads, a vector must be allocated to hold string references or decoded values in order to then further process the payload and eventually generate `Event`s. Additionally, for multi-value payloads, a vector is allocated to hold the `Event`s before being pushed into `EventBuffer`.
While the size of the vectors might generally be small -- only a few hundred bytes -- it still represents unnecessary allocations per metric payload.
We've reworked the DSD codec to use dedicated iterators -- one for tags, and one for values -- that can iterate over the raw bytes and extract individual tags/values. These are then used to incrementally build the context, and each `Event` that a …
=> codec/dogstatsd: change decoder to be zero-copy

Cargo.lock, bin/agent-data-plane/src/main.rs, lib/memory-accounting/Cargo.toml, lib/memory-accounting/src/allocator.rs, lib/memory-accounting/src/lib.rs, lib/saluki-app/src/memory.rs, lib/saluki-components/src/destinations/datadog_metrics/mod.rs, lib/saluki-components/src/sources/dogstatsd/mod.rs, lib/saluki-core/src/lib.rs, lib/saluki-core/src/topology/blueprint.rs, lib/saluki-core/src/topology/built.rs, lib/saluki-io/Cargo.toml, lib/saluki-io/src/net/server/http.rs
This PR adds support for tracking the heap usage of different "components" by using a custom allocator that can instrument allocations such that their allocations/deallocations are attributable back to the originating "component".
First, we've created a custom allocator -- `TrackingAllocator` -- that gets set as the global allocator and handles forwarding (de)allocation requests to an underlying allocator: in our case, the normal system allocator.
This allocator will create slightly-bigger-than-request allocations and store a pointer to a statistics structure for the "component" that owns the allocation. This statistics structure tracks the number of bytes, and the number of objects, that are allocated  by the component. Likewise, when these allocations are then deallocated, we update the …
=> memory-accounting: add a tracking allocator implementation for attributing heap usage to specific components

lib/saluki-context/src/lib.rs
Currently, contexts are effectively immutable because we initially wanted to focus on making them able to be cached and "resolvable" (looked up with a borrowed version of the name/tags) without needing any allocations. Doing so involves caching their hashed value, which meant avoiding mutating the name/tags to avoid messing with the hash value and breaking how they were stored (which is in a hashset).
This PR adds back the ability to mutate tags. When acquiring a mutable reference to the tags on a context, we do a clone-on-write approach with the inner state, which clones it if there's another reference to the inner state. As such, this creates a new context which can then be modified as much as possible without further cloning, since it's now owned independently of the original context. …
=> Allow mutating of tags on contexts.

Cargo.lock, lib/saluki-components/src/transforms/origin_enrichment/mod.rs, lib/saluki-context/src/lib.rs, lib/saluki-env/Cargo.toml, lib/saluki-env/src/workload/collectors/containerd.rs, lib/saluki-env/src/workload/collectors/remote_agent.rs, lib/saluki-env/src/workload/entity.rs, lib/saluki-env/src/workload/store.rs, lib/saluki-event/src/metric/metadata.rs, lib/stringtheory/src/lib.rs
Prior to #121, we had to disable origin enrichment as our work to improve context resolving left us with immutable tags, and so there was no way to actually enrich tags.
With #121 merged, we can now reenable origin enrichment. This did involve some changes beyond uncomment the code, namely around refactoring to handle the use of `MetaString` and changes to struct accessors, but otherwise is pretty strightforward.
=> Reintroduce origin-based enrichment of metrics.

lib/saluki-io/src/deser/codec/dogstatsd.rs
A lot of code exists at the moment surrounding context resolving and the sharing of tags, including code to then try and allow us to _modify_ tags in resolved contexts and minimize how much we have to clone/allocate, and so on and so forth.
The extent to which we work around this is due entirely to the need to modify tags after decoding. While we certainly aspire to allow for such free-form transformation of metrics, the current need to do so stems from origin enrichment, where we extract relevant tags that may or may not be present and use them to augment the metric metadata.
We consciously chose to do this in order to attempt to get the DogStatsD codec somewhat decoupled from being a one-to-one rewrite of the equivalent code in the Agent. In essence, though, our lives would be simpler …
=> [APR-205] dogstatsd: add support for a configurable tag interceptor for filtering/augmenting metadata via tags

lib/saluki-components/src/sources/dogstatsd/framer.rs, lib/saluki-components/src/sources/dogstatsd/interceptor.rs, lib/saluki-components/src/sources/dogstatsd/mod.rs, lib/saluki-components/src/transforms/origin_enrichment/mod.rs, lib/saluki-context/src/lib.rs, lib/saluki-env/src/workload/entity.rs, lib/saluki-event/src/metric/metadata.rs, lib/saluki-io/src/deser/codec/dogstatsd.rs, lib/saluki-io/src/deser/codec/mod.rs, test/smp/regression/saluki/cases/dsd_uds_100mb_250k_contexts/experiment.yaml
As a follow-on to #132, we need to actually switch to using the tag interceptor mechanism to intercept relevant tags and update the metric metadata.
This PR introduces a new interceptor implementation, `AgentLikeTagMetadataInterceptor`, which specifically focuses on `dd.internal.entity_id`, `dd.internal.jmx_check_name`, and `dd.internal.card`. With this, we're able to skip having to _remove_ any tags from metrics in the `origin_enrichment` transform.
We've gone through and tweaked `OriginEntity` from an enum into a struct that can hold all of the relevant entity ID information, similar to `OriginInfo` in the Agent codebase. This is somewhat suboptimal, but it allows us to track the Agent logic better by being able to incrementally enrich and not having to bake in a bunch of …
=> [APR-205] dogstatsd: switch to using tag interceptor for origin entity support

lib/saluki-components/src/destinations/datadog_metrics/request_builder.rs, lib/saluki-event/src/metric/metadata.rs, lib/stringtheory/src/lib.rs
In #133, we ended up increasing the size of `MetricMetadata` by a significant amount due to tracking three potential entity IDs instead of just the latest/highest priority one we had decoded so far.
While a long-term solution would ideally center on going back to using the highest priority entity ID found, for now we need to deal with the status quo... and so we've shrunk the size of the `MetricMetadata` struct to try and get back some of the memory efficiency we've lost by doing so.
We attacked this in two ways: shrink` `MetricMetadata` itself, and shrinking `MetaString`.
We had some non-optimal field sizes for optional things like sample rate and timestamp. Rather than have them be optional, we've just switched to giving them specific default values. Sample rate always defaults to 1.0 …
=> [APR-205] stringtheory/event: shrink MetaString and MetricMetadata struct sizes

lib/saluki-event/src/metric/value.rs, lib/saluki-io/src/deser/codec/dogstatsd/mod.rs
Currently, when decoding multi-value metric payloads, we use an approach that wraps an iterator over the raw values, and then for each value returned from the iterator, we create the corresponding metric.
However, this is suboptimal for distributions because we can add multiple values to a distribution, which is in fact all that will end up happening when these metrics are aggregated.
We've updated `ValueIter<'a>` to take this optimized approach when dealing with distributions, instead just building one sketch, adding all of the values it pulls out of the value iterator (well, a new value iterator just for floats, `FloatIter<'a>`), and then returning a single distribution metric.
=> [APR-205] dogstatsd: optimize multi-value distribution decoding

Cargo.lock, Cargo.toml, bin/agent-data-plane/src/main.rs, lib/saluki-app/Cargo.toml, lib/saluki-app/src/lib.rs, lib/saluki-app/src/tls.rs, lib/saluki-components/Cargo.toml, lib/saluki-env/Cargo.toml, lib/saluki-io/Cargo.toml
Currently, Saluki exclusively uses `rustls` as its TLS crate, primarily due to it being a Rust-based TLS solution that avoids depending on shared libraries, such as OpenSSL. Additionally, it has support for AWS-LC, which is a FIPS validated cryptography module that it can use as its "crypto provider", giving us a pathway to easy FIPS-compliant builds.
However, `rustls` also supports the `ring` crate as a provider. Normally, applications enable one feature or the other and things Just Work (tm), but in the case when both providers are enabled, additional code is needed to tell `rustls` which provider to use by default.
Another dependency -- `kube` -- transitively depends on `rustls` but explicitly enables the `ring` feature, which breaks things in ADP when trying to use `rustls`.
We've …
=> [APR-205] app: ensure TLS subsystem initialization

lib/saluki-core/src/topology/interconnect/event_buffer.rs, lib/saluki-event/src/lib.rs
This PR updates `EventBuffer` to track the data types it has seen for events currently in the buffer. As `DataType` is already a bitfield, we simply OR the data type of an event being added (whether through `EventBuffer::push` or `Extend`) to a new field, `seen_data_types`, and expose a new method -- `EventBuffer::has_data_type` -- that checks if a given data type is contained in `seen_data_types`. Care is taken to ensure that `seen_data_types` is reset when the buffer is cleared.
This allows code which intermingles multiple data types in a single `EventBuffer` to efficiently know if there's a need to filter out/split the buffer into multiple buffers, such as when the buffer must have a homogenous event type, without having to first iterate over it.
=> [APR-205] core: track seen data types in event buffers

ARCHITECTURE.md, lib/memory-accounting/src/lib.rs
The PR title kind of says it all.
We're adding a project-level architecture document, and beefing up the module-level docs for `memory-accounting`.
=> chore: start adding more architecture docs, and docs in general

Cargo.lock, bin/agent-data-plane/src/main.rs, lib/saluki-components/Cargo.toml, lib/saluki-components/src/destinations/datadog_events_service_checks/mod.rs, lib/saluki-components/src/destinations/datadog_events_service_checks/request_builder.rs, lib/saluki-components/src/destinations/mod.rs, lib/saluki-components/src/sources/dogstatsd/mod.rs, lib/saluki-event/Cargo.toml, lib/saluki-event/src/eventd/mod.rs, lib/saluki-event/src/service_check/mod.rs, lib/saluki-io/src/deser/codec/dogstatsd/message.rs, lib/saluki-io/src/deser/codec/dogstatsd/mod.rs
In order to support sending events and service checks to Datadog, we need a new destination to send them to.
We create a new destination in `saluki-components/src/destinations/datadog_events_service_checks` that supports both events and service checks.
Submit events and service checks. You should now see them show up on the Datadog platform.
Finishes #120
=> [APR-230] Add a new destination to support sending events/service checks to the Datadog platform

Cargo.lock, lib/saluki-components/src/destinations/datadog_events_service_checks/mod.rs, lib/saluki-components/src/destinations/datadog_events_service_checks/request_builder.rs, lib/saluki-event/src/eventd/mod.rs, lib/saluki-event/src/service_check/mod.rs, lib/saluki-io/Cargo.toml, lib/saluki-io/src/deser/codec/dogstatsd/mod.rs, lib/stringtheory/Cargo.toml, lib/stringtheory/src/lib.rs
This simply addresses some TODOs around switching from `String` to `MetaString` for events and service checks. We don't do anything here to actually intern those strings, since doing that is a more involved changed.
=> chore: switch to MetaString for events/service checks

lib/saluki-components/src/destinations/datadog_events_service_checks/mod.rs, lib/saluki-components/src/destinations/datadog_events_service_checks/request_builder.rs, lib/saluki-io/src/compression.rs
This PR addresses #158 by slightly adjusting our threshold from 99.5% of the target payload size limit to 99%. For the purposes of the Datadog Metrics destination, this is about 2.5KiB smaller (0.995 * 512kB = 509,440 bytes vs 0.99 * 512kB = 506,880 bytes) which is larger, empirically, than the overruns we generally see, which are generally only a few hundred bytes.
Fixes #158.
=> chore: adjust red zone threshold for compression estimator to be more conservative

Cargo.lock, bin/agent-data-plane/src/main.rs, clippy.toml, lib/memory-accounting/src/registry.rs, lib/saluki-components/src/destinations/blackhole/mod.rs, lib/saluki-components/src/destinations/datadog_events_service_checks/mod.rs, lib/saluki-components/src/destinations/datadog_metrics/mod.rs, lib/saluki-components/src/destinations/prometheus/mod.rs, lib/saluki-components/src/sources/dogstatsd/mod.rs, lib/saluki-components/src/sources/internal_metrics/mod.rs, lib/saluki-components/src/transforms/aggregate/mod.rs, lib/saluki-components/src/transforms/chained/mod.rs, lib/saluki-core/Cargo.toml, lib/saluki-core/src/components/destinations/context.rs, lib/saluki-core/src/components/sources/context.rs, lib/saluki-core/src/components/transforms/context.rs, lib/saluki-core/src/topology/built.rs, lib/saluki-env/src/workload/providers/remote_agent.rs, lib/saluki-health/Cargo.toml, lib/saluki-health/src/api.rs, lib/saluki-health/src/lib.rs
This PR addresses #192 by wiring up the topology building code, and all current components, into the health registry.
Most code changes not in `saluki-health` were purely boilerplate wiring. The glut of changes are, however, in `saluki-health`: I spent a good amount of time trying to clean up and simplify the code, including making it easier to pass around `HealthRegistry` in the same way that `memory_accounting::ComponentRegistry` can be passed around. I didn't quite go as far as `ComponentRegistry` goes, but it's good enough for now.
Practically speaking, this means you can do `curl http://localhost:5400/health/live` after building/running ADP and get back this:
```json
{"topology.destinations.dd_metrics_out":{"ready":true,"live":true},"topology.transforms.dsd_agg":{"ready":true,"live":t …
```
=> chore: integrate health registry into topology

.ci/images/build/Dockerfile, .gitlab-ci.yml, .gitlab/internal.yml, Cargo.lock, Cargo.toml, LICENSE-3rdparty.csv, Makefile, docker/Dockerfile.agent-data-plane, lib/saluki-app/Cargo.toml, lib/saluki-app/src/tls.rs, lib/saluki-io/Cargo.toml, lib/saluki-io/src/net/client/http.rs, lib/saluki-tls/Cargo.toml, lib/saluki-tls/src/lib.rs
In #196, we detailed how some of the configuration defaults for TLS can be suboptimal in terms of memory usage. This manifested itself as not only inefficient memory usage (duplication) but also misattributed memory usage, leading to certain components having to bear the usage burden because they happened to be spawned in a specific order that led to them being the first to initialize an HTTP client, and so on.
This PR introduces a small overhaul of how we centralize both TLS initialization as well as configuration.  We're doing a few things here:
- new crate, `saluki-tls`, where all of this stuff now lives and can be depended on from various crates (`saluki-app`, `saluki-io`, etc)
- tailored methods for all process-wide initialization (cryptography provider and native certificate store …
=> [APR-205] chore: consolidate TLS config generation and initialization

.gitlab-ci.yml, .gitlab/build.yml, Cargo.toml, docker/Dockerfile.agent-data-plane, docker/Dockerfile.datadog-agent
This PR is a simple addition of CI bits to enable us to start building a "converged" Datadog Agent image that utilizes our internal Datadog Agent image and plops ADP on top. This is the bare minimum necessary change to give us something we can deploy internally, and specifically eschews any of the necessary init system tweaks needed to integrate with `s6` for running the Datadog Agent image standalone in Docker.
=> [APR-207] chore: add basis for building converged Datadog Agent image in CI

lib/saluki-components/src/transforms/aggregate/mod.rs
I screwed up when I made the default aggregation window be 10 seconds. It's 15 seconds in the Datadog Agent.
That's it. That's the PR.
=> fix: change default aggregation window from 10 seconds to 15 seconds

lib/saluki-env/Cargo.toml, lib/saluki-env/src/workload/collectors/mod.rs, lib/saluki-env/src/workload/helpers/mod.rs, lib/saluki-env/src/workload/providers/remote_agent.rs
In #208, we added a bunch of code that is only relevant on Linux platforms. Some of that code was properly gated to only be used on Linux, but the areas where we initially imported the code/dependencies was not gated. This led to compilation issues on non-Linux platforms, like macOS.
This PR simply gates the relevant code and dependencies to only be included on Linux.
=> fix: try scoping cgroups v2 collector to only build on linux

lib/saluki-io/src/net/client/http.rs
When building an HTTP client, we should be able to configure the maximum idle connection age before the connection is terminated. Open connections consume resources on the downstream target systems, and we should prefer to be sparing with how long we try to hold on to reusable resources before we declare the efficiency gains we stand to make not worth the imposition on the downstream target systems themselves.
Use [Builder::pool_max_idle_per_host](https://docs.rs/hyper-util/latest/hyper_util/client/legacy/struct.Builder.html#method.pool_max_idle_per_host)
The value is hardcoded in the [datadog agent](https://github.com/DataDog/datadog-agent/blob/0501086088f6615845ad1d052729cc6d27a23e56/pkg/util/http/transport.go#L116).
=> [APR-239] Add support for configuring the maximum idle connection pool size for HTTP clients.

lib/saluki-io/src/net/client/http.rs
When building an HTTP client, we should be able to configure a timeout specifically for connecting to the downstream target system. This is a simple assurance against extended delays trying to connect to unresponsive systems.
Use [HttpConnector::set_connect_timeout](https://docs.rs/hyper-util/0.1.2/hyper_util/client/legacy/connect/struct.HttpConnector.html#method.set_connect_timeout)
One caveat is that set_connect_timeout carries the following note:
> If a domain resolves to multiple IP addresses, the timeout will be evenly divided across them.
The datadog-agent uses the `Dialer.Timeout` field  to [set the timeout](https://github.com/DataDog/datadog-agent/blob/main/pkg/util/http/transport.go#L110-L111) with a value of `30` which [may also be divided …
=> [APR-241] Allow configuring the connection timeout for HTTP clients.

lib/saluki-io/src/net/client/http.rs
When building an HTTP client, we should be able to configure the maximum idle connection age before the connection is terminated. Open connections consume resources on the downstream target systems, and we should prefer to be sparing with how long we try to hold on to reusable resources before we declare the efficiency gains we stand to make not worth the imposition on the downstream target systems themselves.
Use [Builder::pool_idle_timeout](https://docs.rs/hyper-util/latest/hyper_util/client/legacy/struct.Builder.html#method.pool_idle_timeout)
Value hard coded to `45s` in [datadog-agent](https://github.com/DataDog/datadog-agent/blob/main/pkg/util/http/transport.go#L119)
=> [APR-240] Add support for configuring the idle connection timeout for HTTP clients.

lib/saluki-components/src/transforms/aggregate/mod.rs, lib/saluki-event/src/metric/value.rs
In #210, we attempted to "fix" our observed issues with the amount of output data from ADP not matching DSD by changing the bucket width (window duration) from 10 seconds to 15 seconds. This _did_ fix the output data discrepancy, but still wasn't actually correct.
In the Datadog Agent, the bucket width is in fact 10 seconds, while the _flush interval_ is 15 seconds.
This PR introduces a standalone setting for flush interval -- defaulting to 15 seconds -- to bring this up to snuff. We had to rework a bit of the flush logic to properly account for zero-value counters when we may be flushing multiple buckets, but overall things are a bit simpler (I think, at least) and hopefully easier to understand.
There's still some temporary data structures we use to track our progress and so on, and …
=> [APR-208] fix: properly separate bucket width from flush interval in aggregate transform

bin/agent-data-plane/src/main.rs, lib/saluki-health/src/api.rs
This PR is a simple update to align both the port and readiness/liveness endpoints with the Datadog Agent. This is simply to remove additional, and unnecessary differences between the core Agent and ADP.
=> fix: align the admin API port and healthcheck paths with the Datadog Agent

.gitlab/benchmark.yml, docker/Dockerfile.agent-data-plane, lib/saluki-components/src/sources/dogstatsd/framer.rs, lib/saluki-components/src/sources/dogstatsd/mod.rs, lib/saluki-io/src/buf/mod.rs, lib/saluki-io/src/deser/framing/length_delimited.rs, lib/saluki-io/src/deser/framing/mod.rs, lib/saluki-io/src/deser/framing/newline.rs
In the DogStatsD source, we have to potentially handle two types of framing: newline-delimited (UDP and UDS in `SOCK_DGRAM` mode) and length-delimited (UDS in `SOCK_STREAM` mode).
During recent testing, we discovered our handling of UDS in `SOCK_STREAM` mode was broken, and that length-delimited payloads actually still end up being newline-delimited inside, like so:
`15\0\0\0my.counter:1|c\n`
This is a payload with a length of 15 (32-bit, little-endian), representing a 15 byte "inner" payload: 14 bytes for the metric itself, and 1 byte for the newline delimiter.
This PR slightly reworks the `Framer` trait and adds some helpers that ultimately are designed to allow us to more easily combine framers to handle these "nested" framing schemes.
We now work with `Bytes` instead of `&'a [u8]` as …
=> [APR-208] fix: properly handle nested framing in DSD payloads

Cargo.lock, LICENSE-3rdparty.csv, lib/saluki-app/Cargo.toml, lib/saluki-app/src/logging.rs
This PR adds support for logging entirely in JSON by setting a new environment variable, `DD_LOG_FORMAT`, to a value of `json` (case insensitive).
We're adding this because JSON-formatted logs are vastly easier to ingest and parse compared to the human-friendly colored logs, while avoiding giving up the human-friendly logs completely, since they're good for testing.
=> [APR-207] enhancement: add support for writing logs as JSON

Cargo.lock, bin/agent-data-plane/src/main.rs, lib/saluki-config/Cargo.toml, lib/saluki-config/src/lib.rs, lib/saluki-config/src/secrets.rs
The Datadog Agent provides support for secrets management through an approach called the "secrets backend". This is an executable that uses a lightweight JSON-based protocol to receive requests for secrets to resolve (a list of opaque keys) and is expected to return back the resolved secrets, all operating over standard in/out.
This is the primary way by which to use external secrets management systems, such as Vault, as a secrets backend for the Datadog Agent.
This PR adds a barebones implementation of secrets backend support, matching that of the Datadog Agent. We've eschewed some specific things here:
- we don't do any of the same ownership/permissions checks on the backend command that is passed in
- we only support specifying the command to run and the timeout
- we don't support …
=> [APR-207] chore: add support for resolving config secrets

.cargo/config.toml, lib/saluki-app/src/metrics.rs
Currently, we have no way to understand the performance of the Tokio runtime itself, which can be a hamper to debugging and understanding performance issues.
This PR introduces a change to scrape and expose all of the Tokio runtime metrics under a `runtime` prefix. As most of the metrics are gated behind an unstable cfg flag (`tokio_unstable`), we've also added a project-level Cargo configuration to ensure that flag is always set.
We don't currently enable/expose the poll time histograms, however, as this requires building the runtime manually in order to enable them, and more investigation is needed to determine if they're collected in an absolute or incremental fashion, as we would need to do much more work in order to emit incremental distributions if they were in fact absolute.
Closes …
=> [APR-207] chore: add tokio runtime metrics to internal telemetry

Cargo.lock, bin/agent-data-plane/Cargo.toml, bin/agent-data-plane/src/components/mod.rs, bin/agent-data-plane/src/components/remapper.rs, bin/agent-data-plane/src/main.rs, lib/saluki-components/src/destinations/datadog_metrics/mod.rs, lib/saluki-components/src/sources/dogstatsd/mod.rs, lib/saluki-components/src/transforms/aggregate/mod.rs, lib/saluki-context/src/lib.rs, lib/saluki-core/Cargo.toml, lib/saluki-core/src/pooling/fixed.rs, lib/saluki-core/src/pooling/mod.rs, lib/saluki-core/src/topology/built.rs, lib/saluki-core/src/topology/interconnect/forwarder.rs, lib/saluki-event/src/lib.rs, lib/saluki-io/src/buf/chunked.rs, lib/saluki-io/src/buf/mod.rs, lib/saluki-io/src/deser/codec/dogstatsd/mod.rs, lib/stringtheory/src/lib.rs
In #118, we talked about the disconnect between the internal telemetry emitted by the Datadog Agent and Agent Data Plane. This gap makes it harder to test Agent Data Plane as a replacement for the DogStatsD portion of the core Agent as it requires focusing in to new telemetry and eschewing existing dashboards and monitors, which is not great.
This PR takes a simple approach of adding a new ADP-specific component, the Agent Telemetry Remapper, which is a transform that emits Datadog Agent-compatible versions of Saluki internal metrics.
The transform is fairly hardcoded, defining all of the metric mappings manually, and has a minimum of helper code for making those definitions a little easier to write. It emits _additional_ metrics, which means that for any metric with a mapping configured, …
=> [APR-207] chore: experimental approach to doing internal telemetry remapping

lib/saluki-core/src/components/sources/context.rs, lib/saluki-core/src/components/transforms/context.rs, lib/saluki-core/src/pooling/elastic.rs, lib/saluki-core/src/pooling/fixed.rs, lib/saluki-core/src/pooling/mod.rs, lib/saluki-core/src/topology/built.rs, lib/saluki-core/src/topology/interconnect/forwarder.rs
In #185, we explored the concept of an elastic object pool as a way to help combat the nearly-unbounded growth, over time, of the existing `FixedSizeObjectPool<EventBuffer>` pattern.
This PR introduces a new object pool implementation, `ElasticObjectPool<T>`, that instead of allocating all items upfront, instead is configured with a minimum and maximum capacity, and initially allocates only the minimum necessary items to populate the pool.
When a caller attempts to acquire an item, and the pool is empty but not yet at maximum capacity, items are allocated on-demand and then eventually returned back to the pool. In the background, a "shrinker" task runs periodically and measures both the "active" pool size (number of items attached to the pool, whether available or in use) and the average …
=> experiment: add elastic-sized object pool implementation

Makefile, lib/stringtheory/src/interning/fixed_size.rs, lib/stringtheory/src/interning/helpers.rs, lib/stringtheory/src/interning/map.rs, lib/stringtheory/src/interning/mod.rs, lib/stringtheory/src/lib.rs
This PR introduces a new, map-based string interner that is meant to serve as a potential replacement for `FixedSizeInterner` in cases where the number of interned strings is high enough that the linear scan necessary to find already-interned strings is prohibitively expensive.
The majority of this PR, however, is mostly centered on the reworking of `InternedString` to support a virtual table-based approach. This was necessary in order to support multiple interner implementations with a single, concrete type (`InternedString`) without needing to be tied down with an enum-based approach.
=> experimental: map-based string interner

lib/saluki-context/src/resolver.rs, lib/saluki-env/src/workload/collectors/cgroups.rs, lib/saluki-env/src/workload/collectors/containerd.rs, lib/saluki-env/src/workload/collectors/remote_agent.rs, lib/saluki-env/src/workload/helpers/cgroups.rs, lib/saluki-env/src/workload/providers/remote_agent.rs, lib/stringtheory/src/interning/map.rs, lib/stringtheory/src/lib.rs
Currently, string interning utilizes `FixedSizeInterner`, which is an string interner implementation that stores all information within the backing memory allocation. This is great for being bounded -- we don't use any more memory than the backing allocation -- but is bad for performance, as we have to do a linear scan of all entries when trying to intern.
In #250, we added support for a generic map-based interner, `GenericMapInterner`. This string interner implementation utilizes a normal map to track where in the backing allocation an interned string lives. This makes lookups for existing interned strings very cheap: O(1). Naturally, this uses more memory than `FixedSizeInterner`, but not by a hugely meaningful amount for regular workloads: each map entry is worth around 24 bytes, plus …
=> [APR-205] chore: try switching to map-based interner for general interning needs

Cargo.lock, lib/saluki-event/src/eventd/mod.rs, lib/saluki-event/src/lib.rs, lib/saluki-event/src/metric/metadata.rs, lib/saluki-event/src/service_check/mod.rs, lib/stringtheory/src/lib.rs
As stated in the title, we're trying out some optimizations to shrink the size of `Event` overall. As of the latest changes in this PR, we've shrunk `Event` from 216 bytes to 200 bytes, or by about 7%.
=> experiment: try to shrink the `Event` struct by brute forcing some field optimizations

lib/memory-accounting/src/allocator.rs, lib/saluki-core/src/pooling/elastic.rs
In #185, it was noted that when event buffers are extended -- additional capacity is required -- that the component that was unlucky enough to need to extend the buffer was ultimately the component attributed with the related allocation activity. This lead to components having this allocation usage attributed to them even if they had no allocations otherwise.
This PR simply threads through the allocation group token that is present at the time the pool is created, and uses it to wrap the acquire future such that all allocations within the acquire future are attributed to the original allocation group.
This is slightly different than the problem described in #185, which is around the extending of the event buffer itself, but is an equally relevant aspect to cover. As well, when #261 is …
=> [APR-205] chore: attribute all elastic pool allocations to the creator of the pool

Cargo.lock, Makefile, bin/agent-data-plane/src/env_provider.rs, bin/agent-data-plane/src/main.rs, lib/saluki-env/Cargo.toml, lib/saluki-env/src/workload/aggregator.rs, lib/saluki-env/src/workload/collectors/cgroups.rs, lib/saluki-env/src/workload/collectors/containerd.rs, lib/saluki-env/src/workload/collectors/mod.rs, lib/saluki-env/src/workload/collectors/remote_agent.rs, lib/saluki-env/src/workload/providers/remote_agent.rs
As part of #193, we want to integrate environment providers with the health registry as they often run many background tasks to drive metadata collection, in particular for workload providers.
This PR integrates all of the ADP-specific environment provider components -- Remote Agent workload providers, and the metadata collectors it depends on -- with the health registry. We've had to do a small amount of reworking of the structure to support this. In particular, the Remote Agent metadata collector needed a little bit of reworking to cope with some Tonic peculiarities and how we have to drive liveness checks... but other than that, it was mostly straightforward.
Fixes #193.
=> [APR-205] chore: integrate env provider with health registry

lib/saluki-components/src/sources/dogstatsd/mod.rs, lib/saluki-io/src/buf/mod.rs, lib/saluki-io/src/buf/vec.rs
Currently, ADP has two bugs with the handling of UDS stream payloads:
- handling partial packets
- compensating for the length delimiter itself
When in UDS stream mode, multiple packets might be read in a single `read` call, although we may encounter a partial read, such that a single `read` call contains all of packet 1, but only part of packet 2, and so on. Based on how we currently manage the buffers when doing reads, if any data is left after extracting all of the valid frames from the buffer, we throw the buffer away and then... our next read, with a fresh buffer, now has the remaining portion of that initial partial packet, and the length delimiter it reads is effectively a corrupted value, and overall it just leads to a bunch of errors and packets/metrics being dropped.
When in UDS …
=> fix: properly handle length-delimited packets in UDS stream mode for DogStatsD source

lib/saluki-components/src/destinations/datadog_metrics/mod.rs, lib/saluki-io/src/net/util/retry/backoff.rs, lib/saluki-io/src/net/util/retry/classifier/http.rs, lib/saluki-io/src/net/util/retry/classifier/mod.rs, lib/saluki-io/src/net/util/retry/lifecycle/http.rs, lib/saluki-io/src/net/util/retry/lifecycle/mod.rs, lib/saluki-io/src/net/util/retry/mod.rs, lib/saluki-io/src/net/util/retry/policy/mod.rs, lib/saluki-io/src/net/util/retry/policy/rolling_exponential.rs
In #267, we detailed the various ways in which logging (or the lack thereof) of retries, well, sucks. Overall, the experience when retries are firing is suboptimal because there's just no user-visible indication that it's even occurring.
This PR adds support for what we call a retry "lifecycle", a new trait that defines callbacks that are used to provide hooks into specific parts of the "lifecycle" of a retry: when we've decided that a retry needs to happen, and when a request was executed successfully. This now provides the means to add customized lifecycles tailored to the request/response at hand, such as a custom lifecycle for HTTP request/response types, which can then emit logs that explain why a response was considered for retry (4xx/5xx response code, TLS failure, etc).
While the …
=> [APR-248] chore: add support for configurable lifecycle events in retry policies to enable contextual logging

lib/saluki-event/src/metric/metadata.rs, lib/saluki-event/src/metric/value/mod.rs, lib/saluki-io/src/deser/codec/dogstatsd/mod.rs
In #271, we detailed the fact that the DogStatsD codec/source currently don't _do_ anything with the sample rate we parse from DogStatsD payloads. This inevitably leads to inconsistencies when payloads have a non-`1.0` sample rate.
We've done a small amount of refactoring to rearrange the codec to collect the raw values, then the sample rate, and then generate the `MetricValues` by combining the sample rate with the raw values. We've emulated what the Datadog Agent does, which is:
- for counts, we just multiple the value by the reciprocal of the sample rate (e.g., a sample rate of `0.25` and value of `10` leads to `40` based on `10 * (1 / 0.25) -> 10 * 4 -> 40`)
- for timers, histograms, and distribution, we record the value once if the sample rate wasn't specified, or is 1.0 (current …
=> [APR-248] chore: add proper support for sample rate in DSD codec

.gitlab/benchmark.yml, test/smp/regression/dogstatsd/cases/dsd_uds_100mb_250k_contexts/experiment.yaml, test/smp/regression/dogstatsd/cases/dsd_uds_100mb_3k_contexts/experiment.yaml, test/smp/regression/dogstatsd/cases/dsd_uds_100mb_3k_contexts_distributions_only/experiment.yaml, test/smp/regression/dogstatsd/cases/dsd_uds_10mb_3k_contexts/experiment.yaml, test/smp/regression/dogstatsd/cases/dsd_uds_1mb_3k_contexts/experiment.yaml, test/smp/regression/dogstatsd/cases/dsd_uds_1mb_50k_contexts/experiment.yaml, test/smp/regression/dogstatsd/cases/dsd_uds_1mb_50k_contexts_memlimit/experiment.yaml, test/smp/regression/dogstatsd/cases/dsd_uds_500mb_3k_contexts/experiment.yaml, test/smp/regression/dogstatsd/cases/dsd_uds_512kb_3k_contexts/experiment.yaml, test/smp/regression/dogstatsd/config.yaml
Our profiling data in SMP runs hasn't always been quite right, so now it's time to fix that. This PR specifically focuses on enabling internal profiling from the Agent for the DSD runs, since that profiling data is already possible to collect and better matches the profiling data we're collecting in the Agent's own SMP experiments.
Part 2 related to ADP to follow.
=> chore: fix some of the SMP profiling oddities (part 1)

test/smp/regression/saluki/config.yaml
Saluki doesn't have an internal profiler, so these are wasted
=> Disables internal profiling replicates on SMP runs

bin/agent-data-plane/src/components/remapper.rs, bin/agent-data-plane/src/main.rs, lib/saluki-components/src/destinations/blackhole/mod.rs, lib/saluki-components/src/destinations/datadog_events_service_checks/mod.rs, lib/saluki-components/src/destinations/datadog_metrics/mod.rs, lib/saluki-components/src/destinations/prometheus/mod.rs, lib/saluki-components/src/sources/dogstatsd/mod.rs, lib/saluki-components/src/sources/internal_metrics/mod.rs, lib/saluki-components/src/transforms/aggregate/mod.rs, lib/saluki-components/src/transforms/chained/mod.rs, lib/saluki-core/src/components/destinations/mod.rs, lib/saluki-core/src/components/sources/mod.rs, lib/saluki-core/src/components/transforms/mod.rs, lib/saluki-core/src/lib.rs, lib/saluki-core/src/task.rs, lib/saluki-core/src/topology/built.rs, lib/saluki-core/src/topology/running.rs, lib/saluki-core/src/topology/test_util.rs, lib/saluki-error/src/lib.rs, lib/saluki-io/src/net/server/http.rs
Currently, when trying to shutdown ADP (either locally with Ctrl-C or when sent a SIGTERM under some process supervision system), we fail to shutdown at all if something is stuck, like a component that is busy endlessly retrying a request or something to that effect.
This is annoying because it means we can't ever reasonably shutdown in the face of pathological component behavior, and worse, we have no insight into _which_ component is behaving poorly.
This PR principally fixes two main problems: add a way to force shutting down ADP after a fixed amount of time if it cannot otherwise gracefully shutdown, and drastically improve the logging around when and where component errors are occurring in terms of orderly/graceful shutdown.
We've refactored `RunningTopology` quite a bit, switching …
=> [APR-248] chore: add graceful topology shutdown and improve error messages when topology errors occur

Cargo.lock, LICENSE-3rdparty.csv, bin/correctness/airlock/src/main.rs, bin/correctness/ground-truth/src/analysis/metric.rs, bin/correctness/ground-truth/src/analysis/mod.rs, bin/correctness/ground-truth/src/sync.rs, bin/correctness/millstone/src/config.rs, bin/correctness/millstone/src/corpus.rs, deny.toml, lib/saluki-io/Cargo.toml, rust-toolchain.toml
Routine dependency bump and a bump in Rust version to 1.81.
Had to add a new allowance for the `Unicode-3.0` license after some dependencies switch from `Unicode-DFS-2016`, and fixed a feature flag or two, and also removed some dead code that Clippy was very angry about... but otherwise fairly straightforward.
=> chore: update deps + bump to Rust 1.81.0

lib/saluki-components/src/destinations/datadog_events_service_checks/mod.rs, lib/saluki-components/src/destinations/datadog_metrics/mod.rs, lib/saluki-io/Cargo.toml, lib/saluki-io/src/net/client/http/client.rs, lib/saluki-io/src/net/client/http/mod.rs, lib/saluki-io/src/net/util/retry/mod.rs, lib/saluki-io/src/net/util/retry/policy/mod.rs
As a follow-on to #297, this PR starts us down the path of bundling more logic/middleware into `HttpClient` itself, starting with timeouts and retries.
We've also removed the need to carry the underlying connector type as a generic type on `HttpClient` since we currently don't have a need to utilize anything other than a TCP-based HTTP-or-HTTPS connector for `HttpClient`.
=> chore: move more middleware logic into `HttpClient` directly

docker/Dockerfile.agent-data-plane
The various linters / analyzers complain about how this is bad, but, uh... we need it for profiling and it is what it is. :)
=> Go back to using the root user for ADP container.

.gitlab-ci.yml, .gitlab/build.yml, .gitlab/release.yml, docker/Dockerfile.datadog-agent
As we start to work towards building public Datadog Agent images with ADP bundled in, we need to add CI jobs that allow us to build these images when we cut ADP releases.
This PR does some reworking of the CI configuration, namely:
- a new `release` stage specifically for tasks related to building release images
- an intentional split between the internal Agent+ADP images (which have internal, DD-only additions on top of the public Datadog Agent image) and the public Agent+ADP images
It was a little tough to fully unify everything since, for example, we have difference such as our internal Datadog Agent image tags being in the form of `7-58-0-jmx` while the same image tag on the public Datadog Agent image is `7.58.0-jmx`.
There are also some other differences, such as using the ADP …
=> [APR-248] chore: add CI job for building images on tagged releases

docker/Dockerfile.agent-data-plane, docker/Dockerfile.datadog-agent
As part of our obligations when building public artifacts, we must document the license of not only our own software, but the licenses of any dependencies we utilize. While we currently document the licenses used through `LICENSE-3rdparty.csv`, we don't include a copy of those licenses alongside the relevant binary artifacts which means that it's both more difficult to look up the contents of those licenses, as well it not knowing which version of the license a given release refers to.
This PR introduces some small changes to our Dockerfiles in order to, based on `LICENSE-3rdparty.csv`, determine which licenses are in use and then copy the relevant licenses into the resulting container image. We do this by parsing `LICENSE-3rdparty.csv` and then utilize SPDX's helpful "[License List …
=> chore: bundle licenses of dependencies into ADP container image

.gitlab/internal.yml, .gitlab/release.yml
Just some general cleanup that hides the `internal` stage (used for building helper images) from normal CI pipeline runs, as well as tweaks the `release` stage to make it so you don't have to manually click each job to start... just the initial image build job step.
=> chore: get internal stage out of normal pipeline + make release stage one-click

lib/saluki-components/src/destinations/datadog_metrics/mod.rs, lib/saluki-components/src/destinations/datadog_metrics/request_builder.rs
This pr adds support for splitting oversized metric payloads. Previously, oversized payloads would just be dropped.
This pr introduces a change to the `scratch_buf` , allowing it to grow up to the endpoints `uncompressed_size_limit`. Instead of holding one singular encoded metric, `scratch_buf` will hold multiple and be cleared after `flush`.
Closes #159
=> [APR-270] Add support for splitting oversized payloads in the Datadog Metrics destination

.gitlab/correctness.yml, bin/correctness/airlock/src/driver.rs
Currently, there's an issue in CI where the non-internal image references we use in the correctness tests -- one for the Alpine container (to fix up permissions in the shared volume) and one for standalone DSD itself -- don't seem to... work. They're both valid references if you just did `docker pull ...` locally, but not in CI. I guess due to allowed registries. 🤷🏻 
We've switched to the GCR-based `dogstatsd` image, which is identical to the one on Docker Hub, and we've added a special environment variable-based override for Alpine which we set only in CI, and pull from our internal registry since we have it mirrored there.
=> chore: fix image references to make correctness tests work again

test/smp/regression/dogstatsd/cases/quality_gates_idle_rss/experiment.yaml, test/smp/regression/dogstatsd/cases/quality_gates_idle_rss/lading/lading.yaml, test/smp/regression/dogstatsd/config.yaml, test/smp/regression/saluki/cases/quality_gates_idle_rss/experiment.yaml, test/smp/regression/saluki/cases/quality_gates_idle_rss/lading/lading.yaml, test/smp/regression/saluki/config.yaml
This PR adds two new experiments (one for DSD, one for ADP) that add a bounds check for idle RSS usage. This is meant to mirror the current work being done with quality gates on the Datadog Agent repository.
We currently have the two experiments configured identically in terms of the RSS bound, to better demonstrate ADP hitting it and DSD not, or vise versa. The bound is a little higher than it ought to be for ADP, but I noticed sometimes a replicate has some spiky usage, so we're compensating for that here.
=> chore: add new idle RSS experiments for quality gates

.gitlab-ci.yml, .gitlab/release.yml
This PR adds more updates to the release stage, specifically around updating the image labels for the bundled images and adding in a publish step to actually publish the images to our public image repositories.
=> chore: add publish step for the ADP-bundled images

.gitlab/benchmark.yml
Update SMP CLI to the latest version to match the SMP services deployed for the agent team.
The changes on the CLI side are:
- Two new reports will be fetched by `smp job sync`. `report.json` is a machine-readable report and `quality_gates.md` is a bounds-checks summary meant for quality gates runs.
- Optimization may be disabled by setting `optimization_goal:none` in an experiment's config.
=> Update SMP CLI to 0.18.2

lib/memory-accounting/src/allocator.rs, lib/saluki-core/src/pooling/elastic.rs
`ElasticObjectPool`, as its name implies, is an elastic object pool that allows maintaining a minimum number of items in the pool, with a configured upper bound. When a caller tries to acquire an object from the pool, and there are no available objects, it can potentially build a new object so long as the maximum pool size has not been reached.
However, while the objects that the pool is initialized with have their memory attributed to the current allocation group at the time of creation, any objects which are built later on are attributed to whatever allocation group happens to be active at that time. This can cause issues where the object pool's memory usage is misattributed to callers, and essentially "transfers" over time from the original allocation group to the allocation group of …
=> [APR-248] chore: attribute burst item allocations to object pool owner in `ElasticObjectPool`

lib/saluki-core/src/topology/blueprint.rs, lib/saluki-core/src/topology/built.rs
Testing different changes to the global event buffer pool, specifically around the size of the buffers themselves as well as the minimum/maximum size of the object pool.
This PR tests changing the minimum size of the object pool to 32 items instead of 64.
=> chore: try shrinking global event buffer pool to a minimum of 32 buffers

lib/saluki-env/src/workload/aggregator.rs, lib/saluki-env/src/workload/helpers/mod.rs, lib/saluki-env/src/workload/metadata.rs, lib/saluki-env/src/workload/mod.rs, lib/saluki-env/src/workload/providers/remote_agent.rs, lib/saluki-env/src/workload/store.rs
This PR introduces some refactoring of the core workload primitives, namely `MetadataAggregator`, in order to better support multiple stores that subscribe to metadata operations.
This is in preparation of adding support for a Remote Agent "workload" collector (in addition to the existing Remote Agent "tag" collector) where ADP will be able to subscribe to a stream of `workloadmeta` events from the Datadog Agent and use them to collect the necessary information to map External Data entries to containers, necessary for #162.
The PR primarily introduces the concept of "stores", which are added to `MetadataAggregator` and receive metadata operations to be processed. We've added support for two types of stores -- consuming and borrowing -- to support stores which really only need to look at …
=> [APR-248] chore: refactor metadata aggregator to support multiple stores

lib/saluki-app/src/memory.rs
We would like to pull configured memory limits from the environment (Cgroups).
If the memory limit is not set, we check for `DOCKER_DD_AGENT` to see if we are running in a containerized environment. We pull the memory limit from the appropriate place depending on which Cgroup is enabled (v1 vs v2).
Closes #310
=> [APR-276] Add support to pull the configured memory limit from Cgroups

.gitlab/benchmark.yml
The warmup period is a convenience for targets that do not make guarantees about behavior from startup. This is not the case for saluki so the warmup period is a sneaky place where mistakes can hide, which we don't want.
=> Disable warmup-seconds for saluki Regression Detector

Makefile, README.md
This PR is simply doing some cleanup to make it easier to run ADP locally in a way that developers can then run a specific SMP experiment against it.
The new chain of commands to trivially run an SMP experiment is:
```shell
make profile-run-blackhole
#
#
make profile-run-adp
make profile-run-adp-ddprof
#
EXPERIMENT=dsd_uds_10mb_3k_contexts make profile-run-smp-experiment
=> chore: clean up makefile to simplify running SMP experiments locally against ADP

Cargo.lock, lib/saluki-components/Cargo.toml, lib/saluki-components/src/destinations/datadog_metrics/endpoint/endpoints.rs, lib/saluki-components/src/destinations/datadog_metrics/mod.rs, lib/saluki-config/src/lib.rs, lib/saluki-config/src/secrets.rs
The `additional_endpoints` setting of the Datadog Metrics destination allows specifying additional endpoints to which metrics will be forwarded, and is keyed by the endpoint, containing a list of API keys for each endpoint to use... all of which forms a list of unique endpoint/API key pairs to forward to.
While this setting is ostensibly meant to be a map of strings to string arrays, it can actually be passed in via two other forms in the Datadog Agent:
- a map of strings to strings (one API key per endpoint domain)
- a raw JSON string (used when specifying via environment variable, follows the same structural logic as above)
Currently, we don't support the "map of strings to strings" structure.
This PR adds additional support for the "map of strings to strings" case by adding additional …
=> fix: better deal with the myriad ways that additional endpoints can be specified in DD Metrics destination

Cargo.lock
As stated in the PR title. We're doing some general updates here, and some of them are meant to address RustSec advisories, namely `rustls` and `url`.
=> chore: update deps to deal with advisories

Cargo.lock, Cargo.toml, LICENSE-3rdparty.csv, lib/saluki-components/src/destinations/datadog_metrics/mod.rs, lib/saluki-components/src/destinations/datadog_metrics/request_builder.rs, lib/saluki-core/src/pooling/helpers.rs, lib/saluki-io/Cargo.toml, lib/saluki-io/src/buf/chunked.rs, lib/saluki-io/src/buf/mod.rs, lib/saluki-io/src/buf/vec.rs, lib/saluki-io/src/net/client/http/mod.rs
This PR introduces the ability to convert an owned `BytesBuffer` into a shareable `FrozenBytesBuffer`, while still retaining the semantics of returning the underlying buffer (`FixedSizeVec`) to the object pool when all shared references are dropped. This will allow us to build a future abstraction where buffers can be written to by the Datadog Metrics destination, and then frozen to allow sending requests to multiple endpoints _concurrently_ where we want to cheaply reference the existing buffer(s) without cloning.
I've taken a specific approach here which is to use the `triomphe` crate, which provides an enhanced version of `std::sync::Arc`. Specifically, `triomphe::UniqueArc` allows creating an `Arc` that can be used to mutate the inner value without any atomic loads since it encodes …
=> chore: add ability to convert `BytesBuffer` into shareable 'frozen' buffer

bin/agent-data-plane/src/components/remapper.rs, bin/agent-data-plane/src/main.rs
This simply unifies the metric naming scheme to match the Datadog Agent, where our ADP-specific metrics will end up under `datadog.agent.adp` instead of the current `datadog.saluki`
=> [APR-248] chore: emit ADP internal telemetry under consistent `datadog.agent` prefix

Cargo.lock, lib/saluki-context/Cargo.toml, lib/saluki-context/src/tags.rs
Was examining some profiler output related to DSD metrics parsing, and `BorrowedTag::name_and_value` showed up as taking a reasonably large chunk of time. I used a naive splitting approach (`str::split_once`) when writing `BorrowedTag`, and so it's perhaps not surprising that it's less optimal than it could be.
This PR tries out a `memchr`-based solution where we simply search for the first instance of `:` in the raw tag string when creating `BorrowedTag`, and then reuse that in `name`, `value`, and `name_and_value` when deciding whether or not there's anything to split.
In local testing, this has a fairly positive effective on ingest throughput, but we'll see what SMP has to say.
=> experiment: try speeding up `BorrowedTag` splitting via `memchr`

Cargo.lock, docker/Dockerfile.datadog-agent, lib/saluki-env/Cargo.toml, lib/saluki-env/src/lib.rs, lib/saluki-env/src/prelude.rs, lib/saluki-env/src/workload/external_data.rs, lib/saluki-env/src/workload/mod.rs, lib/saluki-env/src/workload/providers/remote_agent.rs, lib/saluki-env/src/workload/stores/external_data.rs, lib/saluki-env/src/workload/stores/mod.rs, lib/saluki-env/src/workload/stores/tag.rs
This PR adds a new metadata store, `ExternalDataStore`, that is designed to hold the mapping between External Data and the underlying entity ID (generally container IDs).
We've also added a new trait method to `WorkloadProvider` for resolving this information: `resolve_entity_id_from_external_data`. We use two new primitive structs, `ExternalData` and `ExternalDataRef<'a>`, which are designed to allow storing the external data in its native form, and then look up the mappings using a borrowed variant.
Support to actually plumb this all together during the enrichment step will come in a follow-up PR.
=> [APR-248] chore: add external data metadata store + allow resolving through workload provider

lib/saluki-app/src/memory.rs, lib/saluki-components/src/destinations/datadog_metrics/mod.rs, lib/saluki-components/src/sources/dogstatsd/mod.rs, lib/saluki-components/src/transforms/aggregate/mod.rs, lib/saluki-core/src/components/metrics.rs, lib/saluki-core/src/topology/interconnect/event_stream.rs, lib/saluki-core/src/topology/interconnect/forwarder.rs
As part of the lead up to better controlling what internal telemetry is emitted by _default_, we're setting all internal metrics to be emitted at debug verbosity. Currently, they're emitted at a info verbosity, which is the default for `metrics`.
We don't actually do any filtering based on metric verbosity, but we'll do so in a follow-up PR.
=> [APR-248] chore: emit all internal metrics at debug verbosity

lib/saluki-components/src/sources/dogstatsd/mod.rs, lib/saluki-io/src/deser/codec/dogstatsd/mod.rs
This PR fixes an issue with the "events received" metric emitted by the DogStatsD source where we undercount the metric events that we received due to using an incorrect source for said count.
Prior to this PR, we were querying the "length" of the given `MetricValues` generated for the packet, which only tracks the number of timestamped values. At the time of calling the `MetricValues::len` method, right after parsing the packet, we would correctly report the number of counter metrics (timestamped points haven't been aggregated yet) but for histograms or distributions, we would have written multi-value payloads into a single container, leading a single timestamped point... which then leads us to undercounting.
We've simply changed the code that builds `MetricValues` to count the …
=> fix: properly calculate events received in DogStatsD source

lib/saluki-core/src/observability/metrics.rs
We're adding the data plane's process ID to the origin metadata for internal metrics in order to try and get them enriched like any other metrics coming in over DogStatsD.
Closes #357.
=> [APR-248] fix: set process ID origin for internal metrics to get origin detection-based enrichment working

bin/agent-data-plane/src/components/remapper.rs, lib/saluki-components/src/destinations/datadog_metrics/mod.rs, lib/saluki-components/src/destinations/datadog_metrics/telemetry.rs, lib/saluki-components/src/sources/dogstatsd/mod.rs, lib/saluki-core/src/components/metrics.rs, lib/saluki-io/src/buf/chunked.rs, lib/saluki-io/src/net/client/http/mod.rs, lib/saluki-io/src/net/client/http/telemetry.rs
This PR centers around adding more remapped internal telemetry as we push to have `AgentTelemetryRemapper` continue to more faithfully emit the same internal telemetry emitted by the Datadog Agent.
We've pushed two major chunks of work in this PR: updates to the remapper configuration, and the addition of a generic Tower middleware layer for emitting "transaction" telemetry.
The remapper configuration changes are pretty self-explanatory: we've added new metrics, fixed messed up ones, and also fixed a bug with `RemapperRule::try_match` which was causing breakage with tags that were meant to be remapped (name change) instead of simply copied over as-is. We've also sprinkled some TODOs to track other metrics that don't exist yet and will be a little uglier to implement so that we don't …
=> [APR-248] fix: remap more internal telemetry + add generic tower middleware for transaction telemetry

Cargo.lock, Cargo.toml, LICENSE-3rdparty.csv, lib/saluki-env/Cargo.toml, lib/saluki-env/src/workload/helpers/remote_agent/client.rs
During startup, ADP will initialize a number of subsystems, among them the workload provider, which involves communicating with the Core Agent to receive tagger and workloadmeta events.
If the Core Agent is not yet listening on the IPC endpoint, or the authentication token does not yet exist, this leads to ADP erroring out and exiting very rapidly. When deployed, the effect is that the ADP container restarts a number of times before eventually it is able to read the authentication token file and connect to the IPC endpoint.
This PR augments `RemoteAgentClient` to add retries to the connect phase when building, allowing us to more gracefully wait for the Core Agent to get everything in place. By default, we try up to 10 times, waiting 2 seconds between attempts, for a total grace period of …
=> [APR-248] chore: retry connect attempt before returning error in `RemoteAgentClient::from_configuration`

bin/agent-data-plane/src/main.rs
This PR removes our internal telemetry from being emitted as part of regular metrics flowing through the ADP topology, and exposes them only from the Prometheus scrape endpoint.
This is done to better align with how the Datadog Agent scrapes its own internal telemetry, which materially changes how the metrics are interpreted/forwarded to the Datadog platform.
=> chore: only expose internal telemetry over Prometheus endpoint

Makefile, lib/saluki-components/src/destinations/datadog_events_service_checks/mod.rs, lib/saluki-components/src/destinations/datadog_metrics/mod.rs, lib/saluki-io/src/net/client/http/client.rs, lib/saluki-io/src/net/client/http/conn.rs
This PR addresses #359, which aims to capture the total number of bytes sent by a component. In this case of the Datadog Metrics and Datadog Events/Service Checks destinations, this is the actual number of bytes sent in a request, including both the headers and body.
As we're tracking this at the connection level, it will work for retries and so on.
=> [APR-248] chore: fix bytes sent metric in DD Metrics and DD Events/Service Checks destinations

.cargo/config.toml, Cargo.lock, Cargo.toml, LICENSE-3rdparty.csv, bin/agent-data-plane/Cargo.toml, bin/agent-data-plane/src/main.rs, test/smp/regression/dogstatsd/config.yaml, test/smp/regression/saluki/cases/quality_gates_idle_rss/experiment.yaml, test/smp/regression/saluki/config.yaml, tooling/jemalloc-stats-analyze.py
This PR switches ADP to using `jemalloc` as the process-wide memory allocator.
We've done this for a few reasons:
- `jemalloc` allows for vastly more fine-grained tuning/control over how the allocator gets memory from _and_ returns memory to the operating system
- `jemalloc` has internal profiling/stats collection that can eventually augment what we get from our own internal allocation telemetry (another level of detail to help quantify what we see at the OS level)
- we see meaningful improvements to the process RSS, compared to `glibc`, for nearly all experiments besides `quality_gates_idle_rss`
We're explicitly setting a customized `MALLOC_CONF` at build-time (in `.cargo/config.toml`) since `jemalloc` uses defaults that optimize for high concurrency: a large number of memory arenas, …
=> [APR-248] enhancement: switch to `jemalloc` as allocator for ADP

Cargo.lock, Cargo.toml, LICENSE-3rdparty.csv, deny.toml
This PR is just doing a bunch of dependency updates:
- general `cargo update` to pull in newer versions that fit within the SemVer declarations we have in `Cargo.toml`
- switch to `Manishearth/triomphe` instead of the forker version at `tobz/triomphe` as the changes related to `Arc::into_unique` got merged (but haven't yet been published officially)
- fix the warning from `cargo-deny` related to the Git dependency on `triomphe`
- removed `governor` which we don't even use (holdover from contest resolver caching experimentation)
=> chore: dependency updates

lib/saluki-env/src/workload/collectors/remote_agent/tagger.rs
Currently, the `remote_agent` workload metadata collector only cares about container and Kubernetes pod entities as it relates to aggregating their tags. The Datadog Agent will additionally send us `container_image_metadata` and `internal` entities, which we don't handle. This results in a burst of warning logs -- about the fact we don't handle those entity ID types -- during startup, with a slow trickle of them afterwards.
We know we don't handle those, so the warnings aren't particularly useful.
This PR introduces two changes:
- handle `internal` entities
- skip `container_image_metadata` entities without logging
The skipping part is pretty self-explanatory: we literally don't care about those entities at all, so it's not that we don't handle them but that we don't _want_ to handle …
=> chore: handle global entity ID in tagger + ignore unused entity IDs

bin/agent-data-plane/src/components/remapper/rules/transaction.rs, lib/saluki-io/src/net/client/http/telemetry.rs
This makes it match the behavior of the Datadog Agent.
=> chore: drop trailing slash from domain tag in endpoint telemetry

Cargo.lock, Cargo.toml, LICENSE-3rdparty.csv, lib/saluki-components/Cargo.toml, lib/saluki-components/src/transforms/aggregate/mod.rs, lib/saluki-components/src/transforms/aggregate/telemetry.rs, lib/saluki-metrics/Cargo.toml, lib/saluki-metrics/src/lib.rs, lib/saluki-metrics/src/test.rs
This PR principally focuses on adding more internal telemetry to the aggregate transform, specifically around aggregate-specific data like the number of active contexts, active contexts by metric type, and more.
Additionally, we've started bootstrapping some metrics testing utilities in `saluki-metrics` to make it easier to assert metric emission/correct values/etc in unit tests.
=> chore: add more telemetry to aggregate transform + metrics testing utilities

lib/saluki-io/src/deser/framing/length_delimited.rs, lib/saluki-io/src/deser/framing/mod.rs, lib/saluki-io/src/deser/framing/newline.rs
This PR improves the error messages emitted by our two framers (length delimited and newline delimited) in order to better assist in understanding framing errors with DSD at runtime.
Currently, there is only a single error variant which fails to encode crucial information about whether the error was due to a partial frame at EOF, or a frame length that was bigger than the actual buffer capacity, and so on. This makes it much harder to understand the underlying cause of framing errors when they occur.
=> chore: better framing error messages to differentiate underlying causes

Makefile, lib/saluki-io/src/deser/framing/mod.rs, test/one-off/millstone-adp-standalone.yaml, test/smp/regression/saluki/cases/dsd_uds_100mb_250k_contexts/experiment.yaml, test/smp/regression/saluki/cases/dsd_uds_100mb_250k_contexts/lading/lading.yaml, test/smp/regression/saluki/cases/dsd_uds_100mb_3k_contexts/experiment.yaml, test/smp/regression/saluki/cases/dsd_uds_100mb_3k_contexts/lading/lading.yaml, test/smp/regression/saluki/cases/dsd_uds_100mb_3k_contexts_distributions_only/experiment.yaml, test/smp/regression/saluki/cases/dsd_uds_100mb_3k_contexts_distributions_only/lading/lading.yaml, test/smp/regression/saluki/cases/dsd_uds_10mb_3k_contexts/experiment.yaml, test/smp/regression/saluki/cases/dsd_uds_10mb_3k_contexts/lading/lading.yaml, test/smp/regression/saluki/cases/dsd_uds_1mb_3k_contexts/experiment.yaml, test/smp/regression/saluki/cases/dsd_uds_1mb_3k_contexts/lading/lading.yaml, test/smp/regression/saluki/cases/dsd_uds_1mb_3k_contexts_dualship/experiment.yaml, test/smp/regression/saluki/cases/dsd_uds_1mb_3k_contexts_dualship/lading/lading.yaml, test/smp/regression/saluki/cases/dsd_uds_1mb_50k_contexts/experiment.yaml, test/smp/regression/saluki/cases/dsd_uds_1mb_50k_contexts/lading/lading.yaml, test/smp/regression/saluki/cases/dsd_uds_1mb_50k_contexts_memlimit/experiment.yaml, test/smp/regression/saluki/cases/dsd_uds_1mb_50k_contexts_memlimit/lading/lading.yaml, test/smp/regression/saluki/cases/dsd_uds_40mb_12k_contexts_40_senders/experiment.yaml, test/smp/regression/saluki/cases/dsd_uds_40mb_12k_contexts_40_senders/lading/lading.yaml, test/smp/regression/saluki/cases/dsd_uds_500mb_3k_contexts/experiment.yaml, test/smp/regression/saluki/cases/dsd_uds_500mb_3k_contexts/lading/lading.yaml, test/smp/regression/saluki/cases/dsd_uds_50mb_10k_contexts_no_inlining/experiment.yaml, test/smp/regression/saluki/cases/dsd_uds_50mb_10k_contexts_no_inlining/lading/lading.yaml, test/smp/regression/saluki/cases/dsd_uds_50mb_10k_contexts_no_inlining_no_allocs/experiment.yaml, test/smp/regression/saluki/cases/dsd_uds_50mb_10k_contexts_no_inlining_no_allocs/lading/lading.yaml, test/smp/regression/saluki/cases/dsd_uds_512kb_3k_contexts/experiment.yaml, test/smp/regression/saluki/cases/dsd_uds_512kb_3k_contexts/lading/lading.yaml, test/smp/regression/saluki/cases/quality_gates_idle_rss/experiment.yaml
In some cases, DogStatsD clients utilizing UDS stream mode[^1] may or may not send a trailing newline on the framed metric payload. The Datadog Agent will handle either case, but ADP currently does not handle this.
If many payloads are sent without a trailing newline, we can fill up our receive buffer because the framer never manages to extract inner frames as they lack a newline. When the receive buffer is filled, the next socket read will yield zero bytes, causing us to believe that we've hit EOF. When this happens, the framer is told that we've hit EOF, which will cause it to forego waiting for the trailing newline... and this allows it to make forward progress with decoding frames, and eventually, metric payloads.
However, in certain cases, if the last payload in the buffer is only …
=> fix: handle lack of trailing newline in DSD UDS stream payloads

Cargo.lock, Cargo.toml, LICENSE-3rdparty.csv, bin/agent-data-plane/src/main.rs, lib/saluki-api/Cargo.toml, lib/saluki-api/src/lib.rs, lib/saluki-app/Cargo.toml, lib/saluki-app/src/lib.rs, lib/saluki-app/src/logging.rs
This PR adds support for dynamically updating the logging filter directives at runtime to support in-place debugging, without having to go through the costly process of redeployment.
The `tracing` stack is configured with a dynamic filtering layer (the ["reload](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/reload/struct.Layer.html)" layer) which allows changing the filter directives dynamically at any time. This retains the full power of `DD_LOG_LEVEL`, specifying anywhere from a single level directive (info, debug, etc) to multiple module-scoped directives (e.g., `saluki_io=debug,saluki_core=trace,info`).
This is coupled with a new API handler which installs two routes on the primary administrative API, one for setting the override and one for resetting back to the …
=> enhancement: add support for dynamically overriding the log level at runtime

lib/saluki-components/src/sources/dogstatsd/mod.rs, lib/saluki-components/src/transforms/origin_enrichment/mod.rs, lib/saluki-env/src/workload/stores/tag.rs, lib/saluki-event/src/metric/metadata.rs, lib/saluki-io/src/deser/codec/dogstatsd/mod.rs
This PR wires up External Data support by threading it through the DSD codec, into `MetricMetadata`, and finally into the Origin Enrichment transform.
=> chore: wire up External Data support for origin detection

test/smp/regression/dogstatsd/config.yaml, test/smp/regression/saluki/config.yaml
This commit updates lading to the latest release, introducing connection count data to blackholes and improved parsing of cgroup v2 information. I have also updated `memory_allotment` to have the "GiB" unit and not "g" which is ambiguous.
=> Update lading to 0.25.3

.gitlab-ci.yml, docker/Dockerfile.datadog-agent
Just bumping the Agent RC version so our converged images track closer to where we want to be.
=> chore: update to latest Datadog Agent RC for image builds/benchmarks

lib/saluki-context/src/context.rs, lib/saluki-context/src/hash.rs, lib/saluki-context/src/lib.rs, lib/saluki-context/src/resolver.rs, lib/saluki-context/src/tags/mod.rs, lib/saluki-context/src/tags/raw.rs
Prior to this PR, the `Tagged` trait was something we added to abstract over the numerous possible ways to supply the borrowed tags that get fed in when resolving a context.
This ends up being overkill and unnecessary without the `Resolvable` machinery, and would be better served as a way to abstract getting the materialized tags from different implementations of tag storage.
This PR reworks the `Tagged` trait slightly by moving it under `saluki_context::tags`, having it give back `&Tag` instead of `&str`, and adding implementations for the major tag storage types, `TagSet`, `SharedTagSet`, and `Context`. This gives us a unified approach to visiting tags, regardless of where they're stored.
We've also reverted back, essentially, to the previous method signatures for hashing a context and …
=> chore: make `Tagged` relevant to materialized tags, not raw tags

lib/saluki-components/src/destinations/datadog/metrics/request_builder.rs, lib/saluki-components/src/destinations/prometheus/mod.rs, lib/saluki-context/src/context.rs, lib/saluki-context/src/hash.rs, lib/saluki-context/src/lib.rs, lib/saluki-context/src/resolver.rs, lib/saluki-context/src/tags/mod.rs, lib/saluki-context/src/tags/raw.rs
This PR just updates the metrics-related destinations to actually take advantage of `Tagged` by using it on the `Context` itself, so they're not having to reach into specific getters for tags.
This sets us up later to incorporate visiting origin tags in the same call, without the callers needing to know or care deeply about the difference between instrumented and origin tags.
=> chore: switch metric-specific destinations to use new `Tagged` trait for metric tags

lib/saluki-components/src/destinations/datadog/metrics/request_builder.rs, lib/saluki-components/src/destinations/prometheus/mod.rs, lib/saluki-components/src/sources/dogstatsd/origin.rs, lib/saluki-context/src/context.rs, lib/saluki-context/src/hash.rs, lib/saluki-context/src/lib.rs, lib/saluki-context/src/resolver.rs, lib/saluki-context/src/tags/mod.rs, lib/saluki-context/src/tags/raw.rs, lib/saluki-env/src/workload/external_data.rs, lib/saluki-env/src/workload/mod.rs, lib/saluki-env/src/workload/providers/noop.rs, lib/saluki-env/src/workload/providers/remote_agent.rs, lib/saluki-env/src/workload/stores/external_data.rs
We weren't entirely using External Data in the correct way prior to this PR, as the Datadog Agent actually enriches for the pod UID contained in External Data, and _then_ enriches based on the container ID that is resolved by _using_ the External Data. We only ever turned External Data identifiers into the container ID, so we were potentially missing things in doing it that way.
This PR adds a new type, `ResolvedExternalData`, which holds the entity IDs of the pod and container, respectively, and can be used to store the result of resolved a raw External Data identifier. This will be necessary for follow-up PRs that need to access the resolved entities from External Data when doing origin detection/enrichment.
We've reworked existing usages of External Data, although these usages will in …
=> chore: slightly revamp External Data support to expose both pod and container entity ID

bin/agent-data-plane/Cargo.toml, bin/agent-data-plane/src/main.rs
When running ADP on macOS, it would immediately crash due to an error coming from `jemalloc`:
```
<jemalloc>: No THP support: thp:never
<jemalloc>: Abort (abort_conf:true) on invalid conf value (see above).
```
We previously disabled THP support in `jemalloc` to deal with ballooning RSS but, seemingly, `jemalloc` considers it a completely invalid configuration when on macOS instead of just ignoring, thus the abort.
This PR simply moves our usage of `jemalloc` to be gated behind `#[cfg(target_os = "linux")]`. In the future, it'd be nice to just adjust our compile-time `jemalloc` configuration string for macOS to not include the `thp:never` bit, but the Cargo configuration file schema doesn't support per-target environment variables, so we don't have an easy way to do so... yet, at least. …
=> fix: only use jemalloc on linux

lib/saluki-env/src/workload/collectors/cgroups.rs, lib/saluki-env/src/workload/helpers/cgroups.rs, lib/saluki-env/src/workload/mod.rs, lib/saluki-env/src/workload/on_demand_pid.rs, lib/saluki-env/src/workload/providers/remote_agent/mod.rs
Currently, the Remote Agent workload provider provides mapping capabilities between process ID and container ID by listening to `containerd` events, noting the process ID that a container is started with. This works well when containers have their actual application process as the entrypoint. However, this breaks down in the case where a process supervisor/specialized init process (such as `tini`) is used, as the application sending metrics then becomes a child process, and as such, we don't know its process ID from the events sent by `containerd`.
In these cases, we need a mechanism where we can query process IDs on demand, to see if they belong to a cgroup, and if that cgroup is attached to a container... which is exactly what this PR does.
We've introduced a new helper -- …
=> fix: handle nested processes in containers for PID-to-container ID resolving

test/smp/regression/dogstatsd/cases/dsd_uds_100mb_250k_contexts/lading/lading.yaml, test/smp/regression/saluki/cases/dsd_uds_100mb_250k_contexts/lading/lading.yaml
This PR is trying to fix both the fact that the Saluki variant of the `dsd_uds_100mb_250k_contexts` hits OOM issues with its `lading` configuration due to recent SMP runner changes... _and_ the fact that the `lading` configuration only seems to end up generating ~160-170k contexts.
This should hopefully solve both and lead to around ~215k contexts being generated while still fitting within the new limits imposed on SMP runners.
N/A
N/A
=> fix: shrink block cache size for saluki/`dsd_uds_100mb_250k_contexts` experiment to avoid OOM

lib/saluki-components/src/sources/dogstatsd/mod.rs, lib/saluki-components/src/sources/dogstatsd/origin.rs
Adds `#[serde(default)]` to `origin_enrichment` 
N/A
N/A
=> chore: add default origin enrichment configuration

lib/saluki-env/src/workload/collectors/cgroups.rs, lib/saluki-env/src/workload/helpers/cgroups.rs, lib/saluki-env/src/workload/on_demand_pid.rs
In the scenario where ADP (and, likewise, the Datadog Agent) is deployed in a containerized environment, it will attempt to query the host for the current cgroups hierarchy (either v1 or v2) in order to discover any containers running on the host. It does so by taking some configuration around where the _host's_ `/proc` and `/sys/fs/cgroup` (`container_proc_root` and `container_cgroup_root`, respectively) have been mapped to within the ADP container, and then examines all mountpoints to find the active cgroups hierarchy. Based on what it finds, it uses that information to inform subsequent calls, whether that be finding all child cgroups mapped to containers, or attempting to find the cgroup attached to a specific process ID.
This process is meant to ultimately provide the "root" path -- …
=> fix: use correct cgroups root path when operating in host-mapped mode

lib/saluki-components/src/transforms/aggregate/mod.rs, lib/saluki-components/src/transforms/aggregate/telemetry.rs
This PR adds the ability for the `aggregate` transform to batch "passthrough" (pre-aggregated) metrics for short periods of time, in larger-than-normal event buffers, with the express goal of improving the efficiency of handling pre-aggregated metrics.
We've updated the logic of the transform to follow an equivalent behavior in the Datadog Agent's "no aggregation pipeline", which looks something like:
- batch pre-aggregated metrics into their own buffer (defaults to 2048 points)
- if the batch is filled to capacity, flush it to the "forwarder" (Datadog Metrics destination, in our case)
- every two seconds, check if we have received any pre-aggregated metrics within the last second: if not, flush the batch to the "forwarder"
This aims to improve how many pre-aggregated metrics are packed …
=> enhancement: batch timestamped (passthrough) metrics for a short period of time before forwarding

lib/saluki-components/src/destinations/datadog/metrics/mod.rs, lib/saluki-components/src/destinations/datadog/metrics/request_builder.rs, lib/saluki-event/src/metric/mod.rs
In #457, we changed around how we handle the ability to split oversized request payloads in the Datadog Metrics destination from storing the raw encoded metrics to storing the `Metric` values themselves. This was done in order to improve the average memory consumed by the destination, as large event batches would tend to drive the buffers used to hold the encoded metrics up in size over time, which could waste significant amounts of memory in the long run.
While switching to holding `Metric` values directly provided more determinism -- `Metric` is only ever X bytes, not variable -- it _worsened_ the worst-case behavior because metrics can easily be encoded to a smaller size than that of `Metric`, meaning that after encoding a certain number of metrics, holding their `Metric` …
=> enhancement: allow configuring maximum number of metrics per DD metrics request payloads

bin/agent-data-plane/src/components/remapper/rules/aggregation.rs, lib/saluki-components/src/transforms/aggregate/mod.rs, lib/saluki-components/src/transforms/aggregate/telemetry.rs, lib/saluki-context/src/context.rs, lib/saluki-context/src/origin.rs, lib/saluki-context/src/resolver.rs, lib/saluki-context/src/tags/mod.rs
This PR adds a few new metrics for the aggregate transform, as well as some remapped ones:
- `aggregate_active_contexts_bytes_by_type` (new in Saluki, tracks total context-related bytes per metric type)
- `aggregator.dogstatsd_contexts_by_mtype` (new remapped metric, derived from `aggregate_active_contexts_by_type`)
- `aggregator.dogstatsd_contexts_bytes_by_mtype` (new remapped metric, derived from `aggregate_active_contexts_by_type`)
- `no_aggregation.processed` (new remapped metric, derived from `aggregate_passthrough_metrics_total`)
- `no_aggregation.flush` (new remapped metric, derived from `aggregate_passthrough_flushes_total`)
The bulk of this PR, however, is the actual addition of the logic to _expose_ the size of a context. I believe the code comments and unit tests should be …
=> enhancement: add more aggregator-specific telemetry

lib/saluki-components/src/transforms/chained/mod.rs, lib/saluki-components/src/transforms/host_enrichment/mod.rs, lib/saluki-core/src/components/transforms/mod.rs
This PR switches `SynchronousTransform::transform_buffer` from taking `&self` to taking `&mut self`.
This unlocks the ability for synchronous transforms to actually maintain mutable state that is needed for transforming metrics. It was an oversight on my part when originally designing `SynchronousTransform` to not do so, so we're just rectifying things here.
N/A
N/A
=> enhancement: make synchronous transforms take a mutable receiver

lib/saluki-context/src/origin.rs, lib/saluki-context/src/resolver.rs
When attempting to modify an existing context, it is better to use a dedicated context resolver so that the portions being modified -- either the name and/or instrumented tags -- can be interned, and the context overall can be cached for future resolve calls. However, this presents an issue when trying to maintain origin tags, as resolving a context normally requires the "raw" origin information, which is no longer present once a context has been resolved and all that is held is `Context`.
This PR introduces a change to `ContextResolver` by exposing a new method -- `resolve_with_origin_tags` -- that allows specifying the origin tags to use for the context at the time of resolving. This allows callers to simply clone the existing `OriginTags` from a context (which is cheap, since it's just …
=> chore: expose new method to resolve context using existing origin tags

bin/agent-data-plane/src/components/remapper/rules/aggregation.rs, lib/saluki-components/src/transforms/aggregate/mod.rs, lib/saluki-components/src/transforms/aggregate/telemetry.rs
This PR adds a new telemetry metric -- `aggregate_flushed_total` -- which tracks the number of series and sketches flushed by the aggregate transform. It additionally contains a new remapped variant of this metric to match the `datadog.agent.aggregator.flush` metric.
It remains to be seen if it's necessarily worth locally tallying up the series/sketches totals before incrementing the counters, but I went with the simpler approach for now.
Built and ran ADP locally and observed the new metrics when querying the internal telemetry endpoint.
N/A
=> chore: emit series/sketches flushed telemetry for aggregation

lib/saluki-components/src/destinations/datadog/common/io.rs, lib/saluki-components/src/destinations/datadog/common/telemetry.rs, lib/saluki-components/src/destinations/datadog/metrics/mod.rs
Currently, the Datadog Metrics destination aims to flush request payloads as soon as it is done processing incoming event buffers. This means that if we immediately get, for example, 10,000 metrics... we process those into the smallest number of requests that we can, and fire them all off immediately. We do this even if the last request is far below the allowable payload size limits, and even if we get another large batch of events within the next 10-20 milliseconds.
This PR introduces a simple time-based batching mechanism to try and improve the long tail inefficiency of large batches of metrics that will, by design, come in during separate loop iterations, and would otherwise result in far more inefficiently-filled request payloads.
We keep the same logic we have where we'll flush out a …
=> fix: improve DD Metrics request efficiency by introducing time-based batching

.gitlab/build.yml, docker/Dockerfile.agent-data-plane
This PR adds a new CI job to build a FIPS-compliant version of ADP. We've had support for a FIPS-compliant build for a while now, but don't use it exclusively/by default as it can sometimes cause breakage with specific load balancer endpoints that aren't meant exclusively for FIPS-compliant TLS.
This is half of the work needed for #508 as there's still no (yet) public FIPS-compliant Agent images to build our converged ADP images from.
N/A
N/A
=> chore: build FIPS-compliant version of ADP

bin/agent-data-plane/src/main.rs
Only add the host tags transform if ADP is not running in standalone mode. This prevents any errors arising from the  `auth_token` file being missing and the `RemoteAgentClient` not being created.
=> chore: add host tags transform when not in standalone mode

Cargo.lock, bin/correctness/airlock/Cargo.toml
As part of the upgrade to `bollard` 0.18.x, there was a change in the default features exposed which are now required to support specific I/O transports out-of-the-box.
This PR simply enables the `http` feature flag to add support back for connecting to the Docker daemon over HTTP/TCP.
Ensured the `run-ground-truth` CI step ran correctly for this PR's CI pipeline.
N/A
=> fix: enable `http` feature flag for `bollard`

.gitlab/benchmark.yml, .gitlab/build.yml, .gitlab/correctness.yml
This PR does a little bit of CI cleanup, specifically:
- remove `allow_failure: true` from various CI jobs that we want to depend on as required checks for PRs (correctness test + SMP regression experiments for ADP)
- adds timeouts and/our retries to various jobs that involve building Rust binaries
We've noticed a number of times in the recent past where Rust builds, especially multi-platform builds, can essentially become stuck and run until they timeout at the 60 minute mark. This is bad because it can stall the pipeline, and we know that if we're not done after some certain amount of time (like 15 minutes, let's say) that something is very long... so waiting 4x longer than the average runtime of a job is not good.
N/A
N/A
=> chore: clean up some CI jobs by disallowing failure and tightening timeouts/retries

lib/saluki-components/src/destinations/datadog/metrics/request_builder.rs, lib/saluki-components/src/destinations/prometheus/mod.rs, lib/saluki-context/src/tags/mod.rs
This PR adds a new default method on the `Tagged` trait -- `visit_tags_deduped` -- which allows visiting the tags of anything that implements `Tagged` in a deduplicated fashion. This can be important when dealing with origin tags, as the origin detection logic, in keeping with matching the behavior of the Datadog Agent, can potentially enrich a metric multiple times with the same underlying set of tags.
Added a unit test to assert that the code added properly dedupes. Ran Agent E2E test suite to demonstrate the deduping functionally matches the Datadog Agent, as the mismatch was originally highlighted by the Agent E2E test suite.
N/A
=> fix: provide default method on `Tagged` for visiting deduped tags

.github/workflows/docs.yml
Fixes a bug with choosing a non-existent Node version in the docs CI job.
N/A
N/A
=> fix: use node v23, not v24, in docs CI job

.github/workflows/docs.yml
We were referencing `master` instead of `main`, which means we don't properly trigger the publish step even when `main` is pushed.
N/A
N/A
=> fix: specify the right branch ref for guarding the docs publish step

.github/workflows/docs.yml
This PR is trying to fix how we extract and choose the directory on disk to pull into the pages branch. 
N/A
N/A
=> fix: change how we extract docs for publish step

Cargo.lock, LICENSE-3rdparty.csv, deny.toml
Weekly dependency update.
Notable change is `ring` has now moved to another repository as a maintenance fork, so we've dropped our one-off clarification for it in `deny.toml`. We've also fixed an advisory ignore for `opentelemetry_api` since we updated it by switching to a newer version of `lading_payload` a few weeks ago.
N/A
N/A
=> chore: update deps

Cargo.lock, Cargo.toml, LICENSE-3rdparty.csv, lib/saluki-io/src/deser/codec/dogstatsd/mod.rs
This PR updates `nom` to `8.0.0` which had some breaking changes due to how combinators have been restructured. We don't _need_ to upgrade, but I'm curious if we happen to notice anything in the benchmarks due to the changes they've made.
N/A
N/A
=> chore: update to nom v8

.gitlab-ci.yml, .gitlab/build.yml, docker/Dockerfile.datadog-agent
This PR adds a new CI job for building a FIPS-compliant bundled ADP image: `build-converged-adp-image-fips`. This builds off of the previous job we added for building a FIPS-compliant ADP binary, `build-adp-image-fips`.
We were blocked on the source Datadog Agent image having a FIPS-compliant version available, but now that that has happened with v7.63.1/v7.64.0, we can finally proceed. As such, this PR also updates our base Datadog Agent version to v7.64.0 RC3.
N/A
Closes #508.
=> chore: update Datadog Agent base version + add bundled FIPS image

lib/saluki-components/src/destinations/prometheus/mod.rs, lib/saluki-core/src/observability/metrics.rs, lib/saluki-event/src/metric/mod.rs, lib/saluki-event/src/metric/value/mod.rs
This PR is an experiment around emitting internal telemetry histograms as actual histograms in the Prometheus destination. This is in service of #500, in terms of being able to emit histograms that can then be scraped and turned into distributions.
We've done two main things in this PR: change our internal telemetry metrics adapter to spit out histograms instead of distributions, and update the Prometheus destination to support histograms.
The first part was easy, and the vast majority of the PR is related to the Prometheus destination changes. The bulk of the Prometheus changes are around how we define our buckets. I think the code comments explain it well, but essentially...
Most usages of Prometheus encourage specify bucket ranges up front since you likely know the scale of the values …
=> experiment: internal telemetry histograms

.gitlab/release.yml, bin/agent-data-plane/src/main.rs, lib/saluki-app/src/metrics.rs, lib/saluki-metadata/build.rs, lib/saluki-metadata/src/lib.rs
This PR adds a new internal telemetry metric -- `running` -- in the same style as that of the Datadog Agent's `datadog.agent.running`. It is meant to be used after internal telemetry is scraped in order to determine the number of ADP processes running.
We did a little work in `saluki-metadata` in order to determine if a build is a dev build or not, which influences how we build the version tag value used, which is meant to also match closely to the `version` tag on `datadog.agent.running`.
I built and ran ADP locally, and queried the telemetry endpoint, and observed the following metric:
```text
toby@consigliera:~/src/saluki$ curl -s localhost:5102/metrics | grep running
adp__running{version="0.1.0-dev-24cfdd0d"} 1
```
N/A
=> chore: emit a 'running' metric to allow asserting ADP liveness through internal telemetry

.ci/images/general/Dockerfile, .ci/images/general/README.md, .ci/images/general/entrypoint.sh, .gitlab-ci.yml, .gitlab/build.yml, .gitlab/internal.yml, .gitlab/release.yml, docker/Dockerfile.agent-data-plane
This PR adds support for pre-uploading debug symbols from ADP binaries to the profiling backend so that we can ship stripped ADP binaries internally and not pay for the cost of debug symbols being included.
We've done a few things specifically:
- updated `Dockerfile.agent-data-plane` to additionally include a stripped copy of the ADP binary
- added a new CI job, `upload-adp-debug-symbols`, which uses `datadog-ci elf-symbols upload` to scrape the non-stripped ADP binary for debug symbols and then uploads it to the profiling backend, both for staging and production
- added a new internal CI image -- `general` -- to support the new CI job for uploading the debug symbols, as the existing default "docker" image doesn't have that tooling
We've also additionally fixed a small little spelling …
=> chore: upload debug symbols to profiling backend

Cargo.lock, lib/saluki-health/Cargo.toml, lib/saluki-health/src/lib.rs
This PR adds new internal telemetry to the health registry (`saluki_health::HealthRegistry`) about the status of registered components in order to be able to track changes to component readiness/liveness over time.
We've added two new gauges -- one for readiness, and one for liveness -- as well as a histogram -- for tracking liveness probe response latency -- which are all tagged with `component_id`, which corresponds to the name given when registering the component in the registry.
These metrics correspond to the output given when querying the readiness/liveness API endpoints themselves, and are updated in lockstep.
Built and ran ADP locally, and observed the new metrics as part of the telemetry scrape endpoint:
```text
toby@consigliera:~/src/saluki$ curl -s localhost:5102/metrics | grep …
```
=> enhancement: emit telemetry about registered components in health registry

lib/saluki-components/src/destinations/datadog/metrics/mod.rs, lib/saluki-core/src/topology/interconnect/event_stream.rs
This pr updates the datadog metrics destination to simply grab the next event buffer instead of grabbing all available buffers.
- Closes: #539
=> chore: chunk up the processing of event buffers in datadog metrics destination.

.gitlab/benchmark.yml
Update to the latest SMP version, 0.21.0.
This release has passed SMP's release tests. This repo's SMP experiments will run when this PR is submitted.
This SMP release fixes the memory constraint that required the workaround in https://github.com/DataDog/saluki/pull/462. Lading is now allocated all memory not otherwise allocated to the target (as configured) or the system (2GiB). Runner instances have 16GiB of memory total.
=> chore(ci): update smp to 0.21.0

Cargo.lock, LICENSE-3rdparty.csv, deny.toml, license-tool.toml
Two parts:
- update dependencies (simple)
- fix our `cargo-deny` configuration to compensate for two recent RUSTSEC advisories that we would dispute as being not relevant to us
- `paste` is now "unmaintained", but it's been stable basically since it was created, so who cares?
- `protobuf` has an issue related to uncontrolled recursion when decoding payloads, but we only use it for _encoding_ payloads, and never for decoding
N/A
N/A
=> chore: update deps and fix cargo-deny config

Cargo.toml, lib/saluki-components/src/destinations/datadog/metrics/request_builder.rs, lib/saluki-io/src/buf/chunked.rs, lib/saluki-io/src/compression.rs
Add support for zstd compression of metric payloads and make it the default behavior to match the Agent.
This required a change to how our chunked buffers accept writes, as we were seeing some deadlock-like behavior with the previous implementation that waited to collect the full capacity for each write. This PR changes that to write as much as it can to the available buffers, even if that is not the full amount, and allow the rest to be written on subsequent calls.
AGTMETRICS-56
=> enhancement: use zstd by default for metric payloads

lib/saluki-io/src/net/util/middleware/mod.rs, lib/saluki-io/src/net/util/middleware/retry_circuit_breaker.rs, lib/saluki-io/src/net/util/mod.rs, lib/saluki-io/src/net/util/retry/mod.rs
This PR implements a new Tower middleware, `RetryCircuitBreaker`. It is designed to help mimic the retry behavior used in the Datadog Agent which involves a blend of both traditional retry behavior (try again after a period of time) and circuit breaker behavior (all requests made while the circuit is open will fail).
Currently, we use the generic retry middleware provided in the `tower` crate, but this comes with a particular downside: requests have to proceed sequentially, and one request being stuck blocks all other requests behind it. The Datadog Agent will intentionally divert additional incoming requests to a "retry queue" when a worker is fully saturated, and when a given endpoint is currently being backed off due to a previous error(s). This is hard to accomplish as-is with the …
=> enhancement: add `RetryCircuitBreaker` middleware

Cargo.lock, lib/saluki-components/Cargo.toml, lib/saluki-components/src/destinations/datadog/common/config.rs, lib/saluki-components/src/destinations/datadog/common/io.rs, lib/saluki-components/src/destinations/datadog/common/mod.rs, lib/saluki-components/src/destinations/datadog/common/retry.rs, lib/saluki-components/src/destinations/datadog/common/telemetry.rs, lib/saluki-components/src/destinations/datadog/common/transaction.rs, lib/saluki-components/src/destinations/datadog/events_service_checks/mod.rs, lib/saluki-components/src/destinations/datadog/metrics/mod.rs, lib/saluki-io/src/buf/chunked.rs, lib/saluki-io/src/buf/vec.rs, lib/saluki-io/src/net/client/http/client.rs, lib/saluki-io/src/net/util/http.rs, lib/saluki-io/src/net/util/middleware/mod.rs, lib/saluki-io/src/net/util/middleware/retry_circuit_breaker.rs, lib/saluki-io/src/net/util/mod.rs, lib/saluki-io/src/net/util/retry/mod.rs, lib/saluki-io/src/net/util/retry/queue/mod.rs, lib/saluki-io/src/net/util/retry/queue/persisted.rs
This PR adds full retry support for Datadog destinations, matching the behavior of the Datadog Agent.
When we talk about "retries" in the Datadog Agent, we're talking about the retrying of HTTP transactions sent by the "forwarder", which is used for sending metric, event, and service check payloads. Despite what might be commonly assumed to be "retry support", the Datadog Agent has a somewhat different spin on retries:
- all transactions (requests) sent to a forwarder first enter the "high priority" queue which is drained by a configurable number of "workers" (tasks that only care about driving the HTTP requests themselves)
- workers also drain transactions from a "low priority" queue, while giving preference to draining all high priority transactions first
- when a transaction fails in a …
=> enhancement: wire up support for retry queue w/ high vs low priority semantics for DD destinations

test/smp/regression/dogstatsd/cases/dsd_uds_100mb_250k_contexts/experiment.yaml, test/smp/regression/dogstatsd/cases/dsd_uds_100mb_3k_contexts/experiment.yaml, test/smp/regression/dogstatsd/cases/dsd_uds_100mb_3k_contexts_distributions_only/experiment.yaml, test/smp/regression/dogstatsd/cases/dsd_uds_10mb_3k_contexts/experiment.yaml, test/smp/regression/dogstatsd/cases/dsd_uds_1mb_3k_contexts/experiment.yaml, test/smp/regression/dogstatsd/cases/dsd_uds_1mb_3k_contexts_dualship/experiment.yaml, test/smp/regression/dogstatsd/cases/dsd_uds_1mb_50k_contexts/experiment.yaml, test/smp/regression/dogstatsd/cases/dsd_uds_1mb_50k_contexts_memlimit/experiment.yaml, test/smp/regression/dogstatsd/cases/dsd_uds_40mb_12k_contexts_40_senders/experiment.yaml, test/smp/regression/dogstatsd/cases/dsd_uds_500mb_3k_contexts/experiment.yaml, test/smp/regression/dogstatsd/cases/dsd_uds_512kb_3k_contexts/experiment.yaml, test/smp/regression/dogstatsd/cases/quality_gates_idle_rss/experiment.yaml, test/smp/regression/dogstatsd/config.yaml, test/smp/regression/saluki/cases/dsd_uds_100mb_250k_contexts/experiment.yaml, test/smp/regression/saluki/cases/dsd_uds_100mb_3k_contexts/experiment.yaml, test/smp/regression/saluki/cases/dsd_uds_100mb_3k_contexts_distributions_only/experiment.yaml, test/smp/regression/saluki/cases/dsd_uds_10mb_3k_contexts/experiment.yaml, test/smp/regression/saluki/cases/dsd_uds_1mb_3k_contexts/experiment.yaml, test/smp/regression/saluki/cases/dsd_uds_1mb_3k_contexts_dualship/experiment.yaml, test/smp/regression/saluki/cases/dsd_uds_1mb_50k_contexts/experiment.yaml, test/smp/regression/saluki/cases/dsd_uds_1mb_50k_contexts_memlimit/experiment.yaml, test/smp/regression/saluki/cases/dsd_uds_40mb_12k_contexts_40_senders/experiment.yaml, test/smp/regression/saluki/cases/dsd_uds_500mb_3k_contexts/experiment.yaml, test/smp/regression/saluki/cases/dsd_uds_50mb_10k_contexts_no_inlining/experiment.yaml, test/smp/regression/saluki/cases/dsd_uds_50mb_10k_contexts_no_inlining_no_allocs/experiment.yaml, test/smp/regression/saluki/cases/dsd_uds_512kb_3k_contexts/experiment.yaml, test/smp/regression/saluki/cases/quality_gates_idle_rss/experiment.yaml, test/smp/regression/saluki/config.yaml
This PR does two things:
- fixes oversized allotments made by the `dogstatsd` experiments, which caused those experiments to fail to each launch
- moves the top-level allotments to the experiment-level for `saluki`, which will silence some warnings about top-level allotment configuration being deprecated
N/A
N/A
=> fix: move lading CPU/memory allotment config to each experiment

lib/saluki-components/src/destinations/datadog/common/io.rs, lib/saluki-components/src/destinations/datadog/common/telemetry.rs, lib/saluki-components/src/destinations/datadog/common/transaction.rs, lib/saluki-io/src/net/util/retry/mod.rs, lib/saluki-io/src/net/util/retry/queue/mod.rs, lib/saluki-io/src/net/util/retry/queue/persisted.rs
This PR adds the ability to flush `RetryQueue<T>`, and subsequently wires that up in both `PendingTransactions<T>` and the endpoint I/O task once shutdown has been triggered. This has the effect that any remaining pending transactions will attempt to flush to the low-priority queue (`RetryQueue<T>`), and the low-priority queue will attempt to flush them to disk if disk persistence is configured.
However, one notable aspect is that we do not yet have disk persistence configuration exposed, so Datadog destinations can't actually enable disk persistence yet.
Added simple unit tests to verify basic behavior. Performed additional local to ensure that when a Datadog destination shuts down, it flushes all outstanding high-priority transactions to the low-priority queue, and then the low-priority …
=> enhancement(datadog): flush pending transactions to retry queue on I/O shutdown

.ci/images/smp/Dockerfile, .gitlab-ci.yml, .gitlab/benchmark.yml, test/smp/configure-smp-aws-credentials.sh
SMP expects that all target images are sourced from their SMP-specific ECR instance, and SMP runners are configured with this expectation. This causes issues when trying to use a _public_ ECR-based target image, as the authentication implicitly happening in the context of the SMP ECR instance causes errors when talking to a public ECR instance.
We've simply added a new job that mirrors the `dogstatsd` images from the public ECR instance to the SMP-specific ECR instance before running the DSD regression experiments.
N/A
N/A
=> fix(ci): mirror dogstatsd image to SMP ECR for regression tests

.gitlab/release.yml
During a refactor in #575, we deduplicated and hoisted up a number of common variables to the global level, requiring them to be used in `extends` for dependent jobs. We missed a spot where these needed to be used in `extends` in our release jobs: while we refactored everything in that area which _depends_ on these variables, we simply missed importing the variables themselves. :)
This ultimately results in a [job](https://gitlab.ddbuild.io/DataDog/saluki/-/jobs/866895817) which reports an empty `FROM` directive, and that job fails. Doh!
N/A
N/A
=> fix(ci): extend release job definition to access common image tags

.gitlab-ci.yml, lib/saluki-components/src/sources/dogstatsd/mod.rs, lib/saluki-core/src/topology/interconnect/event_buffer.rs, lib/saluki-core/src/topology/interconnect/mod.rs
This PR introduces a change to avoid DogStatsD stream handlers from always acquiring an event buffer when starting. It's accompanied by a new helper primitive, `EventBufferManager`, which is designed to encapsulate the necessary logic for acquiring event buffers on demand and returning them when full.
Overall, this change fixes a real problem encountered under high metrics volume load coupled with a decently high number of DSD clients. Overall, the DSD stream handlers, and most components, acquire their event buffers from the "global" event buffer pool, created as part of the topology and shared with each component. This pool is elastic and designed to support a high metrics volume... so long as event buffers are being released promptly.
Normally, this works fine, as components will …
=> fix(dogstatsd): don't acquire event buffer in stream handler until needed

lib/saluki-components/src/sources/dogstatsd/mod.rs, lib/saluki-components/src/sources/dogstatsd/origin.rs, lib/saluki-components/src/sources/dogstatsd/resolver.rs, lib/saluki-context/src/resolver.rs
This PR introduces the ability to disable caching of contexts in `ContextResolver` and updates the DogStatsD source to use a dedicated context resolver for pre-aggregated metrics.
Normally, all incoming metrics would have their contexts resolved through `ContextResolver`, whether the metrics need to be aggregated or not. This means that we always pay the cost of caching the context of pre-aggregated metrics, and holding the context until it hits idle expiration (or not), when the value of caching such contexts is drastically less than non-aggregated metrics, due to their far more infrequent emissions.
Overall, this can lead to a large amount of memory usage (and the resulting permanent growth of the cache data structures) that we should be able to more aggressively reclaim.
This PR adds …
=> experiment(dsd): dedicated non-caching context resolver for no-agg DSD metrics

lib/saluki-components/src/transforms/host_tags/mod.rs
This pr introduces a couple of changes to make the host tags transform more efficient.
- Using `&str` instead of `String` for tags
- Using `with_idle_context_expiration` with the `self.expected_tags_duration`
- Dropping the resolver and host tags when `self.expected_tags_duration` has elapsed.
Closes: #596
=> chore: set expiration on host tags transform resolver

lib/saluki-components/src/sources/dogstatsd/io_buffer.rs, lib/saluki-components/src/sources/dogstatsd/mod.rs
The DogStatsD source uses a fixed-size object pool to hold I/O buffers, which are used by each stream handler (async task that drives each DSD connection) to read data in before framing, decoding, and forwarding take place. As this object pool is fixed-size, this means that when the pool is empty, subsequent calls to acquire an item from the pool will effectively block until an item is released back to the pool.
When the number of DSD connections (one per client for UDS stream, and up to two "fixed" connections for UDP and/or UDS datagram) exceeds the number of I/O buffers available in the pool, new connections will block on trying to acquire their I/O buffer, unable to perform any socket reads at all. This is problematic on its own -- clients aren't sending the data they want to send -- …
=> fix(dogstatsd): release I/O buffers when empty to allow for fairness in acquisition when oversubscribed

lib/saluki-components/src/destinations/datadog/metrics/mod.rs, lib/saluki-components/src/destinations/datadog/metrics/request_builder.rs, lib/saluki-io/src/compression.rs
Adds the `serializer_compressor_kind` and `serializer_zstd_compressor_level` configuration options that are supported by the datadog agent.
Existing unit tests and also sending metrics and making sure everything still works
- Closes: #556
=> chore: allow configuration of compression type and level

.gitlab-ci.yml, Cargo.lock, LICENSE-3rdparty.csv, bin/correctness/airlock/Cargo.toml, lib/saluki-components/src/sources/dogstatsd/io_buffer.rs, lib/saluki-components/src/sources/dogstatsd/mod.rs
This PR adds a small optimization that avoids releasing and re-acquiring the I/O buffer for connectionless streams.
Essentially, connectionless streams (UDP and UDS datagram) don't have the benefit of spreading their metrics volume across multiple tasks like UDS stream does... which means the overhead of processing -- everything before and after the socket read itself in the core I/O loop -- has an impact to how much we can process over those sockets. This means that in high PPS (packets per second) scenarios with UDP/UDS datagram, additional overhead can be the difference between handling all incoming packets or potentially causing clients to drop when they hit write timeouts, and so on.
This PR additionally does two things:
- updates the base Datadog Agent image to 7.65.0 RC9 to ensure …
=> perf(dogstatsd): retain I/O buffer for connectionless streams to reduce overhead

lib/saluki-common/src/collections.rs, lib/saluki-common/src/hash.rs, lib/saluki-context/src/hash.rs, lib/saluki-context/src/resolver.rs
This PR switches our context-oriented hash map/set usage to use a new "noop" hash implementation in order to avoid duplicate hashing.
For contexts, we always hash our "context key" (hash of metric name, tags, and origin info) as part of resolving a context. This means a context key is itself the hash value, and hashing that value _again_ when storing `ContextKey` (or the raw `u64` hash value) in a hash map or set is... wasteful.
We've introduced a new hash implementation, `NoopU64Hasher`, that is meant to be used in these cases: instead of legitimately hashing a value, it simply waits for the value-being-hashed to pass the `u64` hash value and then holds that and returns it as the hash value.
We've also updated our hash set creation for our "hash seen buffer" to pre-allocate capacity to …
=> enhancement(context): switch to noop hasher for maps/sets with prehashed keys

lib/saluki-context/src/expiry.rs, lib/saluki-context/src/resolver.rs
This PR removes the generic key parameter used in `Expiration` and `ExpiryCapableLifecycle` and hard-codes the usage of `ContextKey`, as it's all we currently used and `ContextResolver` doesn't actually support using a different context key type.
We've additionally switched over to using the no-op hash map impl for the expiration state as mentioned in #608, we're already dealing with pre-hashed values (`ContextKey`) so there's no good reason to hash it _again_.
Utilized existing unit tests and the correctness test harness.
N/A
=> refactor(context): de-genericify the expiration logic

Cargo.lock, bin/agent-data-plane/src/main.rs, lib/saluki-common/src/lib.rs, lib/saluki-common/src/strings.rs, lib/saluki-components/Cargo.toml, lib/saluki-components/src/transforms/chained/mod.rs
This PR updates the Chained transform to use a new string identifier format for subtransforms -- `<index>_<name>` -- to improve the resulting internal telemetry that is generated for each subtransform.
Callers must now provide a name when adding a subtransform, and this name is sanitized to lowercase ASCII alphanumeric (and underscores), and then used to form the string identifier. This means that instead of seeing metrics with a component ID tag like `topology.components.transforms.enrich.subtransform_0`, we now get something like `topology.components.transforms.enrich.0_host_enrichment`. The `host_enrichment` portion can be trivially searched for in the codebase, and in most cases, it will likely be indicative enough on its own without the need to search.
Built and run ADP locally, and …
=> chore(chained): require name for each subtransform to improve internal telemetry

.cargo/config.toml, Cargo.lock, Cargo.toml, LICENSE-3rdparty.csv, bin/agent-data-plane/Cargo.toml, bin/agent-data-plane/src/main.rs, lib/saluki-app/Cargo.toml, lib/saluki-app/src/memory.rs
This PR introduces support for collecting heap profile dumps from `jemalloc`, allowing for more in-depth memory profiling on live ADP processes without having to first instrument the binary or run it under a memory profiler.
This enables heap profiling by default, with a sampling interval of 512KiB (collect profile data every 512KiB worth of allocations). A new privileged API endpoint is exposed at `/debug/pprof/heap` for collecting the pprof-formatted heap profiles.
Non-Linux builds will still expose the API endpoint, but will return an error response indicating that heap profiling is not available.
N/A
N/A
=> enhancement(observability): expose ability to capture jemalloc heap profiles in pprof format from admin API

lib/saluki-components/src/destinations/prometheus/mod.rs
This PR attempts to split the set of histogram buckets we generate in the Prometheus destination into two groups: time-based and non-time-based.
We're working off the knowledge that for time-based histograms (which we define as metrics with names ending in `_seconds`), we can optimize the buckets to allow us to gain enhanced precision in the subsecond range since those values rarely reach multiple seconds. When dealing with non-time-based histograms, we use a shifted range that is designed for whole integer-like values (1 and greater) which is everything we currently emit histograms for that are not time-based.
This is all a bit hard-coded around how we use histograms for internal telemetry, so in the long term, we should probably explore something else... or just finally go all in with …
=> enhancement(prometheus): better bucket ranges for time vs non-time-based histograms

lib/saluki-core/src/components/destinations/context.rs, lib/saluki-core/src/components/sources/context.rs, lib/saluki-core/src/components/transforms/context.rs, lib/saluki-core/src/topology/built.rs, lib/saluki-core/src/topology/running.rs
This PR adds a global asynchronous thread pool, backed by `tokio`, which is exposed to components in the topology for any necessary usages.
This is part of a stack for trying to build Datadog Metrics requests off the primary runtime so as to reduce the amount of synchronous code (Protocol Buffers encoding, compression) executing inline with receiving events, which could lead to elevated tail latencies in serving other tasks on the primary runtime.
For now, we're using a fixed number of worker threads -- eight -- as we don't expect there to be a massive number of concurrent tasks, but do still want some small level of concurrency.
N/A
N/A
=> experiment: generic async thread pool

lib/saluki-components/src/destinations/datadog/metrics/mod.rs, lib/saluki-core/src/task.rs, lib/saluki-core/src/topology/built.rs
This PR updates the Datadog Metrics destination to move request building to the global thread pool, in an attempt to reduce the amount of synchronous code (Protocol Buffers encoding, compression) happening on the primary runtime.
Our hypothesis is that by doing so, we can greatly reduce the tail latency of other tasks on the primary runtime, such as socket handler tasks, and in doing so, improve the client-perceived latency of interacting with ADP.
N/A
N/A
=> experiment(datadog metrics): build requests on global thread pool

.gitlab/build.yml
In CI, we use the `emit-build-metadata` Make target to generate the "build metadata" that gets bundled into the ADP binary: build data, short/full name of the binary, and so on. We were incorrectly passing the "full name" to the relevant Docker build step (`APP_FULLNAME` instead of `APP_FULL_NAME`), leading to the default value of `unknown` being used.
This manifests as showing a name of `unknown` when ADP connects to the Core Agent's "Remote Agent Registry", as well as a User Agent of `unknown/0.1.0` when sending outbound HTTP requests, and so on.
Will require waiting for CI to build an image that we can test locally.
N/A
=> fix(ci): pass proper env var for ADP binary 'full name' value

.gitlab/build.yml
We've recently introduced, in our GitLab, automatic injection of the OTEL exporter configuration when explicitly enabled via the `DDCI_CONFIGURE_OTEL_EXPORTER` environment variable. When enable it provides end-to-end observability for container image builds.
This will allow us to measure the impact for the upgrade of instance generation for our Buildkit ARM workers.
Selected [build-adp-image](https://gitlab.ddbuild.io/DataDog/saluki/-/jobs/906482197) job from this PR and find the corresponding trace: [`env:prod` `service:buildx` `resource_name:build` `@ci.job.id:906482197`](https://app.datadoghq.com/apm/traces?query=env%3Aprod%20service%3Abuildx%20resource_name%3Abuild%20%40ci.job.id%3A906482197&agg_m=count&agg_m_source=base&agg_t=count&cols=core_service%2Ccore_resource_name%2Clog_duration …
=> chore(ci): enable OpenTelemetry Exporter configuration injection

bin/agent-data-plane/src/internal/control_plane.rs, bin/agent-data-plane/src/internal/mod.rs, bin/agent-data-plane/src/internal/observability.rs, bin/agent-data-plane/src/internal/remote_agent.rs, bin/agent-data-plane/src/main.rs, bin/agent-data-plane/src/state/metrics.rs, lib/memory-accounting/src/registry.rs, lib/saluki-app/src/lib.rs, lib/saluki-app/src/logging.rs, lib/saluki-app/src/memory.rs, lib/saluki-app/src/metrics.rs, lib/saluki-config/src/lib.rs, lib/saluki-core/src/topology/blueprint.rs, lib/saluki-core/src/topology/built.rs
This PR reorganizes some of the "internal", non-data pipeline-oriented aspects of the ADP binary to better isolate their behavior from one another. This is meant to ensure that issues/degradation in the primary topology don't negatively impact the control plane, such as by preventing internal telemetry from being scraped due to topology stalls, as well as isolate the primary topology from control plane computation, such as high duration task polls which can drive up tail latency for sensitive tasks (like DogStatsD I/O handlers).
Specifically, we now isolate internal processes -- (un)privileged APIs, health registry, internal telemetry pipeline, etc -- within dedicated current-thread async runtimes. This lets us keep our existing code and utilize existing paradigms, but simply isolates the …
=> enhancement: move internal telemetry/APIs/etc to dedicated runtimes for isolation

.gitlab/build.yml
This PR updates our build job to also sign (via `ddsign`) our "regular" ADP container images in addition to our converged images. This will allow us to run standalone ADP images via the Operator's per-container image override support.
N/A
N/A
=> chore(ci): sign regular ADP container images, not just converged ones

.ci/templates/generate-result-links-markdown.sh, .gitignore, .gitlab-ci.yml, .gitlab/benchmark.yml, Cargo.lock, Cargo.toml, Makefile, bin/checks-agent/Cargo.toml, bin/checks-agent/src/env_provider.rs, bin/checks-agent/src/main.rs, docker/Dockerfile.checks-agent, lib/saluki-components/src/sources/heartbeat/mod.rs, lib/saluki-components/src/sources/mod.rs, test/smp/regression/checks-agent/cases/quality_gates_idle_rss/experiment.yaml, test/smp/regression/checks-agent/cases/quality_gates_idle_rss/lading/lading.yaml, test/smp/regression/checks-agent/config.yaml
This PR introduces the new agent binary `checks-agent`. During the last quarter, the Agent Runtimes worked on extracting the checks outside of the main Agent. This effort was part of an exploration of finding the next Agent architecture that allows us to scale without increasing our customers' operational cost. The end result was that the overhead of extracting separate parts of the Agent into Go processes was not feasible due to the overhead. More importantly, the lack of fine-grained control within Go (garbage-collected language). You can read more about it [here](https://docs.google.com/document/d/1L9Sftu_cPDDYWazBNpR87zqsqhLY3zKp32byjPjDMGg/edit?pli=1&tab=t.3miccnxavpy2). 
We are going to explore the possibility of using Rust and the Saluki framework to extract functionality from the …
=> [AGENTRUN-221] chore(checks-agent): create initial `checks-agent` binary

.ci/templates/generate-result-links-markdown.sh, .gitlab/benchmark.yml, test/smp/regression/checks-agent-go/cases/quality_gates_idle_rss/checks-agent-go/conf.d/disk.d/conf.yaml.default, test/smp/regression/checks-agent-go/cases/quality_gates_idle_rss/checks-agent-go/datadog.yaml, test/smp/regression/checks-agent-go/cases/quality_gates_idle_rss/experiment.yaml, test/smp/regression/checks-agent-go/cases/quality_gates_idle_rss/lading/lading.yaml, test/smp/regression/checks-agent-go/config.yaml
This PR benchmarks the Go version of the checks agent https://github.com/DataDog/datadog-agent/pull/31571 using SMP. We mirror the image created in the PR to the SMP ECR. Since the PR has few changes, we use the same commit as the baseline and comparison.
We updated the links generated to use the Go version as the comparison for the SMP dashboard. 
In a following PR, we might create a different dashboard just to focus on check agent comparison
=> [AGENTRUN-227] chore(checks-agent): compare check-agent in Go against Rust version

lib/saluki-components/src/transforms/dogstatsd_mapper/mod.rs
This pr adds an expiration to the DogstatsD mapper transform that matches that of the DogStatsD source.
N/A
- Closes: #600
=> chore: enable context expiration for the DogstatsD mapper transform

.cargo/config.toml, Cargo.lock, Cargo.toml, LICENSE-3rdparty.csv, bin/agent-data-plane/Cargo.toml, bin/agent-data-plane/src/internal/control_plane.rs, bin/checks-agent/Cargo.toml, lib/saluki-app/Cargo.toml, lib/saluki-app/src/memory.rs
We added the capability to export jemalloc heap profile data in a pprof format in #427, planning to use this to power runtime memory profiling in staging/production. However, this addition (even when not actually _used_) seems to have broken our profiling capabilities (via `ddprof`) in our benchmark/regression testing.
This PR simply removes our addition of jemalloc heap profiling to get `ddprof` working again. We plan on addressing runtime memory profiling in a different way.
N/A
AGTMETRICS-184
=> chore(app): remove jemalloc heap profiling capabilities

bin/agent-data-plane/src/main.rs, lib/saluki-components/src/destinations/datadog/common/config.rs, lib/saluki-components/src/destinations/datadog/common/endpoints.rs, lib/saluki-components/src/destinations/datadog/metrics/mod.rs, lib/saluki-components/src/destinations/datadog/metrics/request_builder.rs, lib/saluki-components/src/transforms/host_tags/mod.rs, lib/saluki-components/src/transforms/mod.rs, lib/saluki-components/src/transforms/preaggregation_filter/mod.rs, lib/saluki-core/src/topology/interconnect/event_buffer.rs
Replacement for #634 and #635 after some helpful discussion with @tobz.
Things still to figure out:
TPOT-19
=> feat: add option to dual ship to preaggr pipeline

Cargo.lock, Cargo.toml, LICENSE-3rdparty.csv, lib/saluki-components/src/destinations/datadog/common/io.rs, lib/saluki-components/src/destinations/datadog/common/retry.rs, lib/saluki-io/Cargo.toml, lib/saluki-io/src/net/util/retry/mod.rs, lib/saluki-io/src/net/util/retry/queue/mod.rs, lib/saluki-io/src/net/util/retry/queue/persisted.rs
This pr adds a configuration option for `forwarder_storage_max_disk_ratio`. 
This is used to compute the maximum bytes that are allowed to be stored on disk which follows the[ algorithm used in the datadog-agent here](https://github.com/DataDog/datadog-agent/blob/main/comp/forwarder/defaultforwarder/internal/retry/disk_usage_limit.go#L41-L50)
The configuration options for `forwarder_storage_path` and `forwarder_storage_max_size_in_bytes` were missing so we added those as well.
This pr also enable disk persistence if `forwarder_storage_max_size_in_bytes > 0` 
New unit test
- Closes: #626
=> enhancement: implement support for restricting retry disk buffer usage when disk usage exceeds a configurable threshold

lib/saluki-components/src/destinations/datadog/common/config.rs, lib/saluki-components/src/destinations/datadog/common/endpoints.rs, lib/saluki-components/src/destinations/datadog/metrics/mod.rs
The new pipeline endpoint is only available at `api.`, so we need to adjust the subdomain of the additional forwarder.
TPOT-19
=> fix: adjust preaggr subdomain to always be api

lib/saluki-env/src/workload/entity.rs
This PR fixes a bug with the parsing of raw container IDs into `EntityId`.
Prior to this PR, we only handled the special case of raw container IDs being prefixed with `in-`, which indicated that the remainder of the raw container ID was actually an inode value, pointing at the cgroup controller for the container from which a metric originated. However, newer DogStatsD clients can send their container ID with a `ci-` prefix, so without special handling, we were treating the entire `ci-<long hexadecimal string>` value as a container ID, leading to failure to properly enrich metrics with origin tags.
We've added proper handling of this raw container ID prefix, as well as unit tests to ensure we handle it and that we don't regress in the future.
Added unit tests to ensure the container ID …
=> fix(entity): properly handle raw container IDs with `ci-` prefix

lib/saluki-components/src/transforms/host_tags/mod.rs
This PR simply updates the Host Tags transform to avoid allocating a backing vector to hold the combined set of tags used when resolving the updated context. Instead, we emulate the approach used by the DogStatsD source which is to simply used a chained iterator: this iterator can be cloned as required by `ContextResolver::resolve_with_origin_tags` and avoids any intermediate allocations.
This is particularly relevant for the pre-aggregation mode where we're constantly enriching with host tags, as even if the resulting context is cached, we're still allocating a `Vec<&str>` to hold them all before resolving.
Unit tests.
AGTMETRICS-184
=> enhancement(host_tags): don't allocate vector to hold tags before resolving

lib/saluki-components/src/destinations/datadog/common/mod.rs, lib/saluki-components/src/destinations/datadog/common/request_builder.rs, lib/saluki-components/src/destinations/datadog/metrics/request_builder.rs, lib/saluki-io/src/compression.rs, lib/saluki-io/src/net/util/retry/queue/mod.rs
This PR introduces an updated/refactored version of `RequestBuilder<O>` (from the Datadog Metrics destination) that is meant to be shared amongst all Datadog destinations. This refactored version allows for the encoding logic (among other things) to be pluggable using a new trait, `EndpointEncoder`.
The general idea is that each destination will implement the trait to define what the endpoint URI for payloads should be, how to encode each individual event that gets pushed into the request builder, the content type, size limits, and so on. `RequestBuilder<E, O>` then becomes responsible for the generic logic of managing compression, compression buffers, request splitting, and request building.
This is in preparation of cutting over the Datadog Events/Service Checks destination to use the …
=> chore(datadog): refactor `RequestBuilder<O>` to be trait-driven to allow reuse between destinations

lib/saluki-components/src/destinations/datadog/metrics/mod.rs, lib/saluki-components/src/destinations/datadog/metrics/request_builder.rs
This PR refactors the Datadog Metrics destination to use the new generic `RequestBuilder<E, O>` by implementing a `MetricsEndpointEncoder` that handles both series and sketch metrics. It is mostly a lift and shift of the existing metrics-specific logic in `RequestBuilder<O>`, just wrapped up in the `EndpointEncoder` trait.
Unit tests and local testing.
AGTMETRICS-184
=> chore(datadog): refactor metrics destination to use new generic request builder

lib/saluki-components/src/destinations/datadog/common/request_builder.rs, lib/saluki-components/src/destinations/datadog/metrics/mod.rs, lib/saluki-io/src/compression.rs
This PR adds support for delimited payloads to `RequestBuilder<E, O>`.
In the case of the Datadog Metrics destination, individual inputs are self-delimiting by virtue of being elements in a repeated message field in the Protocol Buffers payload. This means that while the request itself is a single message with N inputs bundled into it, and not N messages, we still don't have to do anything special to wrap those inputs or separate them: just write them individually, concatenated, and the payload is valid.
However, for other destinations, like Datadog Events/Service Checks, the payloads are JSON arrays. This means that the payload has a prefix and suffix (`[` and `]`) and each input needs to be separated by a comma. Naturally, you get this when encoding an array of values all at once, but …
=> chore(datadog): add support for writing delimited payloads to `RequestBuilder<E, O>`

Cargo.lock, Cargo.toml, LICENSE-3rdparty.csv, lib/saluki-env/src/workload/helpers/containerd/events.rs
This PR includes a general deps update. We updated `containerd-client` as well, which required a small code change.
Ran unit tests locally.
AGTMETRICS-233
=> chore(deps): dep updates

Cargo.lock, Cargo.toml, LICENSE-3rdparty.csv, lib/saluki-common/Cargo.toml, lib/saluki-common/src/hash.rs
We already maintain an opaque "fast" hasher, meant specifically for high-performance hashing (hashmaps, and so on) where the stability of the hash output for a given input does not need to hold across process restarts or releases, and the underlying implementation is free to be changed between releases. However, we have a need to be able to hash a particular input in a stable way such that the resulting hash stays the same across restarts and releases, such as when adding a hash component to a file path.
This PR introduces `StableHasher` to provide this. `StableHasher` is based on SHA-3 (specifically, SHAKE128) which is a standardized cryptographic hash algorithm, which means the generated output is always stable with respect to identical inputs, and it can be recreated in other …
=> enhancement(common): add stable hash function for restart-safe hashes

lib/saluki-components/src/transforms/preaggregation_filter/mod.rs, lib/saluki-core/src/topology/interconnect/event_buffer.rs, lib/saluki-event/src/eventd/mod.rs, lib/saluki-event/src/lib.rs, lib/saluki-event/src/service_check/mod.rs
This PR adds a new method, `remove_if`, to `FixedSizeEventBuffer`, that allows for removing specific events when they aren't needed any longer. The previous best way to accomplish this -- `extract` -- was inefficient for that usage as it involved intermediate allocations to do so.
We've updated the Preaggregation Filter transform to take advantage of this new method, and we also fixed up both methods to properly update the "seen" data types for `FixedSizeEventBuffer`, and updated the unit tests to account for that as well.
Unit tests.
AGTMETRICS-233
=> enhancement(core): add `remove_if` method to `FixedSizeEventBuffer` for efficient removal

lib/saluki-components/src/sources/dogstatsd/origin.rs, lib/saluki-context/src/origin.rs, lib/saluki-env/src/workload/entity.rs, lib/saluki-env/src/workload/mod.rs, lib/saluki-env/src/workload/on_demand_pid.rs, lib/saluki-env/src/workload/origin.rs, lib/saluki-env/src/workload/providers/remote_agent/mod.rs, lib/saluki-env/src/workload/stores/tag.rs
When resolving a metric context, we factor in a number of pieces of information: metric name, instrumented tags (provided with the metric), and the _origin_ of the metric. Origin relates to the actual application sending the metric, such that we can correlate the metric with a specific container or Kubernetes pod. Doing this origin detection allows us to automatically enrich metrics with additional "origin tags" related to the entity identifiers we detect, such as pod-specific tags when we can detect the Kubernetes pod a metric originated from, or the container-specific tags when we can detect the container, and so on.
Doing all of this work every time we receive a metric would be very costly, and so we take a number of steps to attempt to allow quickly determining if we have a cached …
=> fix(origin): don't consider process ID directly when calculating origin key

test/smp/regression/saluki/cases/dsd_uds_1mb_50k_contexts_memlimit/experiment.yaml, test/smp/regression/saluki/cases/dsd_uds_50mb_10k_contexts_no_inlining/experiment.yaml, test/smp/regression/saluki/cases/dsd_uds_50mb_10k_contexts_no_inlining_no_allocs/experiment.yaml
The recent changes to split the Datadog Events/Service Checks destination into two destinations, and to have them use the same buffer pool architecture as the Datadog Metrics destination, has altered the calculated maximum bounds which affects a select number of SMP tests.
This PR is a temporary bump in those bounds to get these tests passing again.
N/A
AGTMETRICS-233
=> chore(ci): bump memory limit for some SMP tests to account for recent changes

lib/saluki-components/src/destinations/datadog/metrics/mod.rs
Fixes two small oversights from the preaggregation work, will hopefully help get clearer per-endpoint metrics.
TPOT-79
=> fix: cleanup preaggr endpoint override and metrics

.ci/images/build/Dockerfile, .ci/images/general/Dockerfile
With the recent work on the checks-agent binary, we are including the [pyo3](https://pyo3.rs/v0.25.0/getting-started.html) crate. Which means we need to be able to compile it when running tests and other CI tasks. 
On this PR https://github.com/DataDog/saluki/pull/691, we can see that the CI jobs for clippy, format, and tests are failing because we are not able to successfully run cargo due to some mismatch on the Python version:
```
error: the configured Python interpreter version (3.4) is lower than PyO3's minimum supported version (3.7)
```
This PR uses the Python interpreter from the Agent to ensure there are no version mismatches between the checks agent in Saluki and the Coe Agent.
Once merge we would have to trigger the CI job to build the latest ci image
=> Add the Agent Python interpreter to the CI images

Makefile, bun.lock
Adds a new Make target, `run-docs`, for running the Vitepress development server that lets developers preview the repository documentation.
N/A
AGTMETRICS-233
=> chore(docs): add make target for running docs locally, run-docs

lib/saluki-core/src/topology/graph.rs, lib/saluki-core/src/topology/ids.rs, lib/saluki-core/src/topology/test_util.rs
This PR updates `Graph` to support the addition of encoders and forwarders to a topology.
Most of the code is test-related.
Unit tests.
AGTMETRICS-233
=> chore(core): update topology graph to support encoders/forwarders

bin/agent-data-plane/src/components/remapper/mod.rs, lib/saluki-components/src/sources/dogstatsd/mod.rs, lib/saluki-components/src/sources/heartbeat/mod.rs, lib/saluki-components/src/sources/internal_metrics/mod.rs, lib/saluki-components/src/transforms/aggregate/mod.rs, lib/saluki-components/src/transforms/chained/mod.rs, lib/saluki-components/src/transforms/dogstatsd_prefix_filter/mod.rs, lib/saluki-core/src/components/encoders/mod.rs, lib/saluki-core/src/components/sources/context.rs, lib/saluki-core/src/components/transforms/context.rs, lib/saluki-core/src/topology/built.rs, lib/saluki-core/src/topology/interconnect/dispatcher.rs, lib/saluki-core/src/topology/interconnect/mod.rs
This PR renames `Forwarder` in `saluki_core::topology::interconnect` to `Dispatcher`, in order to avoid clashing with the new `Forwarder` component.
N/A
AGTMETRICS-233
=> chore(core): rename `interconnect::Forwarder` to `Dispatcher` to avoid name clash with forwarder component

lib/stringtheory/src/lib.rs
This PR adds support to `MetaString` to abstract over `Arc<str>` by adding a new variant in our tag byte niche. This is a simpler approach when intern-like behavior is required but the number of strings is small, and the use of an interner would be overkill compared to simply creating a few `Arc<str>` instances by hand.
Unit tests.
AGTMETRICS-233
Closes #697
=> enhancement(stringtheory): add new `MetaString` variant for `Arc<str>`-backed strings

lib/saluki-components/src/destinations/datadog/events/mod.rs, lib/saluki-components/src/destinations/datadog/metrics/mod.rs, lib/saluki-components/src/destinations/datadog/service_checks/mod.rs, lib/saluki-components/src/destinations/prometheus/mod.rs
This PR fixes the task name for the spawned request builder tasks in the Datadog destinations. We previously were leaving them without a custom name, so all we were getting was `file-/adp/lib/saluki-common/src/task/mod.rs_133-44`.. which is pretty useless. 😅 (Triply so because we had three different request builder tasks all spawned in the same way!)
While working on this, I realized that we're now generating telemetry payloads large enough in the Prometheus destination to trip the previous default payload buffer limits. I had to bump up the limits to allow all metrics to be processed/emitted. This also means that we were potentially missing telemetry in staging as it would silently give up processing any remaining contexts once the payload buffer limit was reached.
Ran ADP locally and …
=> chore(observability): fix task name for DD destination request builders

.gitlab-ci.yml, .gitlab/benchmark.yml, .gitlab/build.yml, .gitlab/correctness.yml, .gitlab/release.yml, docs/agent-data-plane/releasing.md
This PR does a bunch of reworking to how we tag and publish both our internal images and public images, as well as additionally publishes new "standalone" ADP images.
The new process looks something like this now:
- build the debug ("internal")  and "release" ADP standalone images (internal registry only at this point)
- publish the internal image by building off the debug image and adding the necessary bits (new change here is we now publish a FIPS variant)
- for git tags, trigger the public image publish jobs: bundled variants (Agent + ADP) and standalone (ADP only)
For the public images, we've added additional tag variants. For the bundled image, we publish four variants: base, FIPS, JMX, and JMX/FIPS. For the standalone image, we publish two variants: base and FIPS.
N/A
AGTMETRICS-233
=> chore(ci): rework build/release stages for standalone ADP images + JMX/FIPS variations

Makefile, docker/Dockerfile.agent-data-plane
Our ADP Dockerfile was tailored specifically for Ubuntu 22.04, and so it fails to build in CI where we target 24.04 instead.
Built the ADP container image locally via `make build-adp-image`.
AGTMETRICS-233
=> chore(build): fix ADP dockerfile to install `ca-certificates` for Ubuntu 24.04

.gitlab/release.yml
This PR updates some variable names to match what the standalone ADP image publish jobs were expecting, and brings the variable names in line with other existing variables in the release stage.
N/A
AGTMETRICS-233
=> fix(ci): update variable name to properly drive standalone ADP image publish jobs

.gitlab/release.yml
As stated in the PR title. We had some extra brackets where we shouldn't have them. It breaks the job. 🤷🏻 
N/A
AGTMETRICS-233
=> fix(ci): remove extra brackets in image tag reference for publish jobs

.gitlab/release.yml
This PR _attempts_ to resolve an issue where GitLab CI decides to stop interpolating variables in other variables for some reason, which leads to broken image paths when publishing release artifacts.
N/A
AGTMETRICS-233
=> fix(ci): try to make GitLab CI happy with our variable inclusion approach

.gitlab/release.yml
As our bundled Agent/ADP image rides under the same image repository as the normal Agent (`agent`), we're subject to the same validation rules. This PR adds some missing image labels to the bundled Agent/ADP image in order to try and satisfy said validation rules.
N/A
AGTMETRICS-233
=> fix(ci): add missing image labels for bundled Agent/ADP image to satisfy validation

lib/saluki-components/src/transforms/host_tags/mod.rs, lib/saluki-context/src/hash.rs, lib/saluki-context/src/resolver.rs, lib/saluki-context/src/tags/mod.rs, lib/stringtheory/src/clone.rs, lib/stringtheory/src/lib.rs
This PR updates `ContextResolver` to cheaply clone the name and/or tags of a context, when possible, based on changes to `MetaString` and a new trait, `CheapMetaString`, which exposes the ability to determine when a string value can be cheaply cloned to `MetaString`.
In many cases, components need to re-resolve a metric context as they change the tags or remap the name of a metric. For metric names/tags that can inlined, this is effectively free. However, when the strings cannot be inlined, the context resolver must fallback to either interning or heap allocating the values. This means that even in cases where the original name/tag was static or already interned, we will re-intern it (or worse, heap allocate it), wasting additional capacity for a `MetaString` that was already able to be …
=> enhancement(context): cheaply clone incoming context name/tags where possible

.gitlab-ci.yml, .gitlab/build.yml, .gitlab/release.yml
This PR drops our building/publishing of bundled Agent/ADP images.
It's been a lot of work to try and clean up the CI workflow to build and publish them, and we're still hitting issues with downstream jobs required to publish. Given that the medium-term plan is to use standalone images anyways... I'm just going ahead and ripping out the bundled Agent/ADP images a little sooner.
Also removed some unused variables in `.gitlab-ci.yml`.
N/A
AGTMETRICS-233
=> chore(ci): stop building/publishing bundled Agent/ADP images

lib/saluki-components/src/sources/checks/builder/python.rs, lib/saluki-components/src/sources/checks/mod.rs, test/smp/regression/checks-agent/cases/quality_gates_idle_rss/experiment.yaml, test/smp/regression/checks-agent/cases/quality_gates_rss/experiment.yaml
For our SMP test for the checks agent, we were not correctly setting the config value to read the check config and code. 
[SMP documentation](https://github.com/DataDog/single-machine-performance/blob/main/docs/Regression%20Detector.md#file-based-configuration)
This PR fixes that.
As we can see now, the test `quality_gates_rss` has increased the RSS consumption because it loaded the Python runtime and is running the check.
=> chore(checks-agent) ensure that SMP finds the custom checks folders 

bin/agent-data-plane/src/main.rs, lib/saluki-components/src/destinations/datadog/common/endpoints.rs, lib/saluki-components/src/destinations/datadog/common/request_builder.rs, lib/saluki-components/src/destinations/datadog/metrics/mod.rs
As stated in the PR title. All we really care about is allowing the overriding the API key in addition to the DD URL and request path... but I took this opportunity to try and clean up / generalize this code a little.
Ran ADP locally with the pre-aggregation pipeline enabled:
- ensured that the API key was always required when pre-aggregation is enabled
- ensured that when not specified, the host/path default to `api.datad0g.com` and `/api/intake/pipelines/ddseries`, respectively
- ensured both the host and request path could be overridden from their defaults
AGTMETRICS-233
=> chore(preaggr): refactor how we configure pre-aggregation settings for DD Metrics destination to allow overridding API key as well

bin/agent-data-plane/src/components/remapper/rules/aggregation.rs
This PR has a small update to the resolver ID used for one of the remapper's remapping rules. I missed updating this when updating how we generate resolver IDs in #714... although looking at the code, it was probably broken as far back as #595 when we added the no-aggregation-specific context resolver to the DogStatsD source.
Ran ADP locally and observed that the remapped metrics in question -- `aggregator__dogstatsd_contexts` -- was properly mapped to `adp__context_resolver_active_contexts{resolver_id="dsd_in/dsd/primary"}`
AGTMETRICS-233
=> fix(remapper): update resolver ID tag value for mapping context resolver-based metric

.gitlab/release.yml, Cargo.lock, bin/agent-data-plane/Cargo.toml
This PR does two main things:
- updates the ADP version in `bin/agent-data-plane/Cargo.toml` to sit ahead of our latest tagged release
- tries to update the real CI stage to interpolate the ADP version into the target tag
We currently populate `APP_VERSION` from `bin/agent-data-plane/Cargo.toml`, which then in turn feeds `saluki_metadata` and gets used for things like generating the build information that gets logged on startup, and the User Agent header we send in HTTP requests, and so on. We've been depending on the Git tag itself to determine the version we use for container image tags, but it doesn't get used to populate that build information metadata. This PR unifies those two things, and I'll have a follow-up PR to update the release docs to explain how we'll need to increment the …
=> fix(ci): update ADP version and try to fix weird variable interpolation behavior

.gitlab-ci.yml, .gitlab/build.yml, .gitlab/correctness.yml, .gitlab/release.yml
This PR attempts to fix some of the weirdness with variable interpolation in GitLab CI while simultaneously updating or build jobs to work for either internal (PR branch, etc) or release (tagged release) pipelines.
N/A
AGTMETRICS-233
=> chore(ci): update ADP image build to work for internal or release images

.gitlab-ci.yml
This is attempt 7,312,132 to try and get variables forwarding properly to the publish jobs.
Specifically, what we see right now is that we try and specify the "source image", which is the image we copy from when publishing, to a value of `"${ADP_IMAGE_BASE}:${ADP_IMAGE_VERSION}"`. This should evaluate to something like `registry.ddbuild.io/saluki/agent-data-plane:0.1.10`. However, when the job runs, it ends up as `registry.ddbuild.io/saluki/agent-data-plane:`... so only `ADP_IMAGE_VERSION` is failing to be interpolated, but `ADP_IMAGE_BASE` is fine.
The only difference between those two variables is the `ADP_IMAGE_BASE` comes as a default job variable, and `ADP_IMAGE_VERSION` is computed/added dynamic by `workflow:rules:variables`. This PR is attempting to provide a default job-level …
=> fix(ci): try setting a default for `ADP_IMAGE_VERSION` variable to propagate to publish pipeline jobs

lib/saluki-components/src/destinations/datadog/common/endpoints.rs, lib/saluki-components/src/destinations/datadog/common/io.rs, lib/saluki-components/src/destinations/datadog/events/mod.rs, lib/saluki-components/src/destinations/datadog/metrics/mod.rs, lib/saluki-components/src/destinations/datadog/service_checks/mod.rs, lib/saluki-components/src/sources/dogstatsd/mod.rs, lib/saluki-components/src/transforms/aggregate/mod.rs, lib/saluki-core/src/observability/mod.rs, lib/saluki-core/src/topology/interconnect/dispatcher.rs, lib/saluki-core/src/topology/interconnect/event_stream.rs
This PR updates the way we generate the "queue ID" when using `RetryQueue` for Datadog destinations, which influences the resulting on-disk path used to store transactions that should be retried.
Prior to this PR, the queue ID was simply the endpoint URL for the given endpoint I/O task. This posed two main problems: different endpoint/API key combinations would try and point to the same path on disk, and different Datadog destinations pointed at the same endpoint (like Datadog Metrics and Datadog Events) would also try and point to the same path on disk. This represents a correctness issue with two tasks trying to compete for pulling retry files off disk, and so on. No bueno.
This PR updates the way we generate the queue ID to incorporate the following items:
- component ID
- endpoint URL …
=> chore(datadog): generate a unique retry queue id for component ID/endpoint/API key combination

lib/saluki-components/src/destinations/datadog/common/transaction.rs
This PR fixes a bug with deserialization errors for `TransactionBody<B>` due to an incorrect deserialization configuration.
Prior to this PR, we serialized `TransactionBody<B>` by writing out the body like a `Vec<u8>`, and tried to deserialize it by deferring the deserialization implementation to `From<String> for TransactionBody<B>`. This, naturally, will never work: `Vec<u8>` and `String` are not the same, and `serde` would yell at us when it would try to deserialize such a payload.
This PR simply updates our deferred deserialization implementation to be `Vec<u8>`, matching how the body is serialized, which allows payloads to be properly deserialized.
Built and ran ADP locally prior to this fix, with an invalid endpoint URL and fake load, such that retry files were generated and stored …
=> fix(datadog): use proper deserialize type for `TransactionBody<B>`

lib/saluki-components/src/sources/checks/scheduler.rs
This PR refactors the checks scheduler so it does not lose. Sending checks via sender and receiver is using `send` instead of `try_send` 
We removed the concept of interval channels and assigned each check its own `tokio::task`, which would push a copy of the check to the less loaded worker. This simplifies how the scheduler operates.
=> [AGENTRUN-327] chore(checks-agent) avoid check scheduler to loose checks on full workers 

bin/checks-agent/src/env_provider.rs, bin/checks-agent/src/main.rs
On the previous PR we added support for sending metrics from the Python checks https://github.com/DataDog/saluki/pull/711
This PR modifies the `checks-agent` binary to use the transformers (Aggregation, and Host Enrich) and send the data to the DD metrics intake. 
The aggregation transformer might require some changes to make sure the check metrics are emitted on the right interval. Nevertheless, for our benchmarking work, accuracy is not as important 😄
=> [AGENTRUN-350] chore(checks-agent): remove blackhole destination and use a real destination

lib/saluki-components/src/sources/dogstatsd/origin.rs, lib/saluki-context/src/context.rs, lib/saluki-context/src/origin.rs, lib/saluki-context/src/resolver.rs, lib/saluki-env/src/workload/mod.rs, lib/saluki-env/src/workload/providers/noop.rs, lib/saluki-env/src/workload/providers/remote_agent/mod.rs, lib/saluki-env/src/workload/stores/tag.rs
This PR switches origin enrichment to happen immediately during context resolving instead of in a deferred way.
Currently, origin tags are added to contexts in a split way:
- first, we take the incoming origin information/metadata and store it, getting back a key that can be hashed with the context key and used to actually resolve the relevant origin tags
- during rendering of metrics, we use the origin key to look up those origin tags, and visit them alongside the metric's instrumented tags
This works and is a reasonably performant approach to handling origin tags. However, it poses a major problem when it comes to deterministic resource management: the need to delay when origin tags are expired to ensure that they exist when the tags are eventually visited.
In practice, the upper bound …
=> experiment(context): immediately capture origin tags during context resolving

Cargo.lock, bin/agent-data-plane/Cargo.toml
We missed doing 0.1.14 after releasing 0.1.13, so this is playing catch-up to compensate for the fact we've already released.
N/A
AGTMETRICS-233
=> chore(agent-data-plane): bump version to 0.1.15 to start next dev cycle

Makefile
Updates `cargo-nextest` to `0.9.99` to get around build/install errors with `0.9.72`.
Ensured relevant CI jobs didn't fail when installing `cargo-nextest`.
AGTMETRICS-233
=> chore(ci): update cargo-nextest to try and get around install error

bin/agent-data-plane/src/internal/observability.rs, lib/saluki-components/src/transforms/aggregate/mod.rs, lib/saluki-core/src/components/sources/context.rs, lib/saluki-core/src/components/transforms/context.rs, lib/saluki-core/src/pooling/mod.rs, lib/saluki-core/src/pooling/on_demand.rs, lib/saluki-core/src/topology/blueprint.rs, lib/saluki-core/src/topology/built.rs, lib/saluki-core/src/topology/interconnect/dispatcher.rs, lib/saluki-core/src/topology/mod.rs, test/smp/regression/saluki/cases/dsd_uds_1mb_50k_contexts_memlimit/experiment.yaml, test/smp/regression/saluki/cases/dsd_uds_50mb_10k_contexts_no_inlining/experiment.yaml, test/smp/regression/saluki/cases/dsd_uds_50mb_10k_contexts_no_inlining_no_allocs/experiment.yaml
This PR introduces a new "on demand" object pool and switches to using it for the global event buffer pool in order to address the risk of deadlock under high load.
The global event buffer pool is inextricably tied to components dispatching events to the next component in the topology. This means that many components, when there is a steady flow of metrics, are constantly acquiring event buffers and then dispatching them. In some cases, however, the volume of metrics can outpace the rate at which event buffers are processed, leading to scenarios where a deadlock is possible.
One such scenario is the aggregate transform. It processes incoming event buffers, aggregate the metrics within them, and then periodically flushes the aggregated metrics. In order to flush, it has to acquire event …
=> experiment(topology): try using an on-demand object pool for global event buffers pool

.gitlab-ci.yml, Makefile, docker/Dockerfile.datadog-agent
We're seeing issues with DockerHub rate limiting, so this PR switches to using an internal mirrored version of `ubuntu:24.04` instead. Additionally, we've bumped the version of the Datadog Agent that we test against while we were in there, to make sure everything is up-to-date.
N/A
AGTMETRICS-233
=> chore(ci): bump Datadog Agent version and use mirrored ubuntu image

bin/agent-data-plane/src/cli/run.rs, bin/agent-data-plane/src/internal/config.rs, bin/agent-data-plane/src/internal/mod.rs, bin/agent-data-plane/src/internal/observability.rs, bin/checks-agent/src/main.rs, lib/saluki-core/src/topology/blueprint.rs, lib/saluki-core/src/topology/built.rs, lib/saluki-core/src/topology/config.rs, lib/saluki-core/src/topology/mod.rs
This PR introduces the concept of `TopologyConfiguration`, a new trait designed to allow for type-driven configuration of a topology.
Every topology has a number of core aspects that control much of the implicit behavior: how component are connected, whether or not events are buffered between the components, and more. These aspects have always been hard-coded, more or less, in the various responsible pieces: `TopologyBlueprint`, `Dispatcher`, `FixedSizeEventBuffer`, and so on.
Our aim with this change is to start to lift these values and decisions up to a higher level, in the form of a generic type parameter on `TopologyBlueprint`, which implements `TopologyConfiguration`. The given configuration will be used to specify many of these values in a single place that can be applied uniformly …
=> chore(core): introduce `TopologyConfiguration` for configuration of topology blueprints

lib/process-memory/tests/no_runtime_allocations.rs
This PR marks the `no_runtime_allocations` test in the `process-memory` crate to be ignored on macOS as it has been very flaky over the past few months with the introduction of building/testing ADP on macOS in CI.
This test, as it is named, tries to assert we do no runtime allocations when using `process_memory::Querier`. The test often does pass on macOS, but then sometimes fails with a single allocation detected: a very small 160-180 byte allocation, at that.
It's very unclear what this allocation would be, especially given how small it is. While I'd like to not skip tests in general, this one is not _super_ valuable... not valuable enough, at least, to spend a bunch of time tracking it down. We'd rather have the CI be less flaky.
N/A
AGTMETRICS-233
=> chore(ci): ignore flaky 'no_runtime_allocations' test on macOS

Cargo.lock, bin/agent-data-plane/Cargo.toml, bin/agent-data-plane/src/cli/config.rs, bin/agent-data-plane/src/cli/mod.rs, bin/agent-data-plane/src/cli/run.rs, bin/agent-data-plane/src/config.rs, bin/agent-data-plane/src/internal/control_plane.rs, bin/agent-data-plane/src/internal/remote_agent.rs, bin/agent-data-plane/src/main.rs, lib/saluki-app/Cargo.toml, lib/saluki-app/src/config.rs, lib/saluki-app/src/lib.rs, lib/saluki-config/src/refresher.rs
This pr removes the task spawned in `RefresherConfig` that called `v1/config`. Instead, the config values will be populated by the `RemoteAgentImpl`. 
A new config subcommand is added along with a config api handler to display the config.
NOTE: We don't have a scrubber.
run adp with the agent
run `target/debug/agent-data-plane config` to see the initial config
update some configs `agent.exec config set log_level warn` for example
run `target/debug/agent-data-plane config` again to see the updated config
=> Add config subcommand

lib/saluki-components/src/destinations/datadog/common/telemetry.rs, lib/saluki-components/src/destinations/datadog/mod.rs, lib/saluki-components/src/destinations/mod.rs, lib/saluki-components/src/encoders/datadog/events/mod.rs, lib/saluki-components/src/encoders/datadog/mod.rs, lib/saluki-components/src/encoders/mod.rs, lib/saluki-components/src/lib.rs
This PR adds a basic `Encoder` implementation for Datadog Events.
We can't _do_ anything with it yet as we lack a forwarder implementation to use with it. That will be handled in a follow-up PR.
N/A
AGTMETRICS-233
=> enhancement(datadog): add Datadog Events encoder

bin/agent-data-plane/src/cli/run.rs, lib/saluki-components/src/destinations/datadog/mod.rs, lib/saluki-components/src/destinations/datadog/service_checks/mod.rs, lib/saluki-components/src/encoders/datadog/mod.rs, lib/saluki-components/src/encoders/datadog/service_checks/mod.rs, lib/saluki-components/src/encoders/mod.rs
This PR adds a new Datadog Service Checks encoder, following in the steps of #814 and #816.
Existing unit tests + basic local testing by sending service check payloads to ADP and observing them being sent to the configured endpoint.
AGTMETRICS-233
=> chore(datadog): move Datadog Service Checks destination to encoder

lib/saluki-components/src/encoders/buffered_incremental/mod.rs, lib/saluki-components/src/encoders/buffered_incremental/telemetry.rs, lib/saluki-components/src/encoders/mod.rs, lib/saluki-core/src/components/encoders/mod.rs
This PR adds a new encoder, `BufferedIncremental`, that is designed to drive an `IncrementalEncoder` implementation both off the main runtime (using the global thread pool) and with the ability to buffer events by driving payload flushing on an interval.
This encoder will be used for Datadog encoder implementations by allowing us to trim them down to be incremental encoders, only focusing on how to process events and how to flush them. This will allow us to reduce duplication, having one encoder for doing "off-thread encoding with buffering" instead of three, or more.
N/A
AGTMETRICS-233
=> enhancement(encoder): add new encoder for driving incremental encoders

bin/agent-data-plane/src/cli/run.rs, lib/saluki-components/src/common/datadog/request_builder.rs, lib/saluki-components/src/encoders/datadog/events/mod.rs
This PR migrates the Datadog Events encoder to an incremental encoder.
We've also slightly tweaked some error logic in `RequestBuilderError` since it occurred to me during refactoring that the previous logic wasn't quite right.
Existing unit tests. Built and ran ADP locally and sent events via DogStatsD, and ensured they were properly forwarded.
AGTMETRICS-233
=> chore(datadog): migrate Datadog Events encoder to incremental encoder

bin/agent-data-plane/src/cli/run.rs, lib/saluki-components/src/encoders/datadog/service_checks/mod.rs, lib/saluki-core/src/data_model/event/service_check/mod.rs
This PR migrates the Datadog Service Checks encoder to an incremental encoder.
We've also slightly tweaked the serialization behavior for `ServiceCheck`, as I noticed some of our recent work around origin detection for events/service checks left the serialized output a little non-standard.
Existing unit tests. Built and ran ADP locally and sent service checks via DogStatsD, and ensured they were properly forwarded.
AGTMETRICS-233
=> chore(datadog): migrate Datadog Service Checks encoder to incremental encoder

lib/saluki-components/src/common/datadog/request_builder.rs
This was a holdover from some of the recent refactoring work around Datadog destinations/encoders/forwarders. It pops up pretty often when deploying a recent development build of ADP to staging, but on the "pending flush" codepath... so it's not relevant at all to us here because the only other place it really matters if when we fill the request builder during encoding, and if it failed there, we would be hitting a panic.
I'll file an issue to try and clean up how we trigger a pending flush if there's nothing actually in the request builder when we process an event buffer.
N/A
AGTMETRICS-233
=> chore(datadog): drop noisy warning log in `RequestBuilder` when flush is empty

.gitlab/benchmark.yml, .gitlab/build.yml, .gitlab/correctness.yml
We've been hitting a number of timed out build jobs over the past few weeks for our ADP images. I've been chatting with the internal team responsible for the CI infrastructure about the _why_, but in the interim, we should tighten our job timeout to attempt to get away from a stalled job more quickly. This PR sets our timeout to 10m for all ADP/`checks-agent` builds as it's right around the p90 job duration for successful runs of those jobs.
This PR also removes all variables related to setting Kubernetes requests/limits for Docker build-based jobs, as they don't influence the underlying BuildKit worker used for building the image. We've kept them for test jobs, which is where we _do_ execute `cargo` directly on the top-level CI runner.
N/A
AGTMETRICS-233
=> chore(ci): tighten up timeouts for build jobs + remove unnecessary k8s requests/limits

Cargo.lock, Cargo.toml, bin/agent-data-plane/src/cli/run.rs, lib/saluki-common/Cargo.toml, lib/saluki-common/src/collections.rs, lib/saluki-context/Cargo.toml, lib/saluki-health/Cargo.toml, lib/saluki-health/src/api.rs, lib/saluki-health/src/lib.rs
This PR aims to fix what we believe is an issue with asynchronous registration of components in `HealthRegistry` which manifests as ADP failing to completely spawn the primary topology.
Currently, the health checker (`HealthRegistry`) uses incremental logic when deciding how to "register" a component: if after updating the internal state we determine that the health checker _task_ is already running, we try to send a message to inform it that we just registered a new component and that it should schedule liveness probes for it. We do this as when the health checker task initially starts, we schedule probes for all registered components that are present... but we need to make sure we properly schedule probes for components that come _after_ the task is spawned. Crucially, the code will …
=> fix(health): rework async registration to avoid deadlock

lib/saluki-components/src/sources/dogstatsd/resolver.rs
This PR just fixes a simple oversight where we forgot to enable cache expiration on the shared tags resolver used in the DogStatsD source. Without cache expiration, we end up essentially leaking memory until the tags resolver hits the configured tagset limit.
N/A
AGTMETRICS-233
=> fix(dogstatsd): enable cache expiration on shared tags resolver

.gitlab-ci.yml, .gitlab/benchmark.yml
This PR skips the SMP benchmarks for pushes to `main` and release tags. Since there's no reasonable "baseline" to test against, running the benchmarks doesn't make sense... and just ends up always failing which is confusing if you don't know that is expected.
Can't test this without actually merging. 😅 
AGTMETRICS-233
=> chore(ci): skip SMP benchmarks on pushes to main/release tags

lib/saluki-components/src/destinations/prometheus/mod.rs, lib/saluki-context/src/resolver.rs, lib/saluki-env/src/workload/collectors/containerd.rs, lib/saluki-env/src/workload/collectors/remote_agent/tagger.rs, lib/saluki-env/src/workload/collectors/remote_agent/workloadmeta.rs, lib/saluki-env/src/workload/helpers/cgroups.rs, lib/saluki-env/src/workload/on_demand_pid.rs, lib/stringtheory/src/interning/fixed_size.rs, lib/stringtheory/src/interning/map.rs, lib/stringtheory/src/interning/mod.rs, lib/stringtheory/src/lib.rs
This PR adds a new `Interner` trait to `stringtheory` to abstract over varying interner implementations. We've taken the common core methods of both `GenericMapInterner` and `FixedSizeInterner` as the basis for the trait methods.
Existing unit tests.
AGTMETRICS-233
=> chore(stringtheory): add `Interner` trait to generalize interners

.gitlab-ci.yml, .gitlab/build.yml
This PR adds two new build jobs, `build-adp-image-internal` and `build-adp-image-fips-internal`, that are meant to be used exclusively for internal deployments. They are configured to be built on a GBI base, ensuring they're suitable for our specific internal deployment requirements.
We previously tried to accomplish this -- sort of -- by varying the `ADP_APP_IMAGE` variable based on workflow rules, and whether or not `CI_COMMIT_TAG` was set. We actually implemented this logic _backwards_: we select the public base image (`ubuntu:24.04`) when a commit tag is present, and use the internal base image (GBI) otherwise. This is the opposite of what we want.
This PR fixes that, but it fixes it by going further: we don't just want official releases to use GBI for internal deployments, we want it …
=> chore(ci): always build internal images w/ GBI base

lib/saluki-components/src/sources/dogstatsd/filters.rs, lib/saluki-components/src/sources/dogstatsd/mod.rs, lib/saluki-components/src/sources/dogstatsd/origin.rs, lib/saluki-io/src/deser/codec/dogstatsd/mod.rs
This PR cleans up the old logic in the DogStatsD codec that handled parsing "well-known" tags and shuttling their values through the borrowed `*Packet<'a>` representations that the DogStatsD source works with.
Existing unit tests.
AGTMETRICS-233
=> chore(dogstatsd): remove handling of well-known tags from DSD codec

bin/agent-data-plane/src/cli/run.rs
This PR checks the `adp.use_new_config_stream_endpoint ` setting and only creates the config stream and blocks for the initial configuration when this setting is configured true.
Manually tested with setting `DD_ADP_USE_NEW_CONFIG_STREAM_ENDPOINT=true` versus no setting and setting as `false`.
=> chore: gate config stream creation and initial config blocking behind `adp.use_new_config_stream_endpoint`

lib/saluki-components/src/sources/dogstatsd/mod.rs, lib/saluki-components/src/sources/dogstatsd/resolver.rs
This pr adds configurability in the dogstatsd source for the cached contexts and tagsets limit.
=> chore: add configurability for cached contexts/tagsets limit

Cargo.lock, lib/saluki-common/Cargo.toml, lib/saluki-common/src/iter.rs, lib/saluki-common/src/lib.rs, lib/saluki-components/src/destinations/prometheus/mod.rs, lib/saluki-components/src/encoders/datadog/events/mod.rs, lib/saluki-components/src/encoders/datadog/metrics/mod.rs, lib/saluki-context/src/tags/mod.rs, lib/saluki-core/src/data_model/event/service_check/mod.rs
This PR adds a reusable deduplication helper, primarily for tag deduplication.
Currently, tags deduplication happens through the `Deduplicated` helper, exposed by `TagsExt::deduplicated`. This creates a wrapper iterator that uses a hash set internally to skip duplicates: simple and effective. However, one issue is that we're allocating a new hash set every time we create one of these helpers. This means we're (re)allocating constantly as we deduplicate tag sets when building request payloads for Datadog payloads, and so on.
This PR introduces a new helper, `ReusableDeduplicator`, that allows reusing the underlying hash set between iterators. We use it to create a wrapper iterator that borrows the hash set for as long as necessary to iterate and deduplicate.
Existing unit and correctness …
=> enhancement(common): reusable deduplication helper

Cargo.lock, lib/saluki-env/src/workload/collectors/mod.rs, lib/saluki-env/src/workload/collectors/remote_agent/tagger.rs, lib/saluki-env/src/workload/collectors/remote_agent/workloadmeta.rs, lib/saluki-io/Cargo.toml, lib/saluki-io/src/net/util/mod.rs, lib/saluki-io/src/net/util/tonic.rs
This PR includes a number of improvements/tweaks to the Remote Agent workload collectors. In so specific order:
- add actual telemetry to the `remote-agent-tags` collector, matching the `remote-agent-wmeta` collector
- add a wrapper for `tonic::Status` to provide a better `Display` implementation that doesn't end up looking like it's a `Debug` string (`Unavailable(tcp connect error)` vs `status: Unavailable, message: "tcp connect error", details: [], metadata: MetadataMap { headers: {} }`)
- tweak the metadata collector driver to retry watching after 2 seconds instead of 5 seconds to reduce the time spent without processing updates
Existing unit tests and built and ran ADP locally and ensured everything still looked correct.
AGTMETRICS-233
=> chore(env): improve remote agent workload collector logging and telemetry

lib/saluki-env/src/workload/helpers/containerd/mod.rs
We noticed in internal testing that we get responses to the `ListContainers` RPC call that exceed the default limit of 4MB, going as high as ~15MB. Setting a limit of 16MB should hopefully stop these errors entirely without being overly conservative.
N/A
AGTMETRICS-233
=> fix(env): increase container list containers response payload size limit to 16MB

lib/saluki-components/src/sources/dogstatsd/mod.rs
This PR improves two main aspects of the logging around framing/decoding errors in the DogStatsD source:
- emitting UDS stream partial write-related errors at debug instead of warn
- including the full frame for "failed to parse frame" logs
One common scenario with UDS streams is that clients will first write the length delimiter with a write timeout, and if the write completes, continue by writing the actual payload. In many cases, with just the right timing, we can manage to receive the length delimiter but the client believes they've timed out during the overall write operation.... and so they'll close the connection. This leads ADP to see the length delimiter, and then hit EOF after that. From a framer/decoder standpoint, we think we got a partial write at EOF... which may be real or …
=> chore(dogstatsd): improve logging around framing/decoding errors

Cargo.lock, LICENSE-3rdparty.csv, bin/agent-data-plane/src/cli/dogstatsd.rs, bin/agent-data-plane/src/config.rs, lib/saluki-components/Cargo.toml
This PR improves the memory usage of the `dogstatsd stats` command to try and avoid some of the issues associated with using it on high-traffic ADP processes.
We've noticed that when using it internally, the current approach is very susceptible to getting the process (the one for `dogstatsd stats`, not the underlying ADP process) killed by the OOM killer due to the vast amount of memory used. This is generally attributable to the fact that we have to accept a large stats payload, parse it into an intermediate state, and then build a big textual representation of it to write to stdout.
This PR introduces a number of small tweaks which dramatically improve the memory usage when using the command. Generally speaking, we've done two main things to improve the situation:
- write out the …
=> enhancement(agent-data-plane): improve memory usage of the `dogstatsd stats` subcommand

bin/agent-data-plane/src/cli/dogstatsd.rs
Built and ran ADP locally and ensured the log message was now in the right spot.
AGTMETRICS-233
=> fix(agent-data-plane): emit log message about waiting for DSD stats response _before_ we receive it

Cargo.lock
=> chore(agent-data-plane): bump `Cargo.lock` version to 0.1.21 to start next dev cycle 

lib/otlp-protos/build.rs, lib/otlp-protos/proto/opentelemetry/proto/collector/logs/v1/logs_service.proto, lib/otlp-protos/proto/opentelemetry/proto/logs/v1/logs.proto, lib/saluki-components/src/sources/otlp/metrics/translator.rs, lib/saluki-components/src/sources/otlp/mod.rs
Extends OTLP source enabling ADP to receive OTLP logs.
This PR merges into a feature branch, which is based off a [WIP branch](https://github.com/DataDog/saluki/pull/857).
Manual Testing:
Run 
`make run-adp-standalone`
Install
`brew install grpcurl`
then in a new terminal, send over a log using
```
grpcurl -plaintext \
-import-path /Users/andrew.qian/Documents/Code/saluki/lib/otlp-protos/proto \
-proto opentelemetry/proto/collector/logs/v1/logs_service.proto \
-d @ 127.0.0.1:4317 \
opentelemetry.proto.collector.logs.v1.LogsService/Export <<'JSON'
{
"resourceLogs": [
{
"resource": {
"attributes": [
{ "key": "service.name", "value": { "stringValue": "saluki-adp" } }
]
},
"scopeLogs": [
{
"scope": { "name": "test-client", "version": "0.1.0" },
"logRecords": [
{
"timeUnixNano": "0", …
```
=> [AGNTLOG-299] Add otlp log source

Cargo.lock, lib/saluki-components/src/transforms/dogstatsd_prefix_filter/mod.rs, lib/saluki-config/Cargo.toml, lib/saluki-config/src/dynamic/watcher.rs, lib/saluki-config/src/lib.rs
This pr adds a method `ConfigurationLoader::for_tests` and also a bunch of unit tests that uses this method.
The dynamic updater has also been updated to handle nested keys that use "`.`". Previously, it would just create the key on the top level of the map object. 
Unit tests
=> chore(saluki-config): add `ConfigurationLoader::for_tests`

.github/workflows/docs.yml
We forgot to add a dependency to the new `generate-api-docs` job step in #929 so the publishing step fails before it gets invoked before the `generate-api-docs` job step completes.
N/A
AGTMETRICS-233
=> fix(docs): add job dependency for API docs before trying to publish docs site

lib/saluki-components/src/sources/dogstatsd/origin.rs
We had `dogstatsd_origin_detection_unified` when it should have been `origin_detection_unified`. 🤷🏻 
AGTMETRICS-233
=> fix(dogstatsd): read the correct configuration setting for unified origin detection

bin/agent-data-plane/src/cli/run.rs, lib/saluki-components/src/common/datadog/endpoints.rs, lib/saluki-components/src/common/datadog/middleware.rs, lib/saluki-components/src/encoders/datadog/logs/mod.rs, lib/saluki-components/src/encoders/datadog/mod.rs, lib/saluki-components/src/encoders/mod.rs, lib/saluki-components/src/forwarders/datadog/mod.rs, lib/saluki-components/src/sources/otlp/logs/transform.rs, lib/saluki-components/src/sources/otlp/mod.rs, lib/saluki-core/src/data_model/event/log/mod.rs
The encoder component will batch/compress DD native logs and transform them into a JSON payload format and send them to the existing Datadog forwarder component in ADP. It completes the functionality for Otel log ingestion in ADP.
This is a follow up to this [PR](https://github.com/DataDog/saluki/pull/905)
**Manual testing, send the same request to the agent and adp**
Note: changing the host can cause an issue for log visibility in logs explorer because I am using an index to filter for my logs.
**ADP**
Run ADP with OTLP logs enabled
`DD_ADP_OTLP_ENABLED=true DD_OTLP_CONFIG='{}' RUST_LOG=info make run-adp-standalone`
Install grpcurl
`brew install grpcurl`
Send request
```
TIME_NS=$(python3 -c 'import time; print(time.time_ns())')
grpcurl -plaintext \
-import-path …
```
=> [AGNTLOG-314] Add Logs Encoder enabling OTLP logs ingest

bin/agent-data-plane/src/cli/run.rs, bin/agent-data-plane/src/config.rs, bin/agent-data-plane/src/main.rs, lib/saluki-app/src/bootstrap.rs, lib/saluki-app/src/lib.rs, test/smp/regression/adp-checks-agent/cases/quality_gates_rss_basic/experiment.yaml, test/smp/regression/adp-checks-agent/cases/quality_gates_rss_idle/experiment.yaml, test/smp/regression/adp/cases/dsd_uds_100mb_3k_contexts_throughput/experiment.yaml, test/smp/regression/adp/cases/dsd_uds_10mb_3k_contexts_throughput/experiment.yaml, test/smp/regression/adp/cases/dsd_uds_1mb_3k_contexts_throughput/experiment.yaml, test/smp/regression/adp/cases/dsd_uds_500mb_3k_contexts_throughput/experiment.yaml, test/smp/regression/adp/cases/dsd_uds_512kb_3k_contexts_throughput/experiment.yaml, test/smp/regression/adp/cases/quality_gates_rss_dsd_heavy/experiment.yaml, test/smp/regression/adp/cases/quality_gates_rss_dsd_low/experiment.yaml, test/smp/regression/adp/cases/quality_gates_rss_dsd_medium/experiment.yaml, test/smp/regression/adp/cases/quality_gates_rss_dsd_ultraheavy/experiment.yaml, test/smp/regression/adp/cases/quality_gates_rss_idle/experiment.yaml
This PR adds a new flag to the `run` subcommand, `--pidfile`/`-p`, which takes a path to a file where the process ID should be written out to.
When specified, the process ID will be written out. If any error occurs when writing to the PID file, the process will exit, consistent with the behavior of the Core Agent. When no PID file is specified, we skip the behavior entirely.
We've also slightly changed some other related bits:
- specifying the subcommand to run is no longer optional (this simplified using the new flag, and we no longer have any usages of ADP where the `run` subcommand isn't specified)
- new `bootstrap` module in `saluki-app` for one-off functions like writing the PID file
- added the `process_id` file to ADP's startup message just to make logs a little easier to correlate …
=> chore(agent-data-plane): add new pidfile flag to run subcommand for writing self PID to a file

Cargo.lock, Cargo.toml, deny.toml
We depended on a particular branch of `triomphe` that added a method we use for buffer management. The PR for that change was finally merged and released, so we're now switching back to a properly versioned release of the crate.
Existing unit tests.
AGTMETRICS-233
=> chore(deps): switch back to released version of `triomphe`

Cargo.lock, Makefile, bin/agent-data-plane/Cargo.toml, bin/agent-data-plane/src/cli/run.rs, bin/agent-data-plane/src/config.rs, bin/agent-data-plane/src/internal/control_plane.rs, bin/agent-data-plane/src/internal/mod.rs, bin/agent-data-plane/src/internal/platform/linux_impl.rs, bin/agent-data-plane/src/internal/platform/mod.rs, bin/agent-data-plane/src/main.rs, bin/correctness/airlock/Cargo.toml, bin/correctness/ground-truth/Cargo.toml, lib/saluki-app/Cargo.toml, lib/saluki-app/src/bootstrap.rs, lib/saluki-app/src/lib.rs, lib/saluki-app/src/logging/config.rs, lib/saluki-app/src/logging/mod.rs, lib/saluki-app/src/memory.rs, lib/saluki-app/src/metrics/mod.rs, lib/saluki-app/src/tls.rs, lib/saluki-config/src/lib.rs, lib/saluki-core/src/observability/metrics.rs, lib/saluki-tls/src/lib.rs
This PR consolidates all application initialization logic into a new helper, `AppBootstrapper`.
There's a lot of files touched here, so here's the high-level overview:
- we don't want people executing piecemeal `initialize_foo` functions, because it means things can get missed: we want an opinionated way to bootstrap a data plane application that we can centrally update/control
- `AppBootstrapper` acts as this new centralized mechanism, taking in a configuration file that controls how we configure various subsystems (namely logging) and ensuring we're always uniformly initializing logging, metrics, allocator telemetry, and TLS (and anything else we want to add in the future)
- since we're always initializing these subsystems now, we've removed all the feature flagging bits from …
=> enhancement(app): consolidate bootstrapping logic into `AppBootstrapper`
