.gitlab/single-machine-performance/regression_detector-dogstatsd.yml
.gitlab/single-machine-performance/regression_detector.yml
test/smp/regression/dogstatsd/config.yaml
test/smp/regression/saluki/config.yaml

This lading update is intended to solve the "sheering" problem, see https://github.com/DataDog/lading/pull/879 for details. It's an rc yet to confirm that the fix behaves as expected.

Update lading to 0.21.0-rc1

---

test/smp/regression/dogstatsd/config.yaml
test/smp/regression/saluki/config.yaml

See https://github.com/DataDog/lading/pull/890 for details.

Update to lading 0.21.0

---

Cargo.lock
Cargo.toml
bin/agent-data-plane/src/main.rs
lib/saluki-components/Cargo.toml
lib/saluki-components/src/sources/checks/mod.rs

Reads the check configuration YAML and started the code to look for the py sources.
For now this PR only looks for the py sources in the same dir as the checks config (i.e. `conf.d`)

Reads the checks YAML configuration file and looks for the .py in the same dir

---

lib/saluki-context/src/lib.rs
lib/stringtheory/src/lib.rs

This PR adds an experimental "inlined" mode to `MetaString`.
We've added a new variant to the inner enum, `Inlined`, that wraps a new type, `InlinedString`, which is sized to be as large as the largest existing variant: `Shared`, which is based on `bytes::Bytes`, which is 32 bytes. The `Inlined` variant can store up to 31 bytes (1 byte needed for string length).
We've added a new method for fallibly trying to create an inlined `MetaString` (`MetaString::try_inline`) which we've then integrated into `ContextResolver`. It will now try first to inline the string, and if that fails, fallback to trying to intern and then potentially allocating.
This should (hopefully) massively improve performance and reduce interner pressure for inline-able strings, since we're already paying the cost of …

stringtheory/context: add support for inlined strings

---

Cargo.toml
Makefile
bin/agent-data-plane/Cargo.toml
lib/datadog-protos/Cargo.toml
lib/ddsketch-agent/Cargo.toml
lib/memory-accounting/Cargo.toml
lib/saluki-app/Cargo.toml
lib/saluki-components/Cargo.toml
lib/saluki-config/Cargo.toml
lib/saluki-context/Cargo.toml
lib/saluki-core/Cargo.toml
lib/saluki-env/Cargo.toml
lib/saluki-error/Cargo.toml
lib/saluki-event/Cargo.toml
lib/saluki-io/Cargo.toml
lib/saluki-metrics/Cargo.toml
lib/stringtheory/Cargo.toml
tomlfmt.toml

chore: clean up Cargo.toml files and add more things to fmt make target

---

Cargo.lock
LICENSE-3rdparty.csv

Just doing it all in one shot -- including things Dependabot didn't touch -- and doing it as a PR to make sure there's no obvious performance regressions.

chore: update dependencies

---

lib/saluki-io/src/deser/codec/dogstatsd/mod.rs

experiment: try making tags parsing faster

---

Cargo.lock
Cargo.toml
LICENSE-3rdparty.csv
lib/datadog-protos/build.rs
lib/saluki-tls/src/lib.rs

chore: bunch of dependency updates

---

bin/agent-data-plane/src/components/remapper/rules/aggregation.rs
bin/agent-data-plane/src/components/remapper/rules/dogstatsd.rs

Simple change to remap two more internal metrics.

chore: add two more internal metrics to remap

---

bin/agent-data-plane/src/components/remapper/rules/aggregation.rs
bin/agent-data-plane/src/components/remapper/rules/dogstatsd.rs
lib/saluki-components/src/sources/dogstatsd/mod.rs
lib/saluki-io/src/deser/codec/dogstatsd/mod.rs

chore: remap more internal telemetry

---

lib/saluki-components/src/sources/dogstatsd/mod.rs
lib/saluki-io/src/deser/codec/dogstatsd/mod.rs

During testing, we stumbled across the fact that the Datadog Agent is currently more permissive in its decoding of DSD payloads than the DSD specification itself. Specifically, it does not enforce the validation of metric names to be only ASCII alphanumerics, underscores, and periods, but allows essentially any character value.
As it is a primary goal of ADP to be able to replace the DSD support in the Datadog Agent, we need to be able to handle equivalent DSD payloads.
This PR adds support for "permissive" decoding in the DSD codec, which changes how we parse the metric name. In non-permissive mode, everything functions according to the DSD specification. In permissive mode, we take any many characters that are ASCII printable as possible up until we see the metric name delimiter (`:`). …

chore: add support for permissive decoding in DSD codec

---

lib/saluki-io/src/deser/codec/dogstatsd/mod.rs

This PR fixes a bug with the parsing of the message field for DogStatsD service check payloads. Currently, we use the incorrect method for grabbing the message string, which unreasonably limits the allowed characters. This causing parsing to stop early, leading to parsing errors due to the remaining of valid messages appearing as a nonsensical field.
We've simply switched to parsing the entire separated message field as UTF-8, and so long as it's valid UTF-8, then that's what we ingest. There's also now a unit test for this, which is more in the style of a proptest regression case since it's just a failing input we used to diagnose the bug and is now otherwise fixed.

fix: properly accept UTF-8 for DSD service check message field

---

Cargo.lock
lib/saluki-app/src/api.rs
lib/saluki-env/src/helpers/mod.rs
lib/saluki-env/src/helpers/remote_agent/client.rs
lib/saluki-env/src/helpers/remote_agent/mod.rs
lib/saluki-env/src/helpers/tonic.rs
lib/saluki-env/src/lib.rs
lib/saluki-io/src/net/server/http.rs
lib/saluki-io/src/net/server/multiplex_service.rs

chore: docs polish for API/HTTP builder code

---

.gitlab/benchmark.yml

As part of keeping this project up-to-date with the latest stable `smp` CLI version, this pull request updates the `smp` version used in CI from 0.20.1 to 0.20.2.
Submitted this PR.
n/a

chore(ci): update smp to 0.20.2

---

lib/saluki-context/src/hash.rs
lib/saluki-context/src/resolver.rs

In #415, we made a number of changes related to origin enrichment, one of which involved bundling the "origin" key -- a spiritual equivalent to `ContextKey`, but for origin data -- into `ContextKey` itself.
This had the side effect of changing the size of `ContextKey` from 8 bytes (`u64`) to 24 bytes (`u64` + `Option<OriginKey>`, where `OriginKey` was just a `u64`). As `ContextKey` is the key type for our actual context cache in `ContextResolver`, this means we're spending more memory for every cached context.
We've slightly reworked how we generate, and pass around, the `OriginKey` during context resolving. We've also folded in the hash of the origin key to the context's hash itself, rather than carrying the origin key as a separate field. This brings `ContextKey` back down to 8 bytes.

chore: fold `OriginKey` hash into main hash to shrink `ContextKey`

---

.github/CODEOWNERS

Update the `CODEOWNERS` file to reflect the new team name.
N/A

[chore] Update CODEOWNERS

---

lib/saluki-components/src/destinations/datadog/metrics/request_builder.rs

In #306, we added the ability to properly split a request's payload in order to handle scenarios where our estimates about the compressed size of a payload (since we don't _really_ know until we actually try to finalize the compressor) were incorrect and the compressed size exceeded the allowable limit. This meant that instead of having to naively throw away the entire request, losing those metrics in the process, we would try again by building _two_ requests, each containing half of the metrics from the original request.
However, the approach that we chose to take -- maintaining all encoded (but uncompressed) metrics in the scratch buffer -- is fairly memory inefficient. This was a miss on my part, as I pushed for this in code review. Essentially, in high load scenarios, our scratch …

chore: update the request splitting logic for Datadog Metrics destination to be more memory efficient

---

Cargo.lock
LICENSE-3rdparty.csv
lib/process-memory/Cargo.toml
lib/process-memory/src/darwin.rs
lib/saluki-env/src/workload/mod.rs
lib/saluki-env/src/workload/providers/remote_agent/mod.rs

chore: fix some compilation/clippy errors on darwin

---

lib/saluki-io/src/compression.rs

In the Datadog Metrics destination, we use `CompressionEstimator` in order to attempt to mark a payload as having reached its maximum size based on the _estimated_ compressed size of the payload, such that when we finalize the current payload, its compressed size does not exceed the compressed size limit. This provides the main benefit of avoiding needing to split the payload into two if we correctly avoid writing too many metrics, such that the compressed size limit is exceeded.
In our benchmarks/regression experiments, `CompressionEstimator` works well, and often maximizes the compressed size of payloads to within a few percent of the compressed size limit. However, in real staging workloads, we observed a pathological degradation where payloads were being flushed at a compressed size …

fix: don't block compressor writes prior to any compressed output

---

lib/saluki-components/src/sources/dogstatsd/filters/mod.rs
lib/saluki-components/src/sources/dogstatsd/mod.rs

Add payloads filter for events and service checks
- Unit tests
- Manual test of setting `DD_ENABLE_PAYLOADS_EVENTS` and `DD_ENABLE_PAYLOADS_SERVICE_CHECKS` to false and making sure the payloads aren't sent.
- Closes #387

chore: add payloads filter for events and service checks

---

lib/saluki-components/src/transforms/aggregate/mod.rs

In the `aggregate` transform, we follow the behavior of the Datadog Agent where counters are converted to rates before flushing. Counters and rates are conceptually identical, except that a rate encodes the duration over which a counter was collected. If you aggregated updates to a counter for 10 seconds, and then converted it to a rate, the rate's "interval" is 10 seconds: the period over which its value was collected. The reason we do this is mostly historical and relates to maintaining the behavior encoded in the Datadog Agent.
Additionally, however, the `aggregate` transform can passthrough pre-aggregated metrics -- metrics that are timestamped and should be flushed immediately -- as well, and in this area, the `aggregate` transform does not follow the Datadog Agent correctly, as it …

fix: convert pre-aggregated counters to rates as well

---

test/smp/regression/dogstatsd/config.yaml
test/smp/regression/saluki/config.yaml

Release notes: https://github.com/DataDog/lading/releases/tag/v0.25.6

Update lading to 0.25.6

---

.ci/images/build/Dockerfile
bin/agent-data-plane/src/api/remote_agent/mod.rs
lib/memory-accounting/src/allocator.rs
lib/memory-accounting/src/lib.rs
lib/memory-accounting/src/registry.rs
lib/memory-accounting/src/test_util.rs
lib/saluki-app/src/logging.rs
lib/saluki-config/src/secrets/resolver/external.rs
lib/saluki-context/src/origin.rs
lib/saluki-context/src/tags/mod.rs
lib/saluki-core/src/topology/interconnect/event_buffer.rs
lib/saluki-core/src/topology/interconnect/forwarder.rs
lib/saluki-env/src/helpers/remote_agent/client.rs
lib/saluki-env/src/workload/entity.rs
lib/saluki-env/src/workload/helpers/cgroups.rs
lib/saluki-env/src/workload/stores/tag.rs
lib/saluki-event/src/metric/value/histogram.rs
lib/saluki-event/src/metric/value/iter.rs
lib/saluki-event/src/metric/value/mod.rs
lib/saluki-io/src/buf/mod.rs
lib/saluki-io/src/deser/framing/mod.rs
lib/saluki-io/src/net/util/retry/lifecycle/http.rs
rust-toolchain.toml

Bumps our Rust version to 1.85.
N/A
N/A

chore: update to Rust 1.85

---

lib/saluki-components/src/destinations/datadog/events_service_checks/mod.rs

This pr updates the datadog events/servicechecks destination to match the behavior of the metrics destination to simply grab the next event buffer instead of grabbing all available buffers.
Sent event and service check to datadog and made sure it still worked.

chore: chunk up the processing of event buffers in datadog events/service checks destination.

---

test/smp/regression/dogstatsd/config.yaml
test/smp/regression/saluki/config.yaml

Updates to the latest lading version which includes additional telemetry.
https://github.com/DataDog/lading/releases/tag/v0.25.7

feat: enable latest lading version

---

lib/saluki-components/src/sources/dogstatsd/mod.rs

Just a little bit of logging cleanup in the DogStatsD source to:
- improve log message structure
- make some low-volume events visible at the DEBUG level instead of trace
N/A
N/A

[AGTINFR-770] chore(dogstatsd): better log levels for separating out low vs high-volume events

---

lib/saluki-components/src/sources/dogstatsd/filters.rs
lib/saluki-components/src/sources/dogstatsd/mod.rs

This PR is a very simple change to try to clean up/optimize our "filters" capability in the DogStatsD source.
While we may have more filters we want to chain in the future, the current reality is that we only have the "enabled payloads" filter. As such, the PR removes all of the `Filter` trait machinery, and just utilizes `EnabledPayloadsFilter` directly. This lets us get rid of the dynamic dispatch involved, and some clones.
Utilized existing unit tests.
N/A

refactor(dogstatsd): de-traitify pre-filters

---

lib/saluki-components/src/transforms/dogstatsd_mapper/mod.rs
lib/saluki-context/src/resolver.rs

This PR primarily improves the telemetry of the context resolver, in terms of getting telemetry updates out of the hot path for resolving, as well as resolving some overreporting.
Utilized existing unit tests and ran correctness test harness.
Closes #571.

enhancement(contexts): improve context resolver telemetry and slightly improve non-cached overhead

---

lib/saluki-core/src/observability/metrics.rs

As part of our internal metrics, we have to collect and translate metrics from their native `metrics` format into our internal metrics format. Doing so primarily requires collapsing "labels" (`metrics` parlance), which are individual key/value pairs, into our internal tags (`saluki` parlance), which are single values that are either bare keys (like `env`), or concatenated key/value pairs (like `env:prod`). As we have to do this every single time we try to resolve a context via `ContextResolver`, we lose out on a lot of the potential savings of getting a cached context as we're still allocating a bunch of strings to hold the concatenated labels/tags.
This PR wraps `ContextResolver` and combines it with a simple cache, which maps the metrics "key" (`metrics::Key`, the equivalent of …

enhancement: cache key/context mappings for internal metrics

---

.gitlab-ci.yml
.gitlab/correctness.yml

Just cleaning up some old, unused variables and switching old hard-coded references to the new ones, and so on.
N/A
N/A

chore(ci): a little cleanup of build job

---

Cargo.lock
LICENSE-3rdparty.csv

chore(deps): routine dependency updates

---

test/smp/regression/checks-agent/config.yaml

Enable profiling for the check-agent binary in SMP

[AGENTRUN-244] chore(checks-agent) enable profiling for the checks-agentv in SMP

---

Cargo.lock
bin/agent-data-plane/Cargo.toml

chore(agent-data-plane): bump version to 0.1.11 to start next dev cycle

---

lib/saluki-components/src/destinations/datadog/common/transaction.rs

fix(datadog): implement `Body::size_hint` for `TransactionBody<B>` to fix metrics

---

Cargo.lock
bin/agent-data-plane/Cargo.toml

chore(agent-data-plane): bump version to 0.1.13 to start next dev cycle

---

lib/saluki-context/src/expiry.rs

This PR changes the expiration state used for cached contexts/tagsets to only track the last access time, rather than also the number of accesses. The previous approach let us make the "mark accessed" operation cheaper by not constantly querying the time, and utilizing an approximation... but at the cost of an additional 8 bytes in struct size: 16 bytes total for every cache entry.
Instead, we now track only the last access time, and update it directly on every access, using "coarse" time, added in #744. This should be almost as cheap, if not exactly as cheap, as the previous approach... but with a 50% reduction in the size of `AccessState`.
N/A
AGTMETRICS-233

enhancement(context): only track last access time for cached values via coarse time

---

.ci/images/smp/Dockerfile
.gitlab-ci.yml

Use the `24.04.4-jammy` for Docker images
Fixes https://app.datadoghq.com/cases/CS-86

chore: upgrade ubuntu image for the docker images

---

bin/agent-data-plane/src/cli/run.rs

stop sending host tags for preaggr payloads

---

docs/agent-data-plane/releasing.md

chore(docs): fix old/incorrect release documentation

---

lib/saluki-components/src/transforms/aggregate/mod.rs

Right now, after flushing a lot of infrequent metrics, our aggregate state still remains the capacity used to hold those contexts in the first place... which can end up being a lot of memory!
We know we want to clear that excess capacity if we don't need it, but the "do we still need it?" part is tricky. This PR is simply trying out an approach of shrinking the capacity down by half of whatever was removed during a flush.
For example, if we have 100k contexts, and flush 50k of them... we now have 50k left but enough capacity for 100k. No bueno. This PR will now shrink the capacity down to 75k: 50k left + 50% of the flush delta, or 25k. Based on the halving, we can expect that anytime we flush a chunk of contexts, assuming they don't immediately come back, we'll recover 90% of the memory …

experiment(aggregate): shrink context map by half of removed contexts after flush

---

.gitlab/benchmark.yml

Updates SMP CLI in tandem with an the v24 SMP infra release

Update SMP cli to v0.24.1

---

lib/saluki-components/src/sources/dogstatsd/origin.rs

This PR changes the enrichment logic in the DogStatsD source to use the highest precedence container ID instead of attempting to enrich via all available container IDs. It is a sister PR to https://github.com/DataDog/datadog-agent/pull/41195.
In some cases, the container ID we detect via External Data can be stale due to how long it takes for the new container ID to be detected when a container is restarted in the same pod UID, and thus how long it takes for us to receive the new tags for that External Data entry. In many cases, we already have the "true" container ID via either the detected process ID (UDS peer credentials) or "Local Data", where the metric contains a structured field (i.e., `|c:<container ID here>`) that provides the container ID as detected by the client. This makes it …

fix(dogstatsd): use highest precedence container ID when enriching metrics

---

Cargo.lock
bin/agent-data-plane/Cargo.toml

chore(agent-data-plane): bump version to 0.1.23
